// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSetup = `-- name: CompleteSetup :one
UPDATE app_config SET
  soc_module_enabled = $1,
  noc_module_enabled = $2,
  setup_completed_at = now(),
  updated_at = now()
WHERE id = true
RETURNING id, shift_check_cooldown_hours, alert_nok_enabled, alert_nok_role_target, audit_ttl_days, backup_retention_days, soc_module_enabled, noc_module_enabled, territorial_kind_labels, setup_completed_at, updated_at
`

type CompleteSetupParams struct {
	SocModuleEnabled bool `json:"soc_module_enabled"`
	NocModuleEnabled bool `json:"noc_module_enabled"`
}

func (q *Queries) CompleteSetup(ctx context.Context, arg CompleteSetupParams) (AppConfig, error) {
	row := q.db.QueryRow(ctx, completeSetup, arg.SocModuleEnabled, arg.NocModuleEnabled)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.ShiftCheckCooldownHours,
		&i.AlertNokEnabled,
		&i.AlertNokRoleTarget,
		&i.AuditTtlDays,
		&i.BackupRetentionDays,
		&i.SocModuleEnabled,
		&i.NocModuleEnabled,
		&i.TerritorialKindLabels,
		&i.SetupCompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureAppConfigRow = `-- name: EnsureAppConfigRow :exec
INSERT INTO app_config (id) VALUES (true) ON CONFLICT (id) DO NOTHING
`

// app_config es singleton pero no viene precargado por la migración inicial
// (03-esquema-db.sql no tiene un INSERT semilla) — GET /api/setup/status
// necesita una fila para leer, así que se asegura antes de leer si todavía
// no existe, con los defaults de la propia tabla.
func (q *Queries) EnsureAppConfigRow(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureAppConfigRow)
	return err
}

const getAppConfig = `-- name: GetAppConfig :one
SELECT id, shift_check_cooldown_hours, alert_nok_enabled, alert_nok_role_target, audit_ttl_days, backup_retention_days, soc_module_enabled, noc_module_enabled, territorial_kind_labels, setup_completed_at, updated_at FROM app_config WHERE id = true
`

func (q *Queries) GetAppConfig(ctx context.Context) (AppConfig, error) {
	row := q.db.QueryRow(ctx, getAppConfig)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.ShiftCheckCooldownHours,
		&i.AlertNokEnabled,
		&i.AlertNokRoleTarget,
		&i.AuditTtlDays,
		&i.BackupRetentionDays,
		&i.SocModuleEnabled,
		&i.NocModuleEnabled,
		&i.TerritorialKindLabels,
		&i.SetupCompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mergeTerritorialLabels = `-- name: MergeTerritorialLabels :one
UPDATE app_config SET
  territorial_kind_labels = territorial_kind_labels || $1::jsonb,
  updated_at = now()
WHERE id = true
RETURNING territorial_kind_labels
`

// PATCH /api/config/territorial-labels — merge parcial (jsonb ||): solo pisa
// los niveles que vienen en el request, el resto queda como estaba.
func (q *Queries) MergeTerritorialLabels(ctx context.Context, labels []byte) ([]byte, error) {
	row := q.db.QueryRow(ctx, mergeTerritorialLabels, labels)
	var territorial_kind_labels []byte
	err := row.Scan(&territorial_kind_labels)
	return territorial_kind_labels, err
}

const setModuleFlags = `-- name: SetModuleFlags :one
UPDATE app_config SET
  soc_module_enabled = COALESCE($1, soc_module_enabled),
  noc_module_enabled = COALESCE($2, noc_module_enabled),
  updated_at = now()
WHERE id = true
RETURNING id, shift_check_cooldown_hours, alert_nok_enabled, alert_nok_role_target, audit_ttl_days, backup_retention_days, soc_module_enabled, noc_module_enabled, territorial_kind_labels, setup_completed_at, updated_at
`

type SetModuleFlagsParams struct {
	SocModuleEnabled pgtype.Bool `json:"soc_module_enabled"`
	NocModuleEnabled pgtype.Bool `json:"noc_module_enabled"`
}

func (q *Queries) SetModuleFlags(ctx context.Context, arg SetModuleFlagsParams) (AppConfig, error) {
	row := q.db.QueryRow(ctx, setModuleFlags, arg.SocModuleEnabled, arg.NocModuleEnabled)
	var i AppConfig
	err := row.Scan(
		&i.ID,
		&i.ShiftCheckCooldownHours,
		&i.AlertNokEnabled,
		&i.AlertNokRoleTarget,
		&i.AuditTtlDays,
		&i.BackupRetentionDays,
		&i.SocModuleEnabled,
		&i.NocModuleEnabled,
		&i.TerritorialKindLabels,
		&i.SetupCompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
