// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_log
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (
  id, event, level, actor_user_id, actor_username, actor_role,
  request_id, request_ip, request_path, request_method,
  user_agent, device_fingerprint, ip_changed, previous_ip,
  success, reason, source, source_id, metadata
) VALUES (
  $19, $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10, $11, $12, $13,
  $14, $15, $16, $17, $18
)
`

type InsertAuditLogParams struct {
	Event             string      `json:"event"`
	Level             string      `json:"level"`
	ActorUserID       pgtype.UUID `json:"actor_user_id"`
	ActorUsername     pgtype.Text `json:"actor_username"`
	ActorRole         pgtype.Text `json:"actor_role"`
	RequestID         pgtype.Text `json:"request_id"`
	RequestIp         pgtype.Text `json:"request_ip"`
	RequestPath       pgtype.Text `json:"request_path"`
	RequestMethod     pgtype.Text `json:"request_method"`
	UserAgent         pgtype.Text `json:"user_agent"`
	DeviceFingerprint pgtype.Text `json:"device_fingerprint"`
	IpChanged         bool        `json:"ip_changed"`
	PreviousIp        pgtype.Text `json:"previous_ip"`
	Success           bool        `json:"success"`
	Reason            pgtype.Text `json:"reason"`
	Source            string      `json:"source"`
	SourceID          pgtype.Text `json:"source_id"`
	Metadata          []byte      `json:"metadata"`
	ID                uuid.UUID   `json:"id"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Event,
		arg.Level,
		arg.ActorUserID,
		arg.ActorUsername,
		arg.ActorRole,
		arg.RequestID,
		arg.RequestIp,
		arg.RequestPath,
		arg.RequestMethod,
		arg.UserAgent,
		arg.DeviceFingerprint,
		arg.IpChanged,
		arg.PreviousIp,
		arg.Success,
		arg.Reason,
		arg.Source,
		arg.SourceID,
		arg.Metadata,
		arg.ID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, timestamp, event, level, actor_user_id, actor_username, actor_role, request_id, request_ip, request_path, request_method, user_agent, device_fingerprint, ip_changed, previous_ip, success, reason, source, source_id, metadata FROM audit_log
ORDER BY "timestamp" DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// GET /api/audit-logs — paginado simple, más reciente primero.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.Level,
			&i.ActorUserID,
			&i.ActorUsername,
			&i.ActorRole,
			&i.RequestID,
			&i.RequestIp,
			&i.RequestPath,
			&i.RequestMethod,
			&i.UserAgent,
			&i.DeviceFingerprint,
			&i.IpChanged,
			&i.PreviousIp,
			&i.Success,
			&i.Reason,
			&i.Source,
			&i.SourceID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
