// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_log
WHERE ($1::text[] IS NULL
       OR EXISTS (SELECT 1 FROM unnest($1::text[]) AS p(prefix) WHERE event = p.prefix OR starts_with(event, p.prefix || '.')))
  AND ($2::text IS NULL OR level = $2)
  AND ($3::boolean IS NULL OR success = $3)
  AND ($4::uuid IS NULL OR actor_user_id = $4)
  AND ($5::timestamptz IS NULL OR "timestamp" >= $5)
  AND ($6::timestamptz IS NULL OR "timestamp" < $6)
  AND ($7::text IS NULL
       OR actor_username ILIKE '%' || $7 || '%'
       OR request_ip ILIKE '%' || $7 || '%'
       OR request_path ILIKE '%' || $7 || '%'
       OR event ILIKE '%' || $7 || '%'
       OR reason ILIKE '%' || $7 || '%')
`

type CountAuditLogsParams struct {
	Events      []string           `json:"events"`
	Level       pgtype.Text        `json:"level"`
	Success     pgtype.Bool        `json:"success"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	FromDate    pgtype.Timestamptz `json:"from_date"`
	ToDate      pgtype.Timestamptz `json:"to_date"`
	Q           pgtype.Text        `json:"q"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.Events,
		arg.Level,
		arg.Success,
		arg.ActorUserID,
		arg.FromDate,
		arg.ToDate,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (
  id, event, level, actor_user_id, actor_username, actor_role,
  request_id, request_ip, request_path, request_method,
  user_agent, device_fingerprint, ip_changed, previous_ip,
  success, reason, source, source_id, metadata
) VALUES (
  $19, $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10, $11, $12, $13,
  $14, $15, $16, $17, $18
)
`

type InsertAuditLogParams struct {
	Event             string      `json:"event"`
	Level             string      `json:"level"`
	ActorUserID       pgtype.UUID `json:"actor_user_id"`
	ActorUsername     pgtype.Text `json:"actor_username"`
	ActorRole         pgtype.Text `json:"actor_role"`
	RequestID         pgtype.Text `json:"request_id"`
	RequestIp         pgtype.Text `json:"request_ip"`
	RequestPath       pgtype.Text `json:"request_path"`
	RequestMethod     pgtype.Text `json:"request_method"`
	UserAgent         pgtype.Text `json:"user_agent"`
	DeviceFingerprint pgtype.Text `json:"device_fingerprint"`
	IpChanged         bool        `json:"ip_changed"`
	PreviousIp        pgtype.Text `json:"previous_ip"`
	Success           bool        `json:"success"`
	Reason            pgtype.Text `json:"reason"`
	Source            string      `json:"source"`
	SourceID          pgtype.Text `json:"source_id"`
	Metadata          []byte      `json:"metadata"`
	ID                uuid.UUID   `json:"id"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Event,
		arg.Level,
		arg.ActorUserID,
		arg.ActorUsername,
		arg.ActorRole,
		arg.RequestID,
		arg.RequestIp,
		arg.RequestPath,
		arg.RequestMethod,
		arg.UserAgent,
		arg.DeviceFingerprint,
		arg.IpChanged,
		arg.PreviousIp,
		arg.Success,
		arg.Reason,
		arg.Source,
		arg.SourceID,
		arg.Metadata,
		arg.ID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many

SELECT id, timestamp, event, level, actor_user_id, actor_username, actor_role, request_id, request_ip, request_path, request_method, user_agent, device_fingerprint, ip_changed, previous_ip, success, reason, source, source_id, metadata FROM audit_log
WHERE ($1::text[] IS NULL
       OR EXISTS (SELECT 1 FROM unnest($1::text[]) AS p(prefix) WHERE event = p.prefix OR starts_with(event, p.prefix || '.')))
  AND ($2::text IS NULL OR level = $2)
  AND ($3::boolean IS NULL OR success = $3)
  AND ($4::uuid IS NULL OR actor_user_id = $4)
  AND ($5::timestamptz IS NULL OR "timestamp" >= $5)
  AND ($6::timestamptz IS NULL OR "timestamp" < $6)
  AND ($7::text IS NULL
       OR actor_username ILIKE '%' || $7 || '%'
       OR request_ip ILIKE '%' || $7 || '%'
       OR request_path ILIKE '%' || $7 || '%'
       OR event ILIKE '%' || $7 || '%'
       OR reason ILIKE '%' || $7 || '%')
ORDER BY "timestamp" DESC
LIMIT $9 OFFSET $8
`

type ListAuditLogsParams struct {
	Events      []string           `json:"events"`
	Level       pgtype.Text        `json:"level"`
	Success     pgtype.Bool        `json:"success"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	FromDate    pgtype.Timestamptz `json:"from_date"`
	ToDate      pgtype.Timestamptz `json:"to_date"`
	Q           pgtype.Text        `json:"q"`
	PageOffset  int32              `json:"page_offset"`
	PageLimit   int32              `json:"page_limit"`
}

// Los tres comparten el mismo filtro (GET /api/audit-logs y su /export):
//
//	events  dominios o eventos exactos: ["auth","setup"] trae auth.login.fail, setup.bootstrap…
//	level   info | warn | error
//	success true = resultado OK, false = fallo
//	q       texto libre sobre actor, IP, ruta, evento y motivo (ya escapado para LIKE)
//
// Más reciente primero.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Events,
		arg.Level,
		arg.Success,
		arg.ActorUserID,
		arg.FromDate,
		arg.ToDate,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.Level,
			&i.ActorUserID,
			&i.ActorUsername,
			&i.ActorRole,
			&i.RequestID,
			&i.RequestIp,
			&i.RequestPath,
			&i.RequestMethod,
			&i.UserAgent,
			&i.DeviceFingerprint,
			&i.IpChanged,
			&i.PreviousIp,
			&i.Success,
			&i.Reason,
			&i.Source,
			&i.SourceID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsForExport = `-- name: ListAuditLogsForExport :many
SELECT id, timestamp, event, level, actor_user_id, actor_username, actor_role, request_id, request_ip, request_path, request_method, user_agent, device_fingerprint, ip_changed, previous_ip, success, reason, source, source_id, metadata FROM audit_log
WHERE ($1::text[] IS NULL
       OR EXISTS (SELECT 1 FROM unnest($1::text[]) AS p(prefix) WHERE event = p.prefix OR starts_with(event, p.prefix || '.')))
  AND ($2::text IS NULL OR level = $2)
  AND ($3::boolean IS NULL OR success = $3)
  AND ($4::uuid IS NULL OR actor_user_id = $4)
  AND ($5::timestamptz IS NULL OR "timestamp" >= $5)
  AND ($6::timestamptz IS NULL OR "timestamp" < $6)
  AND ($7::text IS NULL
       OR actor_username ILIKE '%' || $7 || '%'
       OR request_ip ILIKE '%' || $7 || '%'
       OR request_path ILIKE '%' || $7 || '%'
       OR event ILIKE '%' || $7 || '%'
       OR reason ILIKE '%' || $7 || '%')
ORDER BY "timestamp" DESC
`

type ListAuditLogsForExportParams struct {
	Events      []string           `json:"events"`
	Level       pgtype.Text        `json:"level"`
	Success     pgtype.Bool        `json:"success"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	FromDate    pgtype.Timestamptz `json:"from_date"`
	ToDate      pgtype.Timestamptz `json:"to_date"`
	Q           pgtype.Text        `json:"q"`
}

func (q *Queries) ListAuditLogsForExport(ctx context.Context, arg ListAuditLogsForExportParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForExport,
		arg.Events,
		arg.Level,
		arg.Success,
		arg.ActorUserID,
		arg.FromDate,
		arg.ToDate,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.Level,
			&i.ActorUserID,
			&i.ActorUsername,
			&i.ActorRole,
			&i.RequestID,
			&i.RequestIp,
			&i.RequestPath,
			&i.RequestMethod,
			&i.UserAgent,
			&i.DeviceFingerprint,
			&i.IpChanged,
			&i.PreviousIp,
			&i.Success,
			&i.Reason,
			&i.Source,
			&i.SourceID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
