// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBackupRuns = `-- name: CountBackupRuns :one
SELECT count(*) FROM backup_runs WHERE ($1::backup_kind IS NULL OR kind=$1)
`

func (q *Queries) CountBackupRuns(ctx context.Context, kind NullBackupKind) (int64, error) {
	row := q.db.QueryRow(ctx, countBackupRuns, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBackupRun = `-- name: CreateBackupRun :one
INSERT INTO backup_runs (kind, window_from, window_to, triggered_by)
VALUES ($1, $3, $4, $2) RETURNING id, kind, window_from, window_to, records_count, started_at, finished_at, status, file_path, file_size_bytes, checksum_sha256, compression_algorithm, encrypted, triggered_by, error_message
`

type CreateBackupRunParams struct {
	Kind        BackupKind         `json:"kind"`
	TriggeredBy pgtype.UUID        `json:"triggered_by"`
	WindowFrom  pgtype.Timestamptz `json:"window_from"`
	WindowTo    pgtype.Timestamptz `json:"window_to"`
}

func (q *Queries) CreateBackupRun(ctx context.Context, arg CreateBackupRunParams) (BackupRun, error) {
	row := q.db.QueryRow(ctx, createBackupRun,
		arg.Kind,
		arg.TriggeredBy,
		arg.WindowFrom,
		arg.WindowTo,
	)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.WindowFrom,
		&i.WindowTo,
		&i.RecordsCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.ChecksumSha256,
		&i.CompressionAlgorithm,
		&i.Encrypted,
		&i.TriggeredBy,
		&i.ErrorMessage,
	)
	return i, err
}

const deleteBackupRun = `-- name: DeleteBackupRun :one
DELETE FROM backup_runs WHERE id=$1 RETURNING id, kind, window_from, window_to, records_count, started_at, finished_at, status, file_path, file_size_bytes, checksum_sha256, compression_algorithm, encrypted, triggered_by, error_message
`

func (q *Queries) DeleteBackupRun(ctx context.Context, id uuid.UUID) (BackupRun, error) {
	row := q.db.QueryRow(ctx, deleteBackupRun, id)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.WindowFrom,
		&i.WindowTo,
		&i.RecordsCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.ChecksumSha256,
		&i.CompressionAlgorithm,
		&i.Encrypted,
		&i.TriggeredBy,
		&i.ErrorMessage,
	)
	return i, err
}

const getBackupRun = `-- name: GetBackupRun :one
SELECT id, kind, window_from, window_to, records_count, started_at, finished_at, status, file_path, file_size_bytes, checksum_sha256, compression_algorithm, encrypted, triggered_by, error_message FROM backup_runs WHERE id=$1
`

func (q *Queries) GetBackupRun(ctx context.Context, id uuid.UUID) (BackupRun, error) {
	row := q.db.QueryRow(ctx, getBackupRun, id)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.WindowFrom,
		&i.WindowTo,
		&i.RecordsCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.ChecksumSha256,
		&i.CompressionAlgorithm,
		&i.Encrypted,
		&i.TriggeredBy,
		&i.ErrorMessage,
	)
	return i, err
}

const listBackupRuns = `-- name: ListBackupRuns :many
SELECT id, kind, window_from, window_to, records_count, started_at, finished_at, status, file_path, file_size_bytes, checksum_sha256, compression_algorithm, encrypted, triggered_by, error_message FROM backup_runs WHERE ($1::backup_kind IS NULL OR kind=$1) ORDER BY started_at DESC LIMIT $3 OFFSET $2
`

type ListBackupRunsParams struct {
	Kind   NullBackupKind `json:"kind"`
	Offset int32          `json:"offset"`
	Limit  int32          `json:"limit"`
}

func (q *Queries) ListBackupRuns(ctx context.Context, arg ListBackupRunsParams) ([]BackupRun, error) {
	rows, err := q.db.Query(ctx, listBackupRuns, arg.Kind, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupRun
	for rows.Next() {
		var i BackupRun
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.WindowFrom,
			&i.WindowTo,
			&i.RecordsCount,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.FilePath,
			&i.FileSizeBytes,
			&i.ChecksumSha256,
			&i.CompressionAlgorithm,
			&i.Encrypted,
			&i.TriggeredBy,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupRun = `-- name: MarkBackupRun :one
UPDATE backup_runs SET records_count=$2, finished_at=now(), status=$3, file_path=$4, file_size_bytes=$5, checksum_sha256=$6, error_message=$7 WHERE id=$1 RETURNING id, kind, window_from, window_to, records_count, started_at, finished_at, status, file_path, file_size_bytes, checksum_sha256, compression_algorithm, encrypted, triggered_by, error_message
`

type MarkBackupRunParams struct {
	ID             uuid.UUID   `json:"id"`
	RecordsCount   int32       `json:"records_count"`
	Status         string      `json:"status"`
	FilePath       pgtype.Text `json:"file_path"`
	FileSizeBytes  pgtype.Int8 `json:"file_size_bytes"`
	ChecksumSha256 pgtype.Text `json:"checksum_sha256"`
	ErrorMessage   pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkBackupRun(ctx context.Context, arg MarkBackupRunParams) (BackupRun, error) {
	row := q.db.QueryRow(ctx, markBackupRun,
		arg.ID,
		arg.RecordsCount,
		arg.Status,
		arg.FilePath,
		arg.FileSizeBytes,
		arg.ChecksumSha256,
		arg.ErrorMessage,
	)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.WindowFrom,
		&i.WindowTo,
		&i.RecordsCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.FilePath,
		&i.FileSizeBytes,
		&i.ChecksumSha256,
		&i.CompressionAlgorithm,
		&i.Encrypted,
		&i.TriggeredBy,
		&i.ErrorMessage,
	)
	return i, err
}
