// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branding.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBranding = `-- name: GetBranding :one

SELECT app_title, title_font, font_name, incident_palette, bulletin_color, login_theme, favicon_url, version, updated_at,
  (logo IS NOT NULL)::boolean AS has_logo, (favicon IS NOT NULL)::boolean AS has_favicon, (font_file IS NOT NULL)::boolean AS has_font, logo_name
FROM app_branding WHERE id = true
`

type GetBrandingRow struct {
	AppTitle        string             `json:"app_title"`
	TitleFont       string             `json:"title_font"`
	FontName        pgtype.Text        `json:"font_name"`
	IncidentPalette string             `json:"incident_palette"`
	BulletinColor   string             `json:"bulletin_color"`
	LoginTheme      pgtype.Text        `json:"login_theme"`
	FaviconUrl      pgtype.Text        `json:"favicon_url"`
	Version         int32              `json:"version"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	HasLogo         bool               `json:"has_logo"`
	HasFavicon      bool               `json:"has_favicon"`
	HasFont         bool               `json:"has_font"`
	LogoName        pgtype.Text        `json:"logo_name"`
}

// ===== Marca (comentario del dueño #8) =====
// Sin los archivos: lo que necesitan la barra, el login y los correos.
func (q *Queries) GetBranding(ctx context.Context) (GetBrandingRow, error) {
	row := q.db.QueryRow(ctx, getBranding)
	var i GetBrandingRow
	err := row.Scan(
		&i.AppTitle,
		&i.TitleFont,
		&i.FontName,
		&i.IncidentPalette,
		&i.BulletinColor,
		&i.LoginTheme,
		&i.FaviconUrl,
		&i.Version,
		&i.UpdatedAt,
		&i.HasLogo,
		&i.HasFavicon,
		&i.HasFont,
		&i.LogoName,
	)
	return i, err
}

const getBrandingFavicon = `-- name: GetBrandingFavicon :one
SELECT favicon, favicon_type FROM app_branding WHERE id = true AND favicon IS NOT NULL
`

type GetBrandingFaviconRow struct {
	Favicon     []byte      `json:"favicon"`
	FaviconType pgtype.Text `json:"favicon_type"`
}

func (q *Queries) GetBrandingFavicon(ctx context.Context) (GetBrandingFaviconRow, error) {
	row := q.db.QueryRow(ctx, getBrandingFavicon)
	var i GetBrandingFaviconRow
	err := row.Scan(&i.Favicon, &i.FaviconType)
	return i, err
}

const getBrandingFont = `-- name: GetBrandingFont :one
SELECT font_file, font_type, font_name FROM app_branding WHERE id = true AND font_file IS NOT NULL
`

type GetBrandingFontRow struct {
	FontFile []byte      `json:"font_file"`
	FontType pgtype.Text `json:"font_type"`
	FontName pgtype.Text `json:"font_name"`
}

func (q *Queries) GetBrandingFont(ctx context.Context) (GetBrandingFontRow, error) {
	row := q.db.QueryRow(ctx, getBrandingFont)
	var i GetBrandingFontRow
	err := row.Scan(&i.FontFile, &i.FontType, &i.FontName)
	return i, err
}

const getBrandingLogo = `-- name: GetBrandingLogo :one
SELECT logo, logo_type FROM app_branding WHERE id = true AND logo IS NOT NULL
`

type GetBrandingLogoRow struct {
	Logo     []byte      `json:"logo"`
	LogoType pgtype.Text `json:"logo_type"`
}

func (q *Queries) GetBrandingLogo(ctx context.Context) (GetBrandingLogoRow, error) {
	row := q.db.QueryRow(ctx, getBrandingLogo)
	var i GetBrandingLogoRow
	err := row.Scan(&i.Logo, &i.LogoType)
	return i, err
}

const setBrandingFavicon = `-- name: SetBrandingFavicon :exec
UPDATE app_branding SET favicon = $1, favicon_type = $2,
  favicon_url = CASE WHEN $1::bytea IS NOT NULL THEN NULL ELSE favicon_url END,
  version = version + 1, updated_by = $3, updated_at = now()
WHERE id = true
`

type SetBrandingFaviconParams struct {
	Favicon     []byte      `json:"favicon"`
	FaviconType pgtype.Text `json:"favicon_type"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SetBrandingFavicon(ctx context.Context, arg SetBrandingFaviconParams) error {
	_, err := q.db.Exec(ctx, setBrandingFavicon, arg.Favicon, arg.FaviconType, arg.UpdatedBy)
	return err
}

const setBrandingFont = `-- name: SetBrandingFont :exec
UPDATE app_branding SET font_file = $1, font_type = $2, font_name = $3,
  title_font = CASE WHEN $1::bytea IS NULL THEN 'inter' ELSE 'custom' END,
  version = version + 1, updated_by = $4, updated_at = now()
WHERE id = true
`

type SetBrandingFontParams struct {
	FontFile  []byte      `json:"font_file"`
	FontType  pgtype.Text `json:"font_type"`
	FontName  pgtype.Text `json:"font_name"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SetBrandingFont(ctx context.Context, arg SetBrandingFontParams) error {
	_, err := q.db.Exec(ctx, setBrandingFont,
		arg.FontFile,
		arg.FontType,
		arg.FontName,
		arg.UpdatedBy,
	)
	return err
}

const setBrandingLogo = `-- name: SetBrandingLogo :exec
UPDATE app_branding SET logo = $1, logo_type = $2, logo_name = $3,
  version = version + 1, updated_by = $4, updated_at = now()
WHERE id = true
`

type SetBrandingLogoParams struct {
	Logo      []byte      `json:"logo"`
	LogoType  pgtype.Text `json:"logo_type"`
	LogoName  pgtype.Text `json:"logo_name"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SetBrandingLogo(ctx context.Context, arg SetBrandingLogoParams) error {
	_, err := q.db.Exec(ctx, setBrandingLogo,
		arg.Logo,
		arg.LogoType,
		arg.LogoName,
		arg.UpdatedBy,
	)
	return err
}

const updateBranding = `-- name: UpdateBranding :exec
UPDATE app_branding SET
  app_title = COALESCE($1, app_title),
  title_font = COALESCE($2, title_font),
  incident_palette = COALESCE($3, incident_palette),
  bulletin_color = COALESCE($4, bulletin_color),
  login_theme = CASE WHEN $5::boolean THEN $6 ELSE login_theme END,
  favicon_url = CASE WHEN $7::boolean THEN $8 ELSE favicon_url END,
  version = version + 1, updated_by = $9, updated_at = now()
WHERE id = true
`

type UpdateBrandingParams struct {
	AppTitle        pgtype.Text `json:"app_title"`
	TitleFont       pgtype.Text `json:"title_font"`
	IncidentPalette pgtype.Text `json:"incident_palette"`
	BulletinColor   pgtype.Text `json:"bulletin_color"`
	SetLoginTheme   bool        `json:"set_login_theme"`
	LoginTheme      pgtype.Text `json:"login_theme"`
	SetFaviconUrl   bool        `json:"set_favicon_url"`
	FaviconUrl      pgtype.Text `json:"favicon_url"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateBranding(ctx context.Context, arg UpdateBrandingParams) error {
	_, err := q.db.Exec(ctx, updateBranding,
		arg.AppTitle,
		arg.TitleFont,
		arg.IncidentPalette,
		arg.BulletinColor,
		arg.SetLoginTheme,
		arg.LoginTheme,
		arg.SetFaviconUrl,
		arg.FaviconUrl,
		arg.UpdatedBy,
	)
	return err
}
