// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeShiftClosure = `-- name: AcknowledgeShiftClosure :one
UPDATE shift_closures SET acknowledged_by = $2, acknowledged_at = $3 WHERE id = $1 AND acknowledged_at IS NULL RETURNING id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at
`

type AcknowledgeShiftClosureParams struct {
	ID             uuid.UUID          `json:"id"`
	AcknowledgedBy pgtype.UUID        `json:"acknowledged_by"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
}

func (q *Queries) AcknowledgeShiftClosure(ctx context.Context, arg AcknowledgeShiftClosureParams) (ShiftClosure, error) {
	row := q.db.QueryRow(ctx, acknowledgeShiftClosure, arg.ID, arg.AcknowledgedBy, arg.AcknowledgedAt)
	var i ShiftClosure
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.ClosureCheckID,
		&i.TotalEntries,
		&i.TotalIncidents,
		&i.ServicesDown,
		&i.Observations,
		&i.PendingForNextShift,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.TicketsResolvedCount,
		&i.SlaBreachesCount,
		&i.SentVia,
		&i.IntegrationName,
		&i.SentStatus,
		&i.SentError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const countEntriesInWindow = `-- name: CountEntriesInWindow :one
SELECT count(*) FROM entries WHERE created_at >= $1 AND created_at < $2
`

type CountEntriesInWindowParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) CountEntriesInWindow(ctx context.Context, arg CountEntriesInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntriesInWindow, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIncidentEntriesInWindow = `-- name: CountIncidentEntriesInWindow :one
SELECT count(*) FROM entries WHERE entry_type = 'incidente' AND created_at >= $1 AND created_at < $2
`

type CountIncidentEntriesInWindowParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) CountIncidentEntriesInWindow(ctx context.Context, arg CountIncidentEntriesInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidentEntriesInWindow, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResolvedTicketsInWindow = `-- name: CountResolvedTicketsInWindow :one
SELECT count(*) FROM tickets WHERE status IN ('resolved', 'closed') AND resolved_at >= $1 AND resolved_at < $2
`

type CountResolvedTicketsInWindowParams struct {
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	ResolvedAt_2 pgtype.Timestamptz `json:"resolved_at_2"`
}

func (q *Queries) CountResolvedTicketsInWindow(ctx context.Context, arg CountResolvedTicketsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResolvedTicketsInWindow, arg.ResolvedAt, arg.ResolvedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSLABreachesInWindow = `-- name: CountSLABreachesInWindow :one
SELECT count(*) FROM tickets WHERE sla_resolution_due_at IS NOT NULL AND resolved_at > sla_resolution_due_at + make_interval(secs => sla_paused_seconds) AND resolved_at >= $1 AND resolved_at < $2
`

type CountSLABreachesInWindowParams struct {
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	ResolvedAt_2 pgtype.Timestamptz `json:"resolved_at_2"`
}

func (q *Queries) CountSLABreachesInWindow(ctx context.Context, arg CountSLABreachesInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSLABreachesInWindow, arg.ResolvedAt, arg.ResolvedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChecklistEntry = `-- name: CreateChecklistEntry :one
INSERT INTO entries (user_id, entry_type, scope, content, tags, work_shift_id)
VALUES ($1, 'checklist', 'general', $2, $3, $4) RETURNING id, user_id, entry_type, scope, content, tags, service_id, asset_id, work_shift_id, glpi_ticket_id, glpi_linked_at, ticket_id, image_url, image_hash, image_size_bytes, created_at, updated_at
`

type CreateChecklistEntryParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Content     string      `json:"content"`
	Tags        []string    `json:"tags"`
	WorkShiftID pgtype.UUID `json:"work_shift_id"`
}

func (q *Queries) CreateChecklistEntry(ctx context.Context, arg CreateChecklistEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createChecklistEntry,
		arg.UserID,
		arg.Content,
		arg.Tags,
		arg.WorkShiftID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryType,
		&i.Scope,
		&i.Content,
		&i.Tags,
		&i.ServiceID,
		&i.AssetID,
		&i.WorkShiftID,
		&i.GlpiTicketID,
		&i.GlpiLinkedAt,
		&i.TicketID,
		&i.ImageUrl,
		&i.ImageHash,
		&i.ImageSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShiftCheck = `-- name: CreateShiftCheck :one
INSERT INTO shift_checks (checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services
`

type CreateShiftCheckParams struct {
	ChecklistTemplateID uuid.UUID          `json:"checklist_template_id"`
	UserID              uuid.UUID          `json:"user_id"`
	WorkShiftID         uuid.UUID          `json:"work_shift_id"`
	CheckType           ChecklistCheckType `json:"check_type"`
	CheckDate           pgtype.Timestamptz `json:"check_date"`
	HasRedServices      bool               `json:"has_red_services"`
}

func (q *Queries) CreateShiftCheck(ctx context.Context, arg CreateShiftCheckParams) (ShiftCheck, error) {
	row := q.db.QueryRow(ctx, createShiftCheck,
		arg.ChecklistTemplateID,
		arg.UserID,
		arg.WorkShiftID,
		arg.CheckType,
		arg.CheckDate,
		arg.HasRedServices,
	)
	var i ShiftCheck
	err := row.Scan(
		&i.ID,
		&i.ChecklistTemplateID,
		&i.UserID,
		&i.WorkShiftID,
		&i.CheckType,
		&i.CheckDate,
		&i.HasRedServices,
	)
	return i, err
}

const createShiftCheckService = `-- name: CreateShiftCheckService :one
INSERT INTO shift_check_services (shift_check_id, checklist_item_id, service_title, status, is_computed, observation, correlated_from_service_id)
VALUES ($1, $5, $2, $3, $4, $6, $7) RETURNING id, shift_check_id, checklist_item_id, service_title, status, is_computed, observation, correlated_from_service_id
`

type CreateShiftCheckServiceParams struct {
	ShiftCheckID            uuid.UUID       `json:"shift_check_id"`
	ServiceTitle            string          `json:"service_title"`
	Status                  ChecklistStatus `json:"status"`
	IsComputed              bool            `json:"is_computed"`
	ChecklistItemID         pgtype.UUID     `json:"checklist_item_id"`
	Observation             pgtype.Text     `json:"observation"`
	CorrelatedFromServiceID pgtype.UUID     `json:"correlated_from_service_id"`
}

func (q *Queries) CreateShiftCheckService(ctx context.Context, arg CreateShiftCheckServiceParams) (ShiftCheckService, error) {
	row := q.db.QueryRow(ctx, createShiftCheckService,
		arg.ShiftCheckID,
		arg.ServiceTitle,
		arg.Status,
		arg.IsComputed,
		arg.ChecklistItemID,
		arg.Observation,
		arg.CorrelatedFromServiceID,
	)
	var i ShiftCheckService
	err := row.Scan(
		&i.ID,
		&i.ShiftCheckID,
		&i.ChecklistItemID,
		&i.ServiceTitle,
		&i.Status,
		&i.IsComputed,
		&i.Observation,
		&i.CorrelatedFromServiceID,
	)
	return i, err
}

const createShiftClosure = `-- name: CreateShiftClosure :one
INSERT INTO shift_closures (user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, tickets_resolved_count, sla_breaches_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $10, $11, $8, $9) RETURNING id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at
`

type CreateShiftClosureParams struct {
	UserID               uuid.UUID          `json:"user_id"`
	ShiftStartAt         pgtype.Timestamptz `json:"shift_start_at"`
	ShiftEndAt           pgtype.Timestamptz `json:"shift_end_at"`
	ClosureCheckID       uuid.UUID          `json:"closure_check_id"`
	TotalEntries         int32              `json:"total_entries"`
	TotalIncidents       int32              `json:"total_incidents"`
	ServicesDown         []string           `json:"services_down"`
	TicketsResolvedCount int32              `json:"tickets_resolved_count"`
	SlaBreachesCount     int32              `json:"sla_breaches_count"`
	Observations         pgtype.Text        `json:"observations"`
	PendingForNextShift  pgtype.Text        `json:"pending_for_next_shift"`
}

func (q *Queries) CreateShiftClosure(ctx context.Context, arg CreateShiftClosureParams) (ShiftClosure, error) {
	row := q.db.QueryRow(ctx, createShiftClosure,
		arg.UserID,
		arg.ShiftStartAt,
		arg.ShiftEndAt,
		arg.ClosureCheckID,
		arg.TotalEntries,
		arg.TotalIncidents,
		arg.ServicesDown,
		arg.TicketsResolvedCount,
		arg.SlaBreachesCount,
		arg.Observations,
		arg.PendingForNextShift,
	)
	var i ShiftClosure
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.ClosureCheckID,
		&i.TotalEntries,
		&i.TotalIncidents,
		&i.ServicesDown,
		&i.Observations,
		&i.PendingForNextShift,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.TicketsResolvedCount,
		&i.SlaBreachesCount,
		&i.SentVia,
		&i.IntegrationName,
		&i.SentStatus,
		&i.SentError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveChecklistTemplate = `-- name: GetActiveChecklistTemplate :one
SELECT id, name, is_active, alert_nok_enabled, alert_nok_role_target, created_at FROM checklist_templates WHERE id = $1 AND is_active = true
`

func (q *Queries) GetActiveChecklistTemplate(ctx context.Context, id uuid.UUID) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, getActiveChecklistTemplate, id)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.AlertNokEnabled,
		&i.AlertNokRoleTarget,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestShiftCheck = `-- name: GetLatestShiftCheck :one
SELECT id, checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services FROM shift_checks WHERE work_shift_id = $1 ORDER BY check_date DESC LIMIT 1
`

func (q *Queries) GetLatestShiftCheck(ctx context.Context, workShiftID uuid.UUID) (ShiftCheck, error) {
	row := q.db.QueryRow(ctx, getLatestShiftCheck, workShiftID)
	var i ShiftCheck
	err := row.Scan(
		&i.ID,
		&i.ChecklistTemplateID,
		&i.UserID,
		&i.WorkShiftID,
		&i.CheckType,
		&i.CheckDate,
		&i.HasRedServices,
	)
	return i, err
}

const getLatestShiftClosure = `-- name: GetLatestShiftClosure :one
SELECT id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at FROM shift_closures ORDER BY shift_end_at DESC LIMIT 1
`

func (q *Queries) GetLatestShiftClosure(ctx context.Context) (ShiftClosure, error) {
	row := q.db.QueryRow(ctx, getLatestShiftClosure)
	var i ShiftClosure
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.ClosureCheckID,
		&i.TotalEntries,
		&i.TotalIncidents,
		&i.ServicesDown,
		&i.Observations,
		&i.PendingForNextShift,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.TicketsResolvedCount,
		&i.SlaBreachesCount,
		&i.SentVia,
		&i.IntegrationName,
		&i.SentStatus,
		&i.SentError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getShiftCheck = `-- name: GetShiftCheck :one
SELECT id, checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services FROM shift_checks WHERE id = $1
`

func (q *Queries) GetShiftCheck(ctx context.Context, id uuid.UUID) (ShiftCheck, error) {
	row := q.db.QueryRow(ctx, getShiftCheck, id)
	var i ShiftCheck
	err := row.Scan(
		&i.ID,
		&i.ChecklistTemplateID,
		&i.UserID,
		&i.WorkShiftID,
		&i.CheckType,
		&i.CheckDate,
		&i.HasRedServices,
	)
	return i, err
}

const getShiftClosure = `-- name: GetShiftClosure :one
SELECT id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at FROM shift_closures WHERE id = $1
`

func (q *Queries) GetShiftClosure(ctx context.Context, id uuid.UUID) (ShiftClosure, error) {
	row := q.db.QueryRow(ctx, getShiftClosure, id)
	var i ShiftClosure
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.ClosureCheckID,
		&i.TotalEntries,
		&i.TotalIncidents,
		&i.ServicesDown,
		&i.Observations,
		&i.PendingForNextShift,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.TicketsResolvedCount,
		&i.SlaBreachesCount,
		&i.SentVia,
		&i.IntegrationName,
		&i.SentStatus,
		&i.SentError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkCorrelatedShiftCheckService = `-- name: LinkCorrelatedShiftCheckService :one
UPDATE shift_check_services SET correlated_from_service_id = $2 WHERE id = $1 RETURNING id, shift_check_id, checklist_item_id, service_title, status, is_computed, observation, correlated_from_service_id
`

type LinkCorrelatedShiftCheckServiceParams struct {
	ID                      uuid.UUID   `json:"id"`
	CorrelatedFromServiceID pgtype.UUID `json:"correlated_from_service_id"`
}

func (q *Queries) LinkCorrelatedShiftCheckService(ctx context.Context, arg LinkCorrelatedShiftCheckServiceParams) (ShiftCheckService, error) {
	row := q.db.QueryRow(ctx, linkCorrelatedShiftCheckService, arg.ID, arg.CorrelatedFromServiceID)
	var i ShiftCheckService
	err := row.Scan(
		&i.ID,
		&i.ShiftCheckID,
		&i.ChecklistItemID,
		&i.ServiceTitle,
		&i.Status,
		&i.IsComputed,
		&i.Observation,
		&i.CorrelatedFromServiceID,
	)
	return i, err
}

const listActiveChecklistTemplates = `-- name: ListActiveChecklistTemplates :many
SELECT id, name, is_active, alert_nok_enabled, alert_nok_role_target, created_at FROM checklist_templates WHERE is_active = true ORDER BY name
`

func (q *Queries) ListActiveChecklistTemplates(ctx context.Context) ([]ChecklistTemplate, error) {
	rows, err := q.db.Query(ctx, listActiveChecklistTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistTemplate
	for rows.Next() {
		var i ChecklistTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.AlertNokEnabled,
			&i.AlertNokRoleTarget,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT id, template_id, parent_item_id, title, item_order FROM checklist_items WHERE template_id = $1 ORDER BY item_order, id
`

func (q *Queries) ListChecklistItems(ctx context.Context, templateID uuid.UUID) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItems, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistItem
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ParentItemID,
			&i.Title,
			&i.ItemOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandoverOnCall = `-- name: ListHandoverOnCall :many
SELECT DISTINCT ON (t.id) t.id AS team_id, t.name AS team_name,
  COALESCE(u.username, c.name, '')::text AS on_call_member
FROM teams t
JOIN rotation_cycles rc ON rc.team_id = t.id AND rc.active = true
JOIN rotation_slots rs ON rs.cycle_id = rc.id
  AND rs.week_start_date <= $1::date
  AND rs.week_end_date >= $1::date
  AND rs.is_paused = false
JOIN team_members tm ON tm.id = rs.team_member_id AND tm.active = true
LEFT JOIN users u ON u.id = tm.user_id
LEFT JOIN contacts c ON c.id = tm.contact_id
WHERE t.active = true
  AND ($2::uuid IS NULL OR t.id = $2)
ORDER BY t.id, tm.priority DESC, tm.id
`

type ListHandoverOnCallParams struct {
	Today  pgtype.Date `json:"today"`
	TeamID pgtype.UUID `json:"team_id"`
}

type ListHandoverOnCallRow struct {
	TeamID       uuid.UUID `json:"team_id"`
	TeamName     string    `json:"team_name"`
	OnCallMember string    `json:"on_call_member"`
}

func (q *Queries) ListHandoverOnCall(ctx context.Context, arg ListHandoverOnCallParams) ([]ListHandoverOnCallRow, error) {
	rows, err := q.db.Query(ctx, listHandoverOnCall, arg.Today, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandoverOnCallRow
	for rows.Next() {
		var i ListHandoverOnCallRow
		if err := rows.Scan(&i.TeamID, &i.TeamName, &i.OnCallMember); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingShiftClosures = `-- name: ListPendingShiftClosures :many
SELECT id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at FROM shift_closures WHERE sent_status = 'pending' ORDER BY shift_end_at ASC
`

func (q *Queries) ListPendingShiftClosures(ctx context.Context) ([]ShiftClosure, error) {
	rows, err := q.db.Query(ctx, listPendingShiftClosures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftClosure
	for rows.Next() {
		var i ShiftClosure
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShiftStartAt,
			&i.ShiftEndAt,
			&i.ClosureCheckID,
			&i.TotalEntries,
			&i.TotalIncidents,
			&i.ServicesDown,
			&i.Observations,
			&i.PendingForNextShift,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.TicketsResolvedCount,
			&i.SlaBreachesCount,
			&i.SentVia,
			&i.IntegrationName,
			&i.SentStatus,
			&i.SentError,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftCheckServices = `-- name: ListShiftCheckServices :many
SELECT id, shift_check_id, checklist_item_id, service_title, status, is_computed, observation, correlated_from_service_id FROM shift_check_services WHERE shift_check_id = $1 ORDER BY id
`

func (q *Queries) ListShiftCheckServices(ctx context.Context, shiftCheckID uuid.UUID) ([]ShiftCheckService, error) {
	rows, err := q.db.Query(ctx, listShiftCheckServices, shiftCheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftCheckService
	for rows.Next() {
		var i ShiftCheckService
		if err := rows.Scan(
			&i.ID,
			&i.ShiftCheckID,
			&i.ChecklistItemID,
			&i.ServiceTitle,
			&i.Status,
			&i.IsComputed,
			&i.Observation,
			&i.CorrelatedFromServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftChecks = `-- name: ListShiftChecks :many
SELECT id, checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services FROM shift_checks
WHERE ($1::uuid IS NULL OR work_shift_id = $1)
  AND ($2::timestamptz IS NULL OR check_date >= $2)
  AND ($3::timestamptz IS NULL OR check_date < $3)
ORDER BY check_date DESC LIMIT $5 OFFSET $4
`

type ListShiftChecksParams struct {
	WorkShiftID pgtype.UUID        `json:"work_shift_id"`
	FromDate    pgtype.Timestamptz `json:"from_date"`
	ToDate      pgtype.Timestamptz `json:"to_date"`
	PageOffset  int32              `json:"page_offset"`
	PageSize    int32              `json:"page_size"`
}

func (q *Queries) ListShiftChecks(ctx context.Context, arg ListShiftChecksParams) ([]ShiftCheck, error) {
	rows, err := q.db.Query(ctx, listShiftChecks,
		arg.WorkShiftID,
		arg.FromDate,
		arg.ToDate,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftCheck
	for rows.Next() {
		var i ShiftCheck
		if err := rows.Scan(
			&i.ID,
			&i.ChecklistTemplateID,
			&i.UserID,
			&i.WorkShiftID,
			&i.CheckType,
			&i.CheckDate,
			&i.HasRedServices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingMaintenanceWindows = `-- name: ListUpcomingMaintenanceWindows :many
SELECT id, service_id, asset_id, territorial_unit_id, title, notes, starts_at, ends_at, suppress_notifications, priority, created_by, active FROM maintenance_windows
WHERE active = true AND ends_at > $1 AND starts_at <= $2
ORDER BY starts_at ASC
`

type ListUpcomingMaintenanceWindowsParams struct {
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) ListUpcomingMaintenanceWindows(ctx context.Context, arg ListUpcomingMaintenanceWindowsParams) ([]MaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listUpcomingMaintenanceWindows, arg.EndsAt, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceWindow
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.AssetID,
			&i.TerritorialUnitID,
			&i.Title,
			&i.Notes,
			&i.StartsAt,
			&i.EndsAt,
			&i.SuppressNotifications,
			&i.Priority,
			&i.CreatedBy,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShiftClosureSent = `-- name: MarkShiftClosureSent :exec
UPDATE shift_closures SET sent_via = $2, sent_status = $3, sent_error = $4, sent_at = CASE WHEN $3 = 'success' THEN now() ELSE sent_at END WHERE id = $1
`

type MarkShiftClosureSentParams struct {
	ID         uuid.UUID   `json:"id"`
	SentVia    string      `json:"sent_via"`
	SentStatus string      `json:"sent_status"`
	SentError  pgtype.Text `json:"sent_error"`
}

func (q *Queries) MarkShiftClosureSent(ctx context.Context, arg MarkShiftClosureSentParams) error {
	_, err := q.db.Exec(ctx, markShiftClosureSent,
		arg.ID,
		arg.SentVia,
		arg.SentStatus,
		arg.SentError,
	)
	return err
}
