// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeShiftClosure = `-- name: AcknowledgeShiftClosure :one
UPDATE shift_closures SET acknowledged_by = $2, acknowledged_at = $3 WHERE id = $1 AND acknowledged_at IS NULL RETURNING id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at
`

type AcknowledgeShiftClosureParams struct {
	ID             uuid.UUID          `json:"id"`
	AcknowledgedBy pgtype.UUID        `json:"acknowledged_by"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
}

func (q *Queries) AcknowledgeShiftClosure(ctx context.Context, arg AcknowledgeShiftClosureParams) (ShiftClosure, error) {
	row := q.db.QueryRow(ctx, acknowledgeShiftClosure, arg.ID, arg.AcknowledgedBy, arg.AcknowledgedAt)
	var i ShiftClosure
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.ClosureCheckID,
		&i.TotalEntries,
		&i.TotalIncidents,
		&i.ServicesDown,
		&i.Observations,
		&i.PendingForNextShift,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.TicketsResolvedCount,
		&i.SlaBreachesCount,
		&i.SentVia,
		&i.IntegrationName,
		&i.SentStatus,
		&i.SentError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const assignShiftEndTemplate = `-- name: AssignShiftEndTemplate :exec
UPDATE work_shifts SET checklist_template_end_id = $2 WHERE id = $1
`

type AssignShiftEndTemplateParams struct {
	ID                     uuid.UUID   `json:"id"`
	ChecklistTemplateEndID pgtype.UUID `json:"checklist_template_end_id"`
}

func (q *Queries) AssignShiftEndTemplate(ctx context.Context, arg AssignShiftEndTemplateParams) error {
	_, err := q.db.Exec(ctx, assignShiftEndTemplate, arg.ID, arg.ChecklistTemplateEndID)
	return err
}

const assignShiftStartTemplate = `-- name: AssignShiftStartTemplate :exec
UPDATE work_shifts SET checklist_template_start_id = $2 WHERE id = $1
`

type AssignShiftStartTemplateParams struct {
	ID                       uuid.UUID   `json:"id"`
	ChecklistTemplateStartID pgtype.UUID `json:"checklist_template_start_id"`
}

func (q *Queries) AssignShiftStartTemplate(ctx context.Context, arg AssignShiftStartTemplateParams) error {
	_, err := q.db.Exec(ctx, assignShiftStartTemplate, arg.ID, arg.ChecklistTemplateStartID)
	return err
}

const clearTemplateFromShifts = `-- name: ClearTemplateFromShifts :exec
UPDATE work_shifts SET
  checklist_template_start_id = CASE WHEN checklist_template_start_id = $1 THEN NULL ELSE checklist_template_start_id END,
  checklist_template_end_id = CASE WHEN checklist_template_end_id = $1 THEN NULL ELSE checklist_template_end_id END
WHERE checklist_template_start_id = $1 OR checklist_template_end_id = $1
`

func (q *Queries) ClearTemplateFromShifts(ctx context.Context, checklistTemplateStartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTemplateFromShifts, checklistTemplateStartID)
	return err
}

const countEntriesInWindow = `-- name: CountEntriesInWindow :one
SELECT count(*) FROM entries WHERE created_at >= $1 AND created_at < $2
`

type CountEntriesInWindowParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) CountEntriesInWindow(ctx context.Context, arg CountEntriesInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntriesInWindow, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIncidentEntriesInWindow = `-- name: CountIncidentEntriesInWindow :one
SELECT count(*) FROM entries WHERE entry_type = 'incidente' AND created_at >= $1 AND created_at < $2
`

type CountIncidentEntriesInWindowParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) CountIncidentEntriesInWindow(ctx context.Context, arg CountIncidentEntriesInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidentEntriesInWindow, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResolvedTicketsInWindow = `-- name: CountResolvedTicketsInWindow :one
SELECT count(*) FROM tickets WHERE status IN ('resolved', 'closed') AND resolved_at >= $1 AND resolved_at < $2
`

type CountResolvedTicketsInWindowParams struct {
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	ResolvedAt_2 pgtype.Timestamptz `json:"resolved_at_2"`
}

func (q *Queries) CountResolvedTicketsInWindow(ctx context.Context, arg CountResolvedTicketsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResolvedTicketsInWindow, arg.ResolvedAt, arg.ResolvedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSLABreachesInWindow = `-- name: CountSLABreachesInWindow :one
SELECT count(*) FROM tickets WHERE sla_resolution_due_at IS NOT NULL AND resolved_at > sla_resolution_due_at + make_interval(secs => sla_paused_seconds) AND resolved_at >= $1 AND resolved_at < $2
`

type CountSLABreachesInWindowParams struct {
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	ResolvedAt_2 pgtype.Timestamptz `json:"resolved_at_2"`
}

func (q *Queries) CountSLABreachesInWindow(ctx context.Context, arg CountSLABreachesInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSLABreachesInWindow, arg.ResolvedAt, arg.ResolvedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShiftChecksForTemplate = `-- name: CountShiftChecksForTemplate :one
SELECT count(*) FROM shift_checks WHERE checklist_template_id = $1
`

func (q *Queries) CountShiftChecksForTemplate(ctx context.Context, checklistTemplateID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countShiftChecksForTemplate, checklistTemplateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChecklistEntry = `-- name: CreateChecklistEntry :one
INSERT INTO entries (user_id, entry_type, scope, content, tags, work_shift_id)
VALUES ($1, 'checklist', 'general', $2, $3, $4) RETURNING id, user_id, entry_type, scope, content, tags, service_id, asset_id, work_shift_id, glpi_ticket_id, glpi_linked_at, ticket_id, image_url, image_hash, image_size_bytes, created_at, updated_at, owner_complement_id, owner_complement_name
`

type CreateChecklistEntryParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Content     string      `json:"content"`
	Tags        []string    `json:"tags"`
	WorkShiftID pgtype.UUID `json:"work_shift_id"`
}

func (q *Queries) CreateChecklistEntry(ctx context.Context, arg CreateChecklistEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createChecklistEntry,
		arg.UserID,
		arg.Content,
		arg.Tags,
		arg.WorkShiftID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryType,
		&i.Scope,
		&i.Content,
		&i.Tags,
		&i.ServiceID,
		&i.AssetID,
		&i.WorkShiftID,
		&i.GlpiTicketID,
		&i.GlpiLinkedAt,
		&i.TicketID,
		&i.ImageUrl,
		&i.ImageHash,
		&i.ImageSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerComplementID,
		&i.OwnerComplementName,
	)
	return i, err
}

const createChecklistTemplate = `-- name: CreateChecklistTemplate :one
INSERT INTO checklist_templates (name, is_active, alert_nok_enabled, alert_nok_role_target)
VALUES ($1, $2, $3, $4) RETURNING id, name, is_active, alert_nok_enabled, alert_nok_role_target, created_at
`

type CreateChecklistTemplateParams struct {
	Name               string      `json:"name"`
	IsActive           bool        `json:"is_active"`
	AlertNokEnabled    bool        `json:"alert_nok_enabled"`
	AlertNokRoleTarget pgtype.Text `json:"alert_nok_role_target"`
}

func (q *Queries) CreateChecklistTemplate(ctx context.Context, arg CreateChecklistTemplateParams) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, createChecklistTemplate,
		arg.Name,
		arg.IsActive,
		arg.AlertNokEnabled,
		arg.AlertNokRoleTarget,
	)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.AlertNokEnabled,
		&i.AlertNokRoleTarget,
		&i.CreatedAt,
	)
	return i, err
}

const createShiftCheck = `-- name: CreateShiftCheck :one
INSERT INTO shift_checks (checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services
`

type CreateShiftCheckParams struct {
	ChecklistTemplateID uuid.UUID          `json:"checklist_template_id"`
	UserID              uuid.UUID          `json:"user_id"`
	WorkShiftID         uuid.UUID          `json:"work_shift_id"`
	CheckType           ChecklistCheckType `json:"check_type"`
	CheckDate           pgtype.Timestamptz `json:"check_date"`
	HasRedServices      bool               `json:"has_red_services"`
}

func (q *Queries) CreateShiftCheck(ctx context.Context, arg CreateShiftCheckParams) (ShiftCheck, error) {
	row := q.db.QueryRow(ctx, createShiftCheck,
		arg.ChecklistTemplateID,
		arg.UserID,
		arg.WorkShiftID,
		arg.CheckType,
		arg.CheckDate,
		arg.HasRedServices,
	)
	var i ShiftCheck
	err := row.Scan(
		&i.ID,
		&i.ChecklistTemplateID,
		&i.UserID,
		&i.WorkShiftID,
		&i.CheckType,
		&i.CheckDate,
		&i.HasRedServices,
	)
	return i, err
}

const createShiftCheckService = `-- name: CreateShiftCheckService :one
INSERT INTO shift_check_services (shift_check_id, checklist_item_id, service_title, status, is_computed, observation, correlated_from_service_id)
VALUES ($1, $5, $2, $3, $4, $6, $7) RETURNING id, shift_check_id, checklist_item_id, service_title, status, is_computed, observation, correlated_from_service_id
`

type CreateShiftCheckServiceParams struct {
	ShiftCheckID            uuid.UUID       `json:"shift_check_id"`
	ServiceTitle            string          `json:"service_title"`
	Status                  ChecklistStatus `json:"status"`
	IsComputed              bool            `json:"is_computed"`
	ChecklistItemID         pgtype.UUID     `json:"checklist_item_id"`
	Observation             pgtype.Text     `json:"observation"`
	CorrelatedFromServiceID pgtype.UUID     `json:"correlated_from_service_id"`
}

func (q *Queries) CreateShiftCheckService(ctx context.Context, arg CreateShiftCheckServiceParams) (ShiftCheckService, error) {
	row := q.db.QueryRow(ctx, createShiftCheckService,
		arg.ShiftCheckID,
		arg.ServiceTitle,
		arg.Status,
		arg.IsComputed,
		arg.ChecklistItemID,
		arg.Observation,
		arg.CorrelatedFromServiceID,
	)
	var i ShiftCheckService
	err := row.Scan(
		&i.ID,
		&i.ShiftCheckID,
		&i.ChecklistItemID,
		&i.ServiceTitle,
		&i.Status,
		&i.IsComputed,
		&i.Observation,
		&i.CorrelatedFromServiceID,
	)
	return i, err
}

const createShiftClosure = `-- name: CreateShiftClosure :one
INSERT INTO shift_closures (user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, tickets_resolved_count, sla_breaches_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $10, $11, $8, $9) RETURNING id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at
`

type CreateShiftClosureParams struct {
	UserID               uuid.UUID          `json:"user_id"`
	ShiftStartAt         pgtype.Timestamptz `json:"shift_start_at"`
	ShiftEndAt           pgtype.Timestamptz `json:"shift_end_at"`
	ClosureCheckID       uuid.UUID          `json:"closure_check_id"`
	TotalEntries         int32              `json:"total_entries"`
	TotalIncidents       int32              `json:"total_incidents"`
	ServicesDown         []string           `json:"services_down"`
	TicketsResolvedCount int32              `json:"tickets_resolved_count"`
	SlaBreachesCount     int32              `json:"sla_breaches_count"`
	Observations         pgtype.Text        `json:"observations"`
	PendingForNextShift  pgtype.Text        `json:"pending_for_next_shift"`
}

func (q *Queries) CreateShiftClosure(ctx context.Context, arg CreateShiftClosureParams) (ShiftClosure, error) {
	row := q.db.QueryRow(ctx, createShiftClosure,
		arg.UserID,
		arg.ShiftStartAt,
		arg.ShiftEndAt,
		arg.ClosureCheckID,
		arg.TotalEntries,
		arg.TotalIncidents,
		arg.ServicesDown,
		arg.TicketsResolvedCount,
		arg.SlaBreachesCount,
		arg.Observations,
		arg.PendingForNextShift,
	)
	var i ShiftClosure
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.ClosureCheckID,
		&i.TotalEntries,
		&i.TotalIncidents,
		&i.ServicesDown,
		&i.Observations,
		&i.PendingForNextShift,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.TicketsResolvedCount,
		&i.SlaBreachesCount,
		&i.SentVia,
		&i.IntegrationName,
		&i.SentStatus,
		&i.SentError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChecklistItemsExcept = `-- name: DeleteChecklistItemsExcept :exec
DELETE FROM checklist_items WHERE template_id = $1 AND NOT (id = ANY($2::uuid[]))
`

type DeleteChecklistItemsExceptParams struct {
	TemplateID uuid.UUID   `json:"template_id"`
	KeepIds    []uuid.UUID `json:"keep_ids"`
}

// Un solo DELETE para padres e hijos: la FK de parent_item_id se revisa al
// final de la sentencia. El historial conserva el nombre (service_title) y
// su checklist_item_id queda en NULL (ON DELETE SET NULL).
func (q *Queries) DeleteChecklistItemsExcept(ctx context.Context, arg DeleteChecklistItemsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteChecklistItemsExcept, arg.TemplateID, arg.KeepIds)
	return err
}

const deleteChecklistTemplate = `-- name: DeleteChecklistTemplate :exec
DELETE FROM checklist_templates WHERE id = $1
`

func (q *Queries) DeleteChecklistTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChecklistTemplate, id)
	return err
}

const getActiveChecklistTemplate = `-- name: GetActiveChecklistTemplate :one
SELECT id, name, is_active, alert_nok_enabled, alert_nok_role_target, created_at FROM checklist_templates WHERE id = $1 AND is_active = true
`

func (q *Queries) GetActiveChecklistTemplate(ctx context.Context, id uuid.UUID) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, getActiveChecklistTemplate, id)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.AlertNokEnabled,
		&i.AlertNokRoleTarget,
		&i.CreatedAt,
	)
	return i, err
}

const getChecklistCooldown = `-- name: GetChecklistCooldown :one
SELECT shift_check_cooldown_minutes FROM app_config WHERE id = true
`

func (q *Queries) GetChecklistCooldown(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getChecklistCooldown)
	var shift_check_cooldown_minutes int32
	err := row.Scan(&shift_check_cooldown_minutes)
	return shift_check_cooldown_minutes, err
}

const getChecklistTemplate = `-- name: GetChecklistTemplate :one
SELECT id, name, is_active, alert_nok_enabled, alert_nok_role_target, created_at FROM checklist_templates WHERE id = $1
`

func (q *Queries) GetChecklistTemplate(ctx context.Context, id uuid.UUID) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, getChecklistTemplate, id)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.AlertNokEnabled,
		&i.AlertNokRoleTarget,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestShiftCheck = `-- name: GetLatestShiftCheck :one
SELECT id, checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services FROM shift_checks WHERE work_shift_id = $1 ORDER BY check_date DESC LIMIT 1
`

func (q *Queries) GetLatestShiftCheck(ctx context.Context, workShiftID uuid.UUID) (ShiftCheck, error) {
	row := q.db.QueryRow(ctx, getLatestShiftCheck, workShiftID)
	var i ShiftCheck
	err := row.Scan(
		&i.ID,
		&i.ChecklistTemplateID,
		&i.UserID,
		&i.WorkShiftID,
		&i.CheckType,
		&i.CheckDate,
		&i.HasRedServices,
	)
	return i, err
}

const getLatestShiftClosure = `-- name: GetLatestShiftClosure :one
SELECT id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at FROM shift_closures ORDER BY shift_end_at DESC LIMIT 1
`

func (q *Queries) GetLatestShiftClosure(ctx context.Context) (ShiftClosure, error) {
	row := q.db.QueryRow(ctx, getLatestShiftClosure)
	var i ShiftClosure
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.ClosureCheckID,
		&i.TotalEntries,
		&i.TotalIncidents,
		&i.ServicesDown,
		&i.Observations,
		&i.PendingForNextShift,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.TicketsResolvedCount,
		&i.SlaBreachesCount,
		&i.SentVia,
		&i.IntegrationName,
		&i.SentStatus,
		&i.SentError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestStartCheckInWindow = `-- name: GetLatestStartCheckInWindow :one
SELECT sc.id, sc.checklist_template_id, sc.user_id, sc.work_shift_id, sc.check_type, sc.check_date, sc.has_red_services, t.name AS template_name FROM shift_checks sc
JOIN checklist_templates t ON t.id = sc.checklist_template_id
WHERE sc.work_shift_id = $1 AND sc.check_type = 'inicio' AND sc.check_date >= $2 AND sc.check_date <= $3
ORDER BY sc.check_date DESC LIMIT 1
`

type GetLatestStartCheckInWindowParams struct {
	WorkShiftID uuid.UUID          `json:"work_shift_id"`
	CheckDate   pgtype.Timestamptz `json:"check_date"`
	CheckDate_2 pgtype.Timestamptz `json:"check_date_2"`
}

type GetLatestStartCheckInWindowRow struct {
	ID                  uuid.UUID          `json:"id"`
	ChecklistTemplateID uuid.UUID          `json:"checklist_template_id"`
	UserID              uuid.UUID          `json:"user_id"`
	WorkShiftID         uuid.UUID          `json:"work_shift_id"`
	CheckType           ChecklistCheckType `json:"check_type"`
	CheckDate           pgtype.Timestamptz `json:"check_date"`
	HasRedServices      bool               `json:"has_red_services"`
	TemplateName        string             `json:"template_name"`
}

// Checklist de inicio más reciente del mismo turno dentro de la ventana
// (loadShiftReportData del legacy).
func (q *Queries) GetLatestStartCheckInWindow(ctx context.Context, arg GetLatestStartCheckInWindowParams) (GetLatestStartCheckInWindowRow, error) {
	row := q.db.QueryRow(ctx, getLatestStartCheckInWindow, arg.WorkShiftID, arg.CheckDate, arg.CheckDate_2)
	var i GetLatestStartCheckInWindowRow
	err := row.Scan(
		&i.ID,
		&i.ChecklistTemplateID,
		&i.UserID,
		&i.WorkShiftID,
		&i.CheckType,
		&i.CheckDate,
		&i.HasRedServices,
		&i.TemplateName,
	)
	return i, err
}

const getShiftCheck = `-- name: GetShiftCheck :one
SELECT id, checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services FROM shift_checks WHERE id = $1
`

func (q *Queries) GetShiftCheck(ctx context.Context, id uuid.UUID) (ShiftCheck, error) {
	row := q.db.QueryRow(ctx, getShiftCheck, id)
	var i ShiftCheck
	err := row.Scan(
		&i.ID,
		&i.ChecklistTemplateID,
		&i.UserID,
		&i.WorkShiftID,
		&i.CheckType,
		&i.CheckDate,
		&i.HasRedServices,
	)
	return i, err
}

const getShiftCheckForReport = `-- name: GetShiftCheckForReport :one

SELECT sc.id, sc.checklist_template_id, sc.user_id, sc.work_shift_id, sc.check_type, sc.check_date, sc.has_red_services, t.name AS template_name FROM shift_checks sc
JOIN checklist_templates t ON t.id = sc.checklist_template_id
WHERE sc.id = $1
`

type GetShiftCheckForReportRow struct {
	ID                  uuid.UUID          `json:"id"`
	ChecklistTemplateID uuid.UUID          `json:"checklist_template_id"`
	UserID              uuid.UUID          `json:"user_id"`
	WorkShiftID         uuid.UUID          `json:"work_shift_id"`
	CheckType           ChecklistCheckType `json:"check_type"`
	CheckDate           pgtype.Timestamptz `json:"check_date"`
	HasRedServices      bool               `json:"has_red_services"`
	TemplateName        string             `json:"template_name"`
}

// ===== Reporte de Turno por correo (formato legacy, utils/shift-report.js) =====
func (q *Queries) GetShiftCheckForReport(ctx context.Context, id uuid.UUID) (GetShiftCheckForReportRow, error) {
	row := q.db.QueryRow(ctx, getShiftCheckForReport, id)
	var i GetShiftCheckForReportRow
	err := row.Scan(
		&i.ID,
		&i.ChecklistTemplateID,
		&i.UserID,
		&i.WorkShiftID,
		&i.CheckType,
		&i.CheckDate,
		&i.HasRedServices,
		&i.TemplateName,
	)
	return i, err
}

const getShiftClosure = `-- name: GetShiftClosure :one
SELECT id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at FROM shift_closures WHERE id = $1
`

func (q *Queries) GetShiftClosure(ctx context.Context, id uuid.UUID) (ShiftClosure, error) {
	row := q.db.QueryRow(ctx, getShiftClosure, id)
	var i ShiftClosure
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.ClosureCheckID,
		&i.TotalEntries,
		&i.TotalIncidents,
		&i.ServicesDown,
		&i.Observations,
		&i.PendingForNextShift,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.TicketsResolvedCount,
		&i.SlaBreachesCount,
		&i.SentVia,
		&i.IntegrationName,
		&i.SentStatus,
		&i.SentError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getShiftClosureByCheck = `-- name: GetShiftClosureByCheck :one
SELECT id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at FROM shift_closures WHERE closure_check_id = $1 LIMIT 1
`

// Un check de cierre se cierra una sola vez: un segundo POST no duplica el cierre ni el reporte.
func (q *Queries) GetShiftClosureByCheck(ctx context.Context, closureCheckID uuid.UUID) (ShiftClosure, error) {
	row := q.db.QueryRow(ctx, getShiftClosureByCheck, closureCheckID)
	var i ShiftClosure
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShiftStartAt,
		&i.ShiftEndAt,
		&i.ClosureCheckID,
		&i.TotalEntries,
		&i.TotalIncidents,
		&i.ServicesDown,
		&i.Observations,
		&i.PendingForNextShift,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.TicketsResolvedCount,
		&i.SlaBreachesCount,
		&i.SentVia,
		&i.IntegrationName,
		&i.SentStatus,
		&i.SentError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkShiftByID = `-- name: GetWorkShiftByID :one
SELECT id, rotation_cycle_id, name, start_time, end_time, timezone, shift_type, checklist_template_start_id, checklist_template_end_id, email_recipients, active, email_include_checklist, email_include_entries, email_subject_template FROM work_shifts WHERE id = $1
`

func (q *Queries) GetWorkShiftByID(ctx context.Context, id uuid.UUID) (WorkShift, error) {
	row := q.db.QueryRow(ctx, getWorkShiftByID, id)
	var i WorkShift
	err := row.Scan(
		&i.ID,
		&i.RotationCycleID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.ShiftType,
		&i.ChecklistTemplateStartID,
		&i.ChecklistTemplateEndID,
		&i.EmailRecipients,
		&i.Active,
		&i.EmailIncludeChecklist,
		&i.EmailIncludeEntries,
		&i.EmailSubjectTemplate,
	)
	return i, err
}

const getWorkShiftForCheck = `-- name: GetWorkShiftForCheck :one
SELECT ws.id, ws.rotation_cycle_id, ws.name, ws.start_time, ws.end_time, ws.timezone, ws.shift_type, ws.checklist_template_start_id, ws.checklist_template_end_id, ws.email_recipients, ws.active, ws.email_include_checklist, ws.email_include_entries, ws.email_subject_template FROM work_shifts ws JOIN shift_checks sc ON sc.work_shift_id = ws.id WHERE sc.id = $1
`

// Turno al que pertenece un check: define la ventana real del cierre (no 8h fijas) y los destinatarios del reporte.
func (q *Queries) GetWorkShiftForCheck(ctx context.Context, id uuid.UUID) (WorkShift, error) {
	row := q.db.QueryRow(ctx, getWorkShiftForCheck, id)
	var i WorkShift
	err := row.Scan(
		&i.ID,
		&i.RotationCycleID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.ShiftType,
		&i.ChecklistTemplateStartID,
		&i.ChecklistTemplateEndID,
		&i.EmailRecipients,
		&i.Active,
		&i.EmailIncludeChecklist,
		&i.EmailIncludeEntries,
		&i.EmailSubjectTemplate,
	)
	return i, err
}

const insertChecklistItem = `-- name: InsertChecklistItem :exec
INSERT INTO checklist_items (id, template_id, parent_item_id, title, item_order)
VALUES ($1, $2, $5, $3, $4)
`

type InsertChecklistItemParams struct {
	ID           uuid.UUID   `json:"id"`
	TemplateID   uuid.UUID   `json:"template_id"`
	Title        string      `json:"title"`
	ItemOrder    int32       `json:"item_order"`
	ParentItemID pgtype.UUID `json:"parent_item_id"`
}

func (q *Queries) InsertChecklistItem(ctx context.Context, arg InsertChecklistItemParams) error {
	_, err := q.db.Exec(ctx, insertChecklistItem,
		arg.ID,
		arg.TemplateID,
		arg.Title,
		arg.ItemOrder,
		arg.ParentItemID,
	)
	return err
}

const lastTaggedEntryInWindow = `-- name: LastTaggedEntryInWindow :one
SELECT COALESCE(max(created_at), 'epoch'::timestamptz)::timestamptz AS at
FROM entries
WHERE user_id = $1 AND $2::text = ANY(tags)
  AND created_at >= $3 AND created_at < $4
`

type LastTaggedEntryInWindowParams struct {
	UserID uuid.UUID          `json:"user_id"`
	Tag    string             `json:"tag"`
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

// Última entrada del usuario con esa etiqueta en la ventana del turno
// (#iniciodeturno / #cierredeturno ya escritos).
func (q *Queries) LastTaggedEntryInWindow(ctx context.Context, arg LastTaggedEntryInWindowParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lastTaggedEntryInWindow,
		arg.UserID,
		arg.Tag,
		arg.FromAt,
		arg.ToAt,
	)
	var at pgtype.Timestamptz
	err := row.Scan(&at)
	return at, err
}

const linkCorrelatedShiftCheckService = `-- name: LinkCorrelatedShiftCheckService :one
UPDATE shift_check_services SET correlated_from_service_id = $2 WHERE id = $1 RETURNING id, shift_check_id, checklist_item_id, service_title, status, is_computed, observation, correlated_from_service_id
`

type LinkCorrelatedShiftCheckServiceParams struct {
	ID                      uuid.UUID   `json:"id"`
	CorrelatedFromServiceID pgtype.UUID `json:"correlated_from_service_id"`
}

func (q *Queries) LinkCorrelatedShiftCheckService(ctx context.Context, arg LinkCorrelatedShiftCheckServiceParams) (ShiftCheckService, error) {
	row := q.db.QueryRow(ctx, linkCorrelatedShiftCheckService, arg.ID, arg.CorrelatedFromServiceID)
	var i ShiftCheckService
	err := row.Scan(
		&i.ID,
		&i.ShiftCheckID,
		&i.ChecklistItemID,
		&i.ServiceTitle,
		&i.Status,
		&i.IsComputed,
		&i.Observation,
		&i.CorrelatedFromServiceID,
	)
	return i, err
}

const listActiveChecklistTemplates = `-- name: ListActiveChecklistTemplates :many
SELECT id, name, is_active, alert_nok_enabled, alert_nok_role_target, created_at FROM checklist_templates WHERE is_active = true ORDER BY name
`

func (q *Queries) ListActiveChecklistTemplates(ctx context.Context) ([]ChecklistTemplate, error) {
	rows, err := q.db.Query(ctx, listActiveChecklistTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistTemplate
	for rows.Next() {
		var i ChecklistTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.AlertNokEnabled,
			&i.AlertNokRoleTarget,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT id, template_id, parent_item_id, title, item_order FROM checklist_items WHERE template_id = $1 ORDER BY item_order, id
`

func (q *Queries) ListChecklistItems(ctx context.Context, templateID uuid.UUID) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItems, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistItem
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ParentItemID,
			&i.Title,
			&i.ItemOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistTemplates = `-- name: ListChecklistTemplates :many

SELECT id, name, is_active, alert_nok_enabled, alert_nok_role_target, created_at FROM checklist_templates ORDER BY is_active DESC, name
`

// ===== Administración de plantillas (pantalla aprobada "Administración: Checklist") =====
func (q *Queries) ListChecklistTemplates(ctx context.Context) ([]ChecklistTemplate, error) {
	rows, err := q.db.Query(ctx, listChecklistTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistTemplate
	for rows.Next() {
		var i ChecklistTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.AlertNokEnabled,
			&i.AlertNokRoleTarget,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesForShiftReport = `-- name: ListEntriesForShiftReport :many
SELECT e.entry_type::text AS entry_type, e.content, e.created_at, COALESCE(o.name, '') AS client_name
FROM entries e
LEFT JOIN services sv ON sv.id = e.service_id
LEFT JOIN organizations o ON o.id = sv.organization_id
WHERE e.entry_type <> 'checklist' AND e.created_at >= $1 AND e.created_at <= $2
ORDER BY e.created_at ASC
`

type ListEntriesForShiftReportParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type ListEntriesForShiftReportRow struct {
	EntryType  string             `json:"entry_type"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ClientName string             `json:"client_name"`
}

// Entradas del periodo en orden cronológico; las de checklist son de 2.0
// (el legacy no las tenía) y ya van en la sección Checklist.
func (q *Queries) ListEntriesForShiftReport(ctx context.Context, arg ListEntriesForShiftReportParams) ([]ListEntriesForShiftReportRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForShiftReport, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesForShiftReportRow
	for rows.Next() {
		var i ListEntriesForShiftReportRow
		if err := rows.Scan(
			&i.EntryType,
			&i.Content,
			&i.CreatedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandoverOnCall = `-- name: ListHandoverOnCall :many
SELECT DISTINCT ON (t.id) t.id AS team_id, t.name AS team_name,
  COALESCE(u.username, c.name, '')::text AS on_call_member
FROM teams t
JOIN rotation_cycles rc ON rc.team_id = t.id AND rc.active = true
JOIN rotation_slots rs ON rs.cycle_id = rc.id
  AND rs.week_start_date <= $1::date
  AND rs.week_end_date >= $1::date
  AND rs.is_paused = false
JOIN team_members tm ON tm.id = rs.team_member_id AND tm.active = true
LEFT JOIN users u ON u.id = tm.user_id
LEFT JOIN contacts c ON c.id = tm.contact_id
WHERE t.active = true
  AND ($2::uuid IS NULL OR t.id = $2)
ORDER BY t.id, tm.priority DESC, tm.id
`

type ListHandoverOnCallParams struct {
	Today  pgtype.Date `json:"today"`
	TeamID pgtype.UUID `json:"team_id"`
}

type ListHandoverOnCallRow struct {
	TeamID       uuid.UUID `json:"team_id"`
	TeamName     string    `json:"team_name"`
	OnCallMember string    `json:"on_call_member"`
}

func (q *Queries) ListHandoverOnCall(ctx context.Context, arg ListHandoverOnCallParams) ([]ListHandoverOnCallRow, error) {
	rows, err := q.db.Query(ctx, listHandoverOnCall, arg.Today, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandoverOnCallRow
	for rows.Next() {
		var i ListHandoverOnCallRow
		if err := rows.Scan(&i.TeamID, &i.TeamName, &i.OnCallMember); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingShiftClosures = `-- name: ListPendingShiftClosures :many
SELECT id, user_id, shift_start_at, shift_end_at, closure_check_id, total_entries, total_incidents, services_down, observations, pending_for_next_shift, acknowledged_by, acknowledged_at, tickets_resolved_count, sla_breaches_count, sent_via, integration_name, sent_status, sent_error, sent_at, created_at FROM shift_closures WHERE sent_status = 'pending' ORDER BY shift_end_at ASC
`

func (q *Queries) ListPendingShiftClosures(ctx context.Context) ([]ShiftClosure, error) {
	rows, err := q.db.Query(ctx, listPendingShiftClosures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftClosure
	for rows.Next() {
		var i ShiftClosure
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShiftStartAt,
			&i.ShiftEndAt,
			&i.ClosureCheckID,
			&i.TotalEntries,
			&i.TotalIncidents,
			&i.ServicesDown,
			&i.Observations,
			&i.PendingForNextShift,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.TicketsResolvedCount,
			&i.SlaBreachesCount,
			&i.SentVia,
			&i.IntegrationName,
			&i.SentStatus,
			&i.SentError,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentShiftReportDeliveries = `-- name: ListRecentShiftReportDeliveries :many
SELECT sc.id, sc.shift_end_at, sc.sent_status, sc.sent_error, sc.sent_at,
       u.username, ws.name AS shift_name, ws.email_recipients
FROM shift_closures sc
JOIN users u ON u.id = sc.user_id
LEFT JOIN shift_checks ck ON ck.id = sc.closure_check_id
LEFT JOIN work_shifts ws ON ws.id = ck.work_shift_id
ORDER BY sc.shift_end_at DESC
LIMIT 20
`

type ListRecentShiftReportDeliveriesRow struct {
	ID              uuid.UUID          `json:"id"`
	ShiftEndAt      pgtype.Timestamptz `json:"shift_end_at"`
	SentStatus      string             `json:"sent_status"`
	SentError       pgtype.Text        `json:"sent_error"`
	SentAt          pgtype.Timestamptz `json:"sent_at"`
	Username        string             `json:"username"`
	ShiftName       pgtype.Text        `json:"shift_name"`
	EmailRecipients []string           `json:"email_recipients"`
}

// Administración → Reportes: los últimos cierres y cómo salió su reporte,
// con el turno y a quién iba (sin esto un envío fallido no se veía en ninguna parte).
func (q *Queries) ListRecentShiftReportDeliveries(ctx context.Context) ([]ListRecentShiftReportDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listRecentShiftReportDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentShiftReportDeliveriesRow
	for rows.Next() {
		var i ListRecentShiftReportDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShiftEndAt,
			&i.SentStatus,
			&i.SentError,
			&i.SentAt,
			&i.Username,
			&i.ShiftName,
			&i.EmailRecipients,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftCheckServices = `-- name: ListShiftCheckServices :many
SELECT id, shift_check_id, checklist_item_id, service_title, status, is_computed, observation, correlated_from_service_id FROM shift_check_services WHERE shift_check_id = $1 ORDER BY id
`

func (q *Queries) ListShiftCheckServices(ctx context.Context, shiftCheckID uuid.UUID) ([]ShiftCheckService, error) {
	rows, err := q.db.Query(ctx, listShiftCheckServices, shiftCheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftCheckService
	for rows.Next() {
		var i ShiftCheckService
		if err := rows.Scan(
			&i.ID,
			&i.ShiftCheckID,
			&i.ChecklistItemID,
			&i.ServiceTitle,
			&i.Status,
			&i.IsComputed,
			&i.Observation,
			&i.CorrelatedFromServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftCheckServicesForReport = `-- name: ListShiftCheckServicesForReport :many
SELECT s.checklist_item_id, s.service_title, s.status::text AS status, COALESCE(s.observation, '') AS observation, i.parent_item_id
FROM shift_check_services s
LEFT JOIN checklist_items i ON i.id = s.checklist_item_id
WHERE s.shift_check_id = $1
ORDER BY i.item_order NULLS LAST, s.id
`

type ListShiftCheckServicesForReportRow struct {
	ChecklistItemID pgtype.UUID `json:"checklist_item_id"`
	ServiceTitle    string      `json:"service_title"`
	Status          string      `json:"status"`
	Observation     string      `json:"observation"`
	ParentItemID    pgtype.UUID `json:"parent_item_id"`
}

func (q *Queries) ListShiftCheckServicesForReport(ctx context.Context, shiftCheckID uuid.UUID) ([]ListShiftCheckServicesForReportRow, error) {
	rows, err := q.db.Query(ctx, listShiftCheckServicesForReport, shiftCheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShiftCheckServicesForReportRow
	for rows.Next() {
		var i ListShiftCheckServicesForReportRow
		if err := rows.Scan(
			&i.ChecklistItemID,
			&i.ServiceTitle,
			&i.Status,
			&i.Observation,
			&i.ParentItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftChecks = `-- name: ListShiftChecks :many
SELECT id, checklist_template_id, user_id, work_shift_id, check_type, check_date, has_red_services FROM shift_checks
WHERE ($1::uuid IS NULL OR work_shift_id = $1)
  AND ($2::timestamptz IS NULL OR check_date >= $2)
  AND ($3::timestamptz IS NULL OR check_date < $3)
ORDER BY check_date DESC LIMIT $5 OFFSET $4
`

type ListShiftChecksParams struct {
	WorkShiftID pgtype.UUID        `json:"work_shift_id"`
	FromDate    pgtype.Timestamptz `json:"from_date"`
	ToDate      pgtype.Timestamptz `json:"to_date"`
	PageOffset  int32              `json:"page_offset"`
	PageSize    int32              `json:"page_size"`
}

func (q *Queries) ListShiftChecks(ctx context.Context, arg ListShiftChecksParams) ([]ShiftCheck, error) {
	rows, err := q.db.Query(ctx, listShiftChecks,
		arg.WorkShiftID,
		arg.FromDate,
		arg.ToDate,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftCheck
	for rows.Next() {
		var i ShiftCheck
		if err := rows.Scan(
			&i.ID,
			&i.ChecklistTemplateID,
			&i.UserID,
			&i.WorkShiftID,
			&i.CheckType,
			&i.CheckDate,
			&i.HasRedServices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingMaintenanceWindows = `-- name: ListUpcomingMaintenanceWindows :many
SELECT id, service_id, asset_id, territorial_unit_id, title, notes, starts_at, ends_at, suppress_notifications, priority, created_by, active FROM maintenance_windows
WHERE active = true AND ends_at > $1 AND starts_at <= $2
ORDER BY starts_at ASC
`

type ListUpcomingMaintenanceWindowsParams struct {
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) ListUpcomingMaintenanceWindows(ctx context.Context, arg ListUpcomingMaintenanceWindowsParams) ([]MaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listUpcomingMaintenanceWindows, arg.EndsAt, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceWindow
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.AssetID,
			&i.TerritorialUnitID,
			&i.Title,
			&i.Notes,
			&i.StartsAt,
			&i.EndsAt,
			&i.SuppressNotifications,
			&i.Priority,
			&i.CreatedBy,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShiftClosureSent = `-- name: MarkShiftClosureSent :exec
UPDATE shift_closures SET sent_via = $2, sent_status = $3, sent_error = $4, sent_at = CASE WHEN $3 = 'success' THEN now() ELSE sent_at END WHERE id = $1
`

type MarkShiftClosureSentParams struct {
	ID         uuid.UUID   `json:"id"`
	SentVia    string      `json:"sent_via"`
	SentStatus string      `json:"sent_status"`
	SentError  pgtype.Text `json:"sent_error"`
}

func (q *Queries) MarkShiftClosureSent(ctx context.Context, arg MarkShiftClosureSentParams) error {
	_, err := q.db.Exec(ctx, markShiftClosureSent,
		arg.ID,
		arg.SentVia,
		arg.SentStatus,
		arg.SentError,
	)
	return err
}

const setChecklistCooldown = `-- name: SetChecklistCooldown :one
UPDATE app_config SET shift_check_cooldown_minutes = $1, updated_at = now() WHERE id = true
RETURNING shift_check_cooldown_minutes
`

func (q *Queries) SetChecklistCooldown(ctx context.Context, shiftCheckCooldownMinutes int32) (int32, error) {
	row := q.db.QueryRow(ctx, setChecklistCooldown, shiftCheckCooldownMinutes)
	var shift_check_cooldown_minutes int32
	err := row.Scan(&shift_check_cooldown_minutes)
	return shift_check_cooldown_minutes, err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :exec
UPDATE checklist_items SET parent_item_id = $5, title = $3, item_order = $4
WHERE id = $1 AND template_id = $2
`

type UpdateChecklistItemParams struct {
	ID           uuid.UUID   `json:"id"`
	TemplateID   uuid.UUID   `json:"template_id"`
	Title        string      `json:"title"`
	ItemOrder    int32       `json:"item_order"`
	ParentItemID pgtype.UUID `json:"parent_item_id"`
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) error {
	_, err := q.db.Exec(ctx, updateChecklistItem,
		arg.ID,
		arg.TemplateID,
		arg.Title,
		arg.ItemOrder,
		arg.ParentItemID,
	)
	return err
}

const updateChecklistTemplate = `-- name: UpdateChecklistTemplate :one
UPDATE checklist_templates SET name = $2, is_active = $3, alert_nok_enabled = $4, alert_nok_role_target = $5
WHERE id = $1 RETURNING id, name, is_active, alert_nok_enabled, alert_nok_role_target, created_at
`

type UpdateChecklistTemplateParams struct {
	ID                 uuid.UUID   `json:"id"`
	Name               string      `json:"name"`
	IsActive           bool        `json:"is_active"`
	AlertNokEnabled    bool        `json:"alert_nok_enabled"`
	AlertNokRoleTarget pgtype.Text `json:"alert_nok_role_target"`
}

func (q *Queries) UpdateChecklistTemplate(ctx context.Context, arg UpdateChecklistTemplateParams) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, updateChecklistTemplate,
		arg.ID,
		arg.Name,
		arg.IsActive,
		arg.AlertNokEnabled,
		arg.AlertNokRoleTarget,
	)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.AlertNokEnabled,
		&i.AlertNokRoleTarget,
		&i.CreatedAt,
	)
	return i, err
}
