// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: complements.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimComplementTicket = `-- name: ClaimComplementTicket :execrows
INSERT INTO token_denylist (jti, user_id, expires_at) VALUES ($1, $2, $3) ON CONFLICT (jti) DO NOTHING
`

type ClaimComplementTicketParams struct {
	Jti       uuid.UUID          `json:"jti"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Un enlace de un solo uso: 0 filas = ya se usó.
func (q *Queries) ClaimComplementTicket(ctx context.Context, arg ClaimComplementTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimComplementTicket, arg.Jti, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countComplementEntries = `-- name: CountComplementEntries :one
SELECT count(*)::int FROM entries WHERE owner_complement_id = $1
`

func (q *Queries) CountComplementEntries(ctx context.Context, ownerComplementID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countComplementEntries, ownerComplementID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countComplementFiles = `-- name: CountComplementFiles :one
SELECT count(*)::int FROM complement_files WHERE complement_id = $1
`

func (q *Queries) CountComplementFiles(ctx context.Context, complementID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countComplementFiles, complementID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createComplement = `-- name: CreateComplement :one
INSERT INTO complements (
  slug, name, description, icon, source_type, status, entry_path, base_url, internal_base_url, health_path,
  scopes, allowed_collections, connect_hosts, visible_roles, visible_permission_group_ids, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, slug, name, description, icon, source_type, status, entry_path, base_url, internal_base_url, health_path, api_version, scopes, allowed_collections, connect_hosts, visible_roles, visible_permission_group_ids, token_hash, token_issued_at, artifact_sha256, artifact_bytes, artifact_files, published_at, created_by, created_at, updated_at
`

type CreateComplementParams struct {
	Slug                      string           `json:"slug"`
	Name                      string           `json:"name"`
	Description               pgtype.Text      `json:"description"`
	Icon                      string           `json:"icon"`
	SourceType                ComplementSource `json:"source_type"`
	Status                    ComplementStatus `json:"status"`
	EntryPath                 string           `json:"entry_path"`
	BaseUrl                   pgtype.Text      `json:"base_url"`
	InternalBaseUrl           pgtype.Text      `json:"internal_base_url"`
	HealthPath                pgtype.Text      `json:"health_path"`
	Scopes                    []string         `json:"scopes"`
	AllowedCollections        []string         `json:"allowed_collections"`
	ConnectHosts              []string         `json:"connect_hosts"`
	VisibleRoles              []string         `json:"visible_roles"`
	VisiblePermissionGroupIds []uuid.UUID      `json:"visible_permission_group_ids"`
	CreatedBy                 pgtype.UUID      `json:"created_by"`
}

func (q *Queries) CreateComplement(ctx context.Context, arg CreateComplementParams) (Complement, error) {
	row := q.db.QueryRow(ctx, createComplement,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.SourceType,
		arg.Status,
		arg.EntryPath,
		arg.BaseUrl,
		arg.InternalBaseUrl,
		arg.HealthPath,
		arg.Scopes,
		arg.AllowedCollections,
		arg.ConnectHosts,
		arg.VisibleRoles,
		arg.VisiblePermissionGroupIds,
		arg.CreatedBy,
	)
	var i Complement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SourceType,
		&i.Status,
		&i.EntryPath,
		&i.BaseUrl,
		&i.InternalBaseUrl,
		&i.HealthPath,
		&i.ApiVersion,
		&i.Scopes,
		&i.AllowedCollections,
		&i.ConnectHosts,
		&i.VisibleRoles,
		&i.VisiblePermissionGroupIds,
		&i.TokenHash,
		&i.TokenIssuedAt,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.ArtifactFiles,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createComplementEntry = `-- name: CreateComplementEntry :one
INSERT INTO entries (user_id, entry_type, scope, content, tags, owner_complement_id, owner_complement_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, entry_type, scope, content, tags, service_id, asset_id, work_shift_id, glpi_ticket_id, glpi_linked_at, ticket_id, image_url, image_hash, image_size_bytes, created_at, updated_at, owner_complement_id, owner_complement_name
`

type CreateComplementEntryParams struct {
	UserID              uuid.UUID   `json:"user_id"`
	EntryType           EntryType   `json:"entry_type"`
	Scope               EntryScope  `json:"scope"`
	Content             string      `json:"content"`
	Tags                []string    `json:"tags"`
	OwnerComplementID   pgtype.UUID `json:"owner_complement_id"`
	OwnerComplementName pgtype.Text `json:"owner_complement_name"`
}

// Entrada creada por un complemento (Runtime API o CREATE_ENTRY del iframe).
func (q *Queries) CreateComplementEntry(ctx context.Context, arg CreateComplementEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createComplementEntry,
		arg.UserID,
		arg.EntryType,
		arg.Scope,
		arg.Content,
		arg.Tags,
		arg.OwnerComplementID,
		arg.OwnerComplementName,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryType,
		&i.Scope,
		&i.Content,
		&i.Tags,
		&i.ServiceID,
		&i.AssetID,
		&i.WorkShiftID,
		&i.GlpiTicketID,
		&i.GlpiLinkedAt,
		&i.TicketID,
		&i.ImageUrl,
		&i.ImageHash,
		&i.ImageSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerComplementID,
		&i.OwnerComplementName,
	)
	return i, err
}

const createComplementUpload = `-- name: CreateComplementUpload :one
INSERT INTO complement_uploads (filename, analysis, content, uploaded_by) VALUES ($1, $2, $3, $4)
RETURNING id, filename, analysis, created_at, expires_at
`

type CreateComplementUploadParams struct {
	Filename   string      `json:"filename"`
	Analysis   []byte      `json:"analysis"`
	Content    []byte      `json:"content"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

type CreateComplementUploadRow struct {
	ID        uuid.UUID          `json:"id"`
	Filename  string             `json:"filename"`
	Analysis  []byte             `json:"analysis"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateComplementUpload(ctx context.Context, arg CreateComplementUploadParams) (CreateComplementUploadRow, error) {
	row := q.db.QueryRow(ctx, createComplementUpload,
		arg.Filename,
		arg.Analysis,
		arg.Content,
		arg.UploadedBy,
	)
	var i CreateComplementUploadRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Analysis,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteComplement = `-- name: DeleteComplement :execrows
DELETE FROM complements WHERE id = $1
`

// Archivos y storage caen por CASCADE; las entradas quedan (FK en NULL) con
// su owner_complement_name.
func (q *Queries) DeleteComplement(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComplement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteComplementFiles = `-- name: DeleteComplementFiles :exec
DELETE FROM complement_files WHERE complement_id = $1
`

func (q *Queries) DeleteComplementFiles(ctx context.Context, complementID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComplementFiles, complementID)
	return err
}

const deleteComplementUpload = `-- name: DeleteComplementUpload :exec
DELETE FROM complement_uploads WHERE id = $1
`

func (q *Queries) DeleteComplementUpload(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComplementUpload, id)
	return err
}

const deleteExpiredComplementUploads = `-- name: DeleteExpiredComplementUploads :execrows
DELETE FROM complement_uploads WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredComplementUploads(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredComplementUploads)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComplementBySlug = `-- name: GetComplementBySlug :one
SELECT id, slug, name, description, icon, source_type, status, entry_path, base_url, internal_base_url, health_path, api_version, scopes, allowed_collections, connect_hosts, visible_roles, visible_permission_group_ids, token_hash, token_issued_at, artifact_sha256, artifact_bytes, artifact_files, published_at, created_by, created_at, updated_at FROM complements WHERE slug = $1
`

func (q *Queries) GetComplementBySlug(ctx context.Context, slug string) (Complement, error) {
	row := q.db.QueryRow(ctx, getComplementBySlug, slug)
	var i Complement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SourceType,
		&i.Status,
		&i.EntryPath,
		&i.BaseUrl,
		&i.InternalBaseUrl,
		&i.HealthPath,
		&i.ApiVersion,
		&i.Scopes,
		&i.AllowedCollections,
		&i.ConnectHosts,
		&i.VisibleRoles,
		&i.VisiblePermissionGroupIds,
		&i.TokenHash,
		&i.TokenIssuedAt,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.ArtifactFiles,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComplementFile = `-- name: GetComplementFile :one
SELECT f.content_type, f.sha256, f.content
FROM complement_files f JOIN complements c ON c.id = f.complement_id
WHERE c.slug = $1 AND f.path = $2
`

type GetComplementFileParams struct {
	Slug string `json:"slug"`
	Path string `json:"path"`
}

type GetComplementFileRow struct {
	ContentType string `json:"content_type"`
	Sha256      string `json:"sha256"`
	Content     []byte `json:"content"`
}

func (q *Queries) GetComplementFile(ctx context.Context, arg GetComplementFileParams) (GetComplementFileRow, error) {
	row := q.db.QueryRow(ctx, getComplementFile, arg.Slug, arg.Path)
	var i GetComplementFileRow
	err := row.Scan(&i.ContentType, &i.Sha256, &i.Content)
	return i, err
}

const getComplementStorage = `-- name: GetComplementStorage :one
SELECT complement_id, key, value, updated_by_user_id, updated_via, updated_at FROM complement_storage WHERE complement_id = $1 AND key = $2
`

type GetComplementStorageParams struct {
	ComplementID uuid.UUID `json:"complement_id"`
	Key          string    `json:"key"`
}

func (q *Queries) GetComplementStorage(ctx context.Context, arg GetComplementStorageParams) (ComplementStorage, error) {
	row := q.db.QueryRow(ctx, getComplementStorage, arg.ComplementID, arg.Key)
	var i ComplementStorage
	err := row.Scan(
		&i.ComplementID,
		&i.Key,
		&i.Value,
		&i.UpdatedByUserID,
		&i.UpdatedVia,
		&i.UpdatedAt,
	)
	return i, err
}

const getComplementUpload = `-- name: GetComplementUpload :one
SELECT id, filename, analysis, content, uploaded_by, created_at, expires_at FROM complement_uploads WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetComplementUpload(ctx context.Context, id uuid.UUID) (ComplementUpload, error) {
	row := q.db.QueryRow(ctx, getComplementUpload, id)
	var i ComplementUpload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Analysis,
		&i.Content,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertComplementFile = `-- name: InsertComplementFile :exec
INSERT INTO complement_files (complement_id, path, content_type, sha256, content) VALUES ($1, $2, $3, $4, $5)
`

type InsertComplementFileParams struct {
	ComplementID uuid.UUID `json:"complement_id"`
	Path         string    `json:"path"`
	ContentType  string    `json:"content_type"`
	Sha256       string    `json:"sha256"`
	Content      []byte    `json:"content"`
}

func (q *Queries) InsertComplementFile(ctx context.Context, arg InsertComplementFileParams) error {
	_, err := q.db.Exec(ctx, insertComplementFile,
		arg.ComplementID,
		arg.Path,
		arg.ContentType,
		arg.Sha256,
		arg.Content,
	)
	return err
}

const listComplementStorage = `-- name: ListComplementStorage :many
SELECT complement_id, key, value, updated_by_user_id, updated_via, updated_at FROM complement_storage
WHERE complement_id = $1 AND ($2::text IS NULL OR key = $2)
ORDER BY updated_at DESC
LIMIT 200
`

type ListComplementStorageParams struct {
	ComplementID uuid.UUID   `json:"complement_id"`
	Key          pgtype.Text `json:"key"`
}

func (q *Queries) ListComplementStorage(ctx context.Context, arg ListComplementStorageParams) ([]ComplementStorage, error) {
	rows, err := q.db.Query(ctx, listComplementStorage, arg.ComplementID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplementStorage
	for rows.Next() {
		var i ComplementStorage
		if err := rows.Scan(
			&i.ComplementID,
			&i.Key,
			&i.Value,
			&i.UpdatedByUserID,
			&i.UpdatedVia,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplements = `-- name: ListComplements :many

SELECT id, slug, name, description, icon, source_type, status, entry_path, base_url, internal_base_url, health_path, api_version, scopes, allowed_collections, connect_hosts, visible_roles, visible_permission_group_ids, token_hash, token_issued_at, artifact_sha256, artifact_bytes, artifact_files, published_at, created_by, created_at, updated_at FROM complements ORDER BY name
`

// Complementos (spec/11-complementos.md, Fase 13b).
func (q *Queries) ListComplements(ctx context.Context) ([]Complement, error) {
	rows, err := q.db.Query(ctx, listComplements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Complement
	for rows.Next() {
		var i Complement
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SourceType,
			&i.Status,
			&i.EntryPath,
			&i.BaseUrl,
			&i.InternalBaseUrl,
			&i.HealthPath,
			&i.ApiVersion,
			&i.Scopes,
			&i.AllowedCollections,
			&i.ConnectHosts,
			&i.VisibleRoles,
			&i.VisiblePermissionGroupIds,
			&i.TokenHash,
			&i.TokenIssuedAt,
			&i.ArtifactSha256,
			&i.ArtifactBytes,
			&i.ArtifactFiles,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditForComplement = `-- name: ListRecentAuditForComplement :many
SELECT id, timestamp, event, level, actor_username, success, reason
FROM audit_log
ORDER BY timestamp DESC
LIMIT $1
`

type ListRecentAuditForComplementRow struct {
	ID            uuid.UUID          `json:"id"`
	Timestamp     pgtype.Timestamptz `json:"timestamp"`
	Event         string             `json:"event"`
	Level         string             `json:"level"`
	ActorUsername pgtype.Text        `json:"actor_username"`
	Success       bool               `json:"success"`
	Reason        pgtype.Text        `json:"reason"`
}

func (q *Queries) ListRecentAuditForComplement(ctx context.Context, limit int32) ([]ListRecentAuditForComplementRow, error) {
	rows, err := q.db.Query(ctx, listRecentAuditForComplement, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentAuditForComplementRow
	for rows.Next() {
		var i ListRecentAuditForComplementRow
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Event,
			&i.Level,
			&i.ActorUsername,
			&i.Success,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEntriesForComplement = `-- name: ListRecentEntriesForComplement :many
SELECT e.id, e.entry_type, e.scope, e.content, e.tags, e.created_at, u.username AS author_username, e.owner_complement_name
FROM entries e JOIN users u ON u.id = e.user_id
ORDER BY e.created_at DESC
LIMIT $1
`

type ListRecentEntriesForComplementRow struct {
	ID                  uuid.UUID          `json:"id"`
	EntryType           EntryType          `json:"entry_type"`
	Scope               EntryScope         `json:"scope"`
	Content             string             `json:"content"`
	Tags                []string           `json:"tags"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	AuthorUsername      string             `json:"author_username"`
	OwnerComplementName pgtype.Text        `json:"owner_complement_name"`
}

// Runtime API query-general?collection=entries: lo más reciente, sin adjuntos.
func (q *Queries) ListRecentEntriesForComplement(ctx context.Context, limit int32) ([]ListRecentEntriesForComplementRow, error) {
	rows, err := q.db.Query(ctx, listRecentEntriesForComplement, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentEntriesForComplementRow
	for rows.Next() {
		var i ListRecentEntriesForComplementRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryType,
			&i.Scope,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.AuthorUsername,
			&i.OwnerComplementName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleComplementCandidates = `-- name: ListVisibleComplementCandidates :many
SELECT id, slug, name, description, icon, source_type, status, entry_path, base_url, internal_base_url, health_path, api_version, scopes, allowed_collections, connect_hosts, visible_roles, visible_permission_group_ids, token_hash, token_issued_at, artifact_sha256, artifact_bytes, artifact_files, published_at, created_by, created_at, updated_at FROM complements WHERE status <> 'disabled' ORDER BY name
`

// Activos o en mantenimiento; la visibilidad por rol y grupo se filtra en Go.
func (q *Queries) ListVisibleComplementCandidates(ctx context.Context) ([]Complement, error) {
	rows, err := q.db.Query(ctx, listVisibleComplementCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Complement
	for rows.Next() {
		var i Complement
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SourceType,
			&i.Status,
			&i.EntryPath,
			&i.BaseUrl,
			&i.InternalBaseUrl,
			&i.HealthPath,
			&i.ApiVersion,
			&i.Scopes,
			&i.AllowedCollections,
			&i.ConnectHosts,
			&i.VisibleRoles,
			&i.VisiblePermissionGroupIds,
			&i.TokenHash,
			&i.TokenIssuedAt,
			&i.ArtifactSha256,
			&i.ArtifactBytes,
			&i.ArtifactFiles,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setComplementArtifact = `-- name: SetComplementArtifact :exec
UPDATE complements SET artifact_sha256 = $2, artifact_bytes = $3, artifact_files = $4, published_at = now(), updated_at = now()
WHERE id = $1
`

type SetComplementArtifactParams struct {
	ID             uuid.UUID   `json:"id"`
	ArtifactSha256 pgtype.Text `json:"artifact_sha256"`
	ArtifactBytes  pgtype.Int8 `json:"artifact_bytes"`
	ArtifactFiles  pgtype.Int4 `json:"artifact_files"`
}

func (q *Queries) SetComplementArtifact(ctx context.Context, arg SetComplementArtifactParams) error {
	_, err := q.db.Exec(ctx, setComplementArtifact,
		arg.ID,
		arg.ArtifactSha256,
		arg.ArtifactBytes,
		arg.ArtifactFiles,
	)
	return err
}

const setComplementToken = `-- name: SetComplementToken :exec
UPDATE complements SET token_hash = $2, token_issued_at = now(), updated_at = now() WHERE slug = $1
`

type SetComplementTokenParams struct {
	Slug      string      `json:"slug"`
	TokenHash pgtype.Text `json:"token_hash"`
}

func (q *Queries) SetComplementToken(ctx context.Context, arg SetComplementTokenParams) error {
	_, err := q.db.Exec(ctx, setComplementToken, arg.Slug, arg.TokenHash)
	return err
}

const updateComplement = `-- name: UpdateComplement :one
UPDATE complements SET
  name = $2, description = $3, icon = $4, status = $5, entry_path = $6, base_url = $7, internal_base_url = $8,
  health_path = $9, scopes = $10, allowed_collections = $11, connect_hosts = $12, visible_roles = $13,
  visible_permission_group_ids = $14, updated_at = now()
WHERE slug = $1
RETURNING id, slug, name, description, icon, source_type, status, entry_path, base_url, internal_base_url, health_path, api_version, scopes, allowed_collections, connect_hosts, visible_roles, visible_permission_group_ids, token_hash, token_issued_at, artifact_sha256, artifact_bytes, artifact_files, published_at, created_by, created_at, updated_at
`

type UpdateComplementParams struct {
	Slug                      string           `json:"slug"`
	Name                      string           `json:"name"`
	Description               pgtype.Text      `json:"description"`
	Icon                      string           `json:"icon"`
	Status                    ComplementStatus `json:"status"`
	EntryPath                 string           `json:"entry_path"`
	BaseUrl                   pgtype.Text      `json:"base_url"`
	InternalBaseUrl           pgtype.Text      `json:"internal_base_url"`
	HealthPath                pgtype.Text      `json:"health_path"`
	Scopes                    []string         `json:"scopes"`
	AllowedCollections        []string         `json:"allowed_collections"`
	ConnectHosts              []string         `json:"connect_hosts"`
	VisibleRoles              []string         `json:"visible_roles"`
	VisiblePermissionGroupIds []uuid.UUID      `json:"visible_permission_group_ids"`
}

// Ficha del complemento: todo lo editable de una vez (el handler mezcla lo
// que llega con lo guardado).
func (q *Queries) UpdateComplement(ctx context.Context, arg UpdateComplementParams) (Complement, error) {
	row := q.db.QueryRow(ctx, updateComplement,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Status,
		arg.EntryPath,
		arg.BaseUrl,
		arg.InternalBaseUrl,
		arg.HealthPath,
		arg.Scopes,
		arg.AllowedCollections,
		arg.ConnectHosts,
		arg.VisibleRoles,
		arg.VisiblePermissionGroupIds,
	)
	var i Complement
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SourceType,
		&i.Status,
		&i.EntryPath,
		&i.BaseUrl,
		&i.InternalBaseUrl,
		&i.HealthPath,
		&i.ApiVersion,
		&i.Scopes,
		&i.AllowedCollections,
		&i.ConnectHosts,
		&i.VisibleRoles,
		&i.VisiblePermissionGroupIds,
		&i.TokenHash,
		&i.TokenIssuedAt,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.ArtifactFiles,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertComplementStorage = `-- name: UpsertComplementStorage :one
INSERT INTO complement_storage (complement_id, key, value, updated_by_user_id, updated_via)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (complement_id, key) DO UPDATE SET
  value = EXCLUDED.value, updated_by_user_id = EXCLUDED.updated_by_user_id,
  updated_via = EXCLUDED.updated_via, updated_at = now()
RETURNING complement_id, key, value, updated_by_user_id, updated_via, updated_at
`

type UpsertComplementStorageParams struct {
	ComplementID    uuid.UUID   `json:"complement_id"`
	Key             string      `json:"key"`
	Value           []byte      `json:"value"`
	UpdatedByUserID pgtype.UUID `json:"updated_by_user_id"`
	UpdatedVia      string      `json:"updated_via"`
}

func (q *Queries) UpsertComplementStorage(ctx context.Context, arg UpsertComplementStorageParams) (ComplementStorage, error) {
	row := q.db.QueryRow(ctx, upsertComplementStorage,
		arg.ComplementID,
		arg.Key,
		arg.Value,
		arg.UpdatedByUserID,
		arg.UpdatedVia,
	)
	var i ComplementStorage
	err := row.Scan(
		&i.ComplementID,
		&i.Key,
		&i.Value,
		&i.UpdatedByUserID,
		&i.UpdatedVia,
		&i.UpdatedAt,
	)
	return i, err
}
