// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearPreferredContactChannel = `-- name: ClearPreferredContactChannel :exec
UPDATE contact_channels SET preferred = false WHERE contact_id = $1 AND preferred
`

// A lo sumo un canal preferido por dueño (índice único parcial del esquema):
// marcar uno nuevo desmarca el anterior.
func (q *Queries) ClearPreferredContactChannel(ctx context.Context, contactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPreferredContactChannel, contactID)
	return err
}

const clearPreferredUserChannel = `-- name: ClearPreferredUserChannel :exec
UPDATE contact_channels SET preferred = false WHERE user_id = $1 AND preferred
`

func (q *Queries) ClearPreferredUserChannel(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPreferredUserChannel, userID)
	return err
}

const countDirectory = `-- name: CountDirectory :one
SELECT count(*)
FROM contacts c JOIN organizations o ON o.id = c.organization_id
WHERE c.active = $1::boolean
  AND ($2::uuid IS NULL OR c.organization_id = $2)
  AND ($3::contact_scope IS NULL OR c.scope = $3)
  AND ($4::text IS NULL OR unaccent(c.specialty) ILIKE unaccent('%' || $4 || '%'))
  AND ($5::boolean IS NULL OR c.is_favorite = $5)
  AND ($6::text IS NULL
       OR unaccent(c.name) ILIKE unaccent('%' || $6 || '%')
       OR unaccent(c.position) ILIKE unaccent('%' || $6 || '%')
       OR unaccent(c.specialty) ILIKE unaccent('%' || $6 || '%')
       OR unaccent(o.name) ILIKE unaccent('%' || $6 || '%')
       OR c.email_hash = $7
       OR c.phone_hash = $8)
`

type CountDirectoryParams struct {
	Active         bool             `json:"active"`
	OrganizationID pgtype.UUID      `json:"organization_id"`
	Scope          NullContactScope `json:"scope"`
	Specialty      pgtype.Text      `json:"specialty"`
	Favorite       pgtype.Bool      `json:"favorite"`
	Q              pgtype.Text      `json:"q"`
	QEmailHash     pgtype.Text      `json:"q_email_hash"`
	QPhoneHash     pgtype.Text      `json:"q_phone_hash"`
}

func (q *Queries) CountDirectory(ctx context.Context, arg CountDirectoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDirectory,
		arg.Active,
		arg.OrganizationID,
		arg.Scope,
		arg.Specialty,
		arg.Favorite,
		arg.Q,
		arg.QEmailHash,
		arg.QPhoneHash,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (organization_id, name, position, specialty, scope, source, is_favorite, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateContactParams struct {
	OrganizationID uuid.UUID     `json:"organization_id"`
	Name           string        `json:"name"`
	Position       pgtype.Text   `json:"position"`
	Specialty      pgtype.Text   `json:"specialty"`
	Scope          ContactScope  `json:"scope"`
	Source         ContactSource `json:"source"`
	IsFavorite     bool          `json:"is_favorite"`
	Notes          pgtype.Text   `json:"notes"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.OrganizationID,
		arg.Name,
		arg.Position,
		arg.Specialty,
		arg.Scope,
		arg.Source,
		arg.IsFavorite,
		arg.Notes,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createContactChannel = `-- name: CreateContactChannel :one
INSERT INTO contact_channels (contact_id, channel_type, value_encrypted, label, preferred)
VALUES ($1, $2, $3, $4, $5) RETURNING id, contact_id, user_id, channel_type, value_encrypted, label, preferred, active
`

type CreateContactChannelParams struct {
	ContactID      pgtype.UUID        `json:"contact_id"`
	ChannelType    ContactChannelType `json:"channel_type"`
	ValueEncrypted string             `json:"value_encrypted"`
	Label          pgtype.Text        `json:"label"`
	Preferred      bool               `json:"preferred"`
}

func (q *Queries) CreateContactChannel(ctx context.Context, arg CreateContactChannelParams) (ContactChannel, error) {
	row := q.db.QueryRow(ctx, createContactChannel,
		arg.ContactID,
		arg.ChannelType,
		arg.ValueEncrypted,
		arg.Label,
		arg.Preferred,
	)
	var i ContactChannel
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.UserID,
		&i.ChannelType,
		&i.ValueEncrypted,
		&i.Label,
		&i.Preferred,
		&i.Active,
	)
	return i, err
}

const createUserChannel = `-- name: CreateUserChannel :one
INSERT INTO contact_channels (user_id, channel_type, value_encrypted, label, preferred)
VALUES ($1, $2, $3, $4, $5) RETURNING id, contact_id, user_id, channel_type, value_encrypted, label, preferred, active
`

type CreateUserChannelParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	ChannelType    ContactChannelType `json:"channel_type"`
	ValueEncrypted string             `json:"value_encrypted"`
	Label          pgtype.Text        `json:"label"`
	Preferred      bool               `json:"preferred"`
}

func (q *Queries) CreateUserChannel(ctx context.Context, arg CreateUserChannelParams) (ContactChannel, error) {
	row := q.db.QueryRow(ctx, createUserChannel,
		arg.UserID,
		arg.ChannelType,
		arg.ValueEncrypted,
		arg.Label,
		arg.Preferred,
	)
	var i ContactChannel
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.UserID,
		&i.ChannelType,
		&i.ValueEncrypted,
		&i.Label,
		&i.Preferred,
		&i.Active,
	)
	return i, err
}

const deactivateLeftoverMemberships = `-- name: DeactivateLeftoverMemberships :exec
UPDATE team_members SET active = false WHERE contact_id = $1
`

func (q *Queries) DeactivateLeftoverMemberships(ctx context.Context, duplicateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateLeftoverMemberships, duplicateID)
	return err
}

const deleteContactChannel = `-- name: DeleteContactChannel :execrows
DELETE FROM contact_channels WHERE id = $1 AND contact_id = $2
`

type DeleteContactChannelParams struct {
	ID        uuid.UUID   `json:"id"`
	ContactID pgtype.UUID `json:"contact_id"`
}

func (q *Queries) DeleteContactChannel(ctx context.Context, arg DeleteContactChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContactChannel, arg.ID, arg.ContactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserChannel = `-- name: DeleteUserChannel :execrows
DELETE FROM contact_channels WHERE id = $1 AND user_id = $2
`

type DeleteUserChannelParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserChannel(ctx context.Context, arg DeleteUserChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserChannel, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fillContactFromDuplicate = `-- name: FillContactFromDuplicate :exec
UPDATE contacts p SET
  position = COALESCE(p.position, d.position),
  specialty = COALESCE(p.specialty, d.specialty),
  notes = COALESCE(p.notes, d.notes),
  email_encrypted = COALESCE(p.email_encrypted, d.email_encrypted),
  email_hash = COALESCE(p.email_hash, d.email_hash),
  phone_encrypted = COALESCE(p.phone_encrypted, d.phone_encrypted),
  phone_hash = COALESCE(p.phone_hash, d.phone_hash),
  is_favorite = p.is_favorite OR d.is_favorite,
  updated_at = now()
FROM contacts d
WHERE p.id = $1 AND d.id = $2
`

type FillContactFromDuplicateParams struct {
	PrimaryID   uuid.UUID `json:"primary_id"`
	DuplicateID uuid.UUID `json:"duplicate_id"`
}

// Completa los huecos del principal con los datos del duplicado, sin pisar nada.
func (q *Queries) FillContactFromDuplicate(ctx context.Context, arg FillContactFromDuplicateParams) error {
	_, err := q.db.Exec(ctx, fillContactFromDuplicate, arg.PrimaryID, arg.DuplicateID)
	return err
}

const findContactByEmailHash = `-- name: FindContactByEmailHash :one
SELECT id, source FROM contacts WHERE active AND email_hash = $1 ORDER BY created_at LIMIT 1
`

type FindContactByEmailHashRow struct {
	ID     uuid.UUID     `json:"id"`
	Source ContactSource `json:"source"`
}

func (q *Queries) FindContactByEmailHash(ctx context.Context, emailHash pgtype.Text) (FindContactByEmailHashRow, error) {
	row := q.db.QueryRow(ctx, findContactByEmailHash, emailHash)
	var i FindContactByEmailHashRow
	err := row.Scan(&i.ID, &i.Source)
	return i, err
}

const findContactByNameAndOrg = `-- name: FindContactByNameAndOrg :one
SELECT id, source FROM contacts
WHERE active AND organization_id = $1 AND lower(name) = lower($2::text)
ORDER BY created_at LIMIT 1
`

type FindContactByNameAndOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

type FindContactByNameAndOrgRow struct {
	ID     uuid.UUID     `json:"id"`
	Source ContactSource `json:"source"`
}

func (q *Queries) FindContactByNameAndOrg(ctx context.Context, arg FindContactByNameAndOrgParams) (FindContactByNameAndOrgRow, error) {
	row := q.db.QueryRow(ctx, findContactByNameAndOrg, arg.OrganizationID, arg.Name)
	var i FindContactByNameAndOrgRow
	err := row.Scan(&i.ID, &i.Source)
	return i, err
}

const getDirectoryContact = `-- name: GetDirectoryContact :one
SELECT c.id, c.organization_id, c.name, c.position, c.specialty, c.scope, c.source, c.is_favorite, c.email_encrypted, c.email_hash, c.phone_encrypted, c.phone_hash, c.notes, c.active, c.created_at, c.updated_at, o.name AS organization_name, o.type AS organization_type
FROM contacts c JOIN organizations o ON o.id = c.organization_id
WHERE c.id = $1
`

type GetDirectoryContactRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Name             string             `json:"name"`
	Position         pgtype.Text        `json:"position"`
	Specialty        pgtype.Text        `json:"specialty"`
	Scope            ContactScope       `json:"scope"`
	Source           ContactSource      `json:"source"`
	IsFavorite       bool               `json:"is_favorite"`
	EmailEncrypted   pgtype.Text        `json:"email_encrypted"`
	EmailHash        pgtype.Text        `json:"email_hash"`
	PhoneEncrypted   pgtype.Text        `json:"phone_encrypted"`
	PhoneHash        pgtype.Text        `json:"phone_hash"`
	Notes            pgtype.Text        `json:"notes"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrganizationName string             `json:"organization_name"`
	OrganizationType OrganizationType   `json:"organization_type"`
}

func (q *Queries) GetDirectoryContact(ctx context.Context, id uuid.UUID) (GetDirectoryContactRow, error) {
	row := q.db.QueryRow(ctx, getDirectoryContact, id)
	var i GetDirectoryContactRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Position,
		&i.Specialty,
		&i.Scope,
		&i.Source,
		&i.IsFavorite,
		&i.EmailEncrypted,
		&i.EmailHash,
		&i.PhoneEncrypted,
		&i.PhoneHash,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationName,
		&i.OrganizationType,
	)
	return i, err
}

const listChannelsForContacts = `-- name: ListChannelsForContacts :many

SELECT id, contact_id, user_id, channel_type, value_encrypted, label, preferred, active FROM contact_channels
WHERE active AND contact_id = ANY($1::uuid[])
ORDER BY preferred DESC, channel_type, id
`

// ===== Canales =====
func (q *Queries) ListChannelsForContacts(ctx context.Context, contactIds []uuid.UUID) ([]ContactChannel, error) {
	rows, err := q.db.Query(ctx, listChannelsForContacts, contactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactChannel
	for rows.Next() {
		var i ContactChannel
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.UserID,
			&i.ChannelType,
			&i.ValueEncrypted,
			&i.Label,
			&i.Preferred,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsForUser = `-- name: ListChannelsForUser :many
SELECT id, contact_id, user_id, channel_type, value_encrypted, label, preferred, active FROM contact_channels WHERE active AND user_id = $1 ORDER BY preferred DESC, channel_type, id
`

func (q *Queries) ListChannelsForUser(ctx context.Context, userID pgtype.UUID) ([]ContactChannel, error) {
	rows, err := q.db.Query(ctx, listChannelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactChannel
	for rows.Next() {
		var i ContactChannel
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.UserID,
			&i.ChannelType,
			&i.ValueEncrypted,
			&i.Label,
			&i.Preferred,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsForDedupe = `-- name: ListContactsForDedupe :many

SELECT id, organization_id, name, email_hash, phone_hash, source,
  ((email_hash IS NOT NULL)::int + (phone_hash IS NOT NULL)::int
   + (position IS NOT NULL)::int + (specialty IS NOT NULL)::int)::int AS completeness
FROM contacts WHERE active ORDER BY created_at, id
`

type ListContactsForDedupeRow struct {
	ID             uuid.UUID     `json:"id"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	Name           string        `json:"name"`
	EmailHash      pgtype.Text   `json:"email_hash"`
	PhoneHash      pgtype.Text   `json:"phone_hash"`
	Source         ContactSource `json:"source"`
	Completeness   int32         `json:"completeness"`
}

// ===== Consolidación de duplicados (POST /api/directory/merge-duplicates) =====
// Orden por antigüedad: el más antiguo de cada grupo queda como principal,
// salvo que otro esté más completo (ver handler).
func (q *Queries) ListContactsForDedupe(ctx context.Context) ([]ListContactsForDedupeRow, error) {
	rows, err := q.db.Query(ctx, listContactsForDedupe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsForDedupeRow
	for rows.Next() {
		var i ListContactsForDedupeRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.EmailHash,
			&i.PhoneHash,
			&i.Source,
			&i.Completeness,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectory = `-- name: ListDirectory :many

SELECT c.id, c.organization_id, c.name, c.position, c.specialty, c.scope, c.source, c.is_favorite, c.email_encrypted, c.email_hash, c.phone_encrypted, c.phone_hash, c.notes, c.active, c.created_at, c.updated_at, o.name AS organization_name, o.type AS organization_type
FROM contacts c JOIN organizations o ON o.id = c.organization_id
WHERE c.active = $1::boolean
  AND ($2::uuid IS NULL OR c.organization_id = $2)
  AND ($3::contact_scope IS NULL OR c.scope = $3)
  AND ($4::text IS NULL OR unaccent(c.specialty) ILIKE unaccent('%' || $4 || '%'))
  AND ($5::boolean IS NULL OR c.is_favorite = $5)
  AND ($6::text IS NULL
       OR unaccent(c.name) ILIKE unaccent('%' || $6 || '%')
       OR unaccent(c.position) ILIKE unaccent('%' || $6 || '%')
       OR unaccent(c.specialty) ILIKE unaccent('%' || $6 || '%')
       OR unaccent(o.name) ILIKE unaccent('%' || $6 || '%')
       OR c.email_hash = $7
       OR c.phone_hash = $8)
ORDER BY c.is_favorite DESC, c.name
LIMIT $10 OFFSET $9
`

type ListDirectoryParams struct {
	Active         bool             `json:"active"`
	OrganizationID pgtype.UUID      `json:"organization_id"`
	Scope          NullContactScope `json:"scope"`
	Specialty      pgtype.Text      `json:"specialty"`
	Favorite       pgtype.Bool      `json:"favorite"`
	Q              pgtype.Text      `json:"q"`
	QEmailHash     pgtype.Text      `json:"q_email_hash"`
	QPhoneHash     pgtype.Text      `json:"q_phone_hash"`
	PageOffset     int32            `json:"page_offset"`
	PageSize       int32            `json:"page_size"`
}

type ListDirectoryRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Name             string             `json:"name"`
	Position         pgtype.Text        `json:"position"`
	Specialty        pgtype.Text        `json:"specialty"`
	Scope            ContactScope       `json:"scope"`
	Source           ContactSource      `json:"source"`
	IsFavorite       bool               `json:"is_favorite"`
	EmailEncrypted   pgtype.Text        `json:"email_encrypted"`
	EmailHash        pgtype.Text        `json:"email_hash"`
	PhoneEncrypted   pgtype.Text        `json:"phone_encrypted"`
	PhoneHash        pgtype.Text        `json:"phone_hash"`
	Notes            pgtype.Text        `json:"notes"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrganizationName string             `json:"organization_name"`
	OrganizationType OrganizationType   `json:"organization_type"`
}

// Directorio Global de Contactos (spec/04-contratos-api.md, HU-DIR-1/2).
// email/phone están cifrados (AES-256-GCM): la búsqueda por esos campos es por
// igualdad exacta contra su índice ciego (email_hash/phone_hash, HMAC), igual
// que el legacy buscaba por sha256. Nombre/cargo/especialidad/organización sí
// admiten búsqueda parcial (ILIKE).
func (q *Queries) ListDirectory(ctx context.Context, arg ListDirectoryParams) ([]ListDirectoryRow, error) {
	rows, err := q.db.Query(ctx, listDirectory,
		arg.Active,
		arg.OrganizationID,
		arg.Scope,
		arg.Specialty,
		arg.Favorite,
		arg.Q,
		arg.QEmailHash,
		arg.QPhoneHash,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectoryRow
	for rows.Next() {
		var i ListDirectoryRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Position,
			&i.Specialty,
			&i.Scope,
			&i.Source,
			&i.IsFavorite,
			&i.EmailEncrypted,
			&i.EmailHash,
			&i.PhoneEncrypted,
			&i.PhoneHash,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
			&i.OrganizationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveContactChannels = `-- name: MoveContactChannels :exec
UPDATE contact_channels SET contact_id = $1, preferred = false
WHERE contact_id = $2
`

type MoveContactChannelsParams struct {
	PrimaryID   pgtype.UUID `json:"primary_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

// Pierden la marca de preferido: el principal ya puede tener el suyo (a lo
// sumo uno por dueño, uq_contact_channels_preferred_contact).
func (q *Queries) MoveContactChannels(ctx context.Context, arg MoveContactChannelsParams) error {
	_, err := q.db.Exec(ctx, moveContactChannels, arg.PrimaryID, arg.DuplicateID)
	return err
}

const moveTeamMemberships = `-- name: MoveTeamMemberships :exec
UPDATE team_members m SET contact_id = $1
WHERE m.contact_id = $2
  AND NOT EXISTS (SELECT 1 FROM team_members x
                  WHERE x.team_id = m.team_id AND x.contact_id = $1)
`

type MoveTeamMembershipsParams struct {
	PrimaryID   pgtype.UUID `json:"primary_id"`
	DuplicateID pgtype.UUID `json:"duplicate_id"`
}

// Reapunta la membresía al principal, salvo que ya esté en ese equipo.
func (q *Queries) MoveTeamMemberships(ctx context.Context, arg MoveTeamMembershipsParams) error {
	_, err := q.db.Exec(ctx, moveTeamMemberships, arg.PrimaryID, arg.DuplicateID)
	return err
}

const setContactPrimaryChannels = `-- name: SetContactPrimaryChannels :exec
UPDATE contacts SET
  email_encrypted = $1,
  email_hash = $2,
  phone_encrypted = $3,
  phone_hash = $4,
  updated_at = now()
WHERE id = $5
`

type SetContactPrimaryChannelsParams struct {
	EmailEncrypted pgtype.Text `json:"email_encrypted"`
	EmailHash      pgtype.Text `json:"email_hash"`
	PhoneEncrypted pgtype.Text `json:"phone_encrypted"`
	PhoneHash      pgtype.Text `json:"phone_hash"`
	ID             uuid.UUID   `json:"id"`
}

// email/phone de contacts son la copia denormalizada del canal preferido de
// cada tipo (la fuente de verdad son contact_channels), cifrada + indexada
// para listar y buscar sin recorrer los canales.
func (q *Queries) SetContactPrimaryChannels(ctx context.Context, arg SetContactPrimaryChannelsParams) error {
	_, err := q.db.Exec(ctx, setContactPrimaryChannels,
		arg.EmailEncrypted,
		arg.EmailHash,
		arg.PhoneEncrypted,
		arg.PhoneHash,
		arg.ID,
	)
	return err
}

const softDeleteContact = `-- name: SoftDeleteContact :execrows
UPDATE contacts SET active = false, updated_at = now() WHERE id = $1 AND active
`

// Borrado lógico: el contacto puede estar referenciado por team_members (FK
// sin cascada) y por el historial de escalación de fases siguientes.
func (q *Queries) SoftDeleteContact(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteContact, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelValue = `-- name: UpdateChannelValue :exec
UPDATE contact_channels SET value_encrypted = $2 WHERE id = $1
`

type UpdateChannelValueParams struct {
	ID             uuid.UUID `json:"id"`
	ValueEncrypted string    `json:"value_encrypted"`
}

func (q *Queries) UpdateChannelValue(ctx context.Context, arg UpdateChannelValueParams) error {
	_, err := q.db.Exec(ctx, updateChannelValue, arg.ID, arg.ValueEncrypted)
	return err
}

const updateContact = `-- name: UpdateContact :execrows
UPDATE contacts SET
  organization_id = COALESCE($1, organization_id),
  name = COALESCE($2, name),
  position = COALESCE($3, position),
  specialty = COALESCE($4, specialty),
  scope = COALESCE($5, scope),
  is_favorite = COALESCE($6, is_favorite),
  notes = COALESCE($7, notes),
  updated_at = now()
WHERE id = $8
`

type UpdateContactParams struct {
	OrganizationID pgtype.UUID      `json:"organization_id"`
	Name           pgtype.Text      `json:"name"`
	Position       pgtype.Text      `json:"position"`
	Specialty      pgtype.Text      `json:"specialty"`
	Scope          NullContactScope `json:"scope"`
	IsFavorite     pgtype.Bool      `json:"is_favorite"`
	Notes          pgtype.Text      `json:"notes"`
	ID             uuid.UUID        `json:"id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContact,
		arg.OrganizationID,
		arg.Name,
		arg.Position,
		arg.Specialty,
		arg.Scope,
		arg.IsFavorite,
		arg.Notes,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
