// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dotacion.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationSchedule = `-- name: CreateNotificationSchedule :one
INSERT INTO work_shift_notification_schedules (name, frequency, day_of_week, send_time, role_filter, recipients, cc_recipients, created_by, target_period, email_format)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, name, enabled, frequency, day_of_week, send_time, timezone, role_filter, recipients, cc_recipients, last_sent_at, created_by, created_at, updated_at, target_period, email_format
`

type CreateNotificationScheduleParams struct {
	Name         string                        `json:"name"`
	Frequency    NotificationScheduleFrequency `json:"frequency"`
	DayOfWeek    int32                         `json:"day_of_week"`
	SendTime     pgtype.Time                   `json:"send_time"`
	RoleFilter   []string                      `json:"role_filter"`
	Recipients   []string                      `json:"recipients"`
	CcRecipients []string                      `json:"cc_recipients"`
	CreatedBy    uuid.UUID                     `json:"created_by"`
	TargetPeriod string                        `json:"target_period"`
	EmailFormat  string                        `json:"email_format"`
}

func (q *Queries) CreateNotificationSchedule(ctx context.Context, arg CreateNotificationScheduleParams) (WorkShiftNotificationSchedule, error) {
	row := q.db.QueryRow(ctx, createNotificationSchedule,
		arg.Name,
		arg.Frequency,
		arg.DayOfWeek,
		arg.SendTime,
		arg.RoleFilter,
		arg.Recipients,
		arg.CcRecipients,
		arg.CreatedBy,
		arg.TargetPeriod,
		arg.EmailFormat,
	)
	var i WorkShiftNotificationSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Frequency,
		&i.DayOfWeek,
		&i.SendTime,
		&i.Timezone,
		&i.RoleFilter,
		&i.Recipients,
		&i.CcRecipients,
		&i.LastSentAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetPeriod,
		&i.EmailFormat,
	)
	return i, err
}

const createPublicShareLink = `-- name: CreatePublicShareLink :one
INSERT INTO public_share_links (slug, token_hash, is_active, created_by)
VALUES ($1, $2, true, $3) RETURNING id, slug, token_hash, is_active, created_by, created_at, last_accessed_at
`

type CreatePublicShareLinkParams struct {
	Slug      string    `json:"slug"`
	TokenHash string    `json:"token_hash"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreatePublicShareLink(ctx context.Context, arg CreatePublicShareLinkParams) (PublicShareLink, error) {
	row := q.db.QueryRow(ctx, createPublicShareLink, arg.Slug, arg.TokenHash, arg.CreatedBy)
	var i PublicShareLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getActivePublicShareByTokenHash = `-- name: GetActivePublicShareByTokenHash :one
SELECT id, slug, token_hash, is_active, created_by, created_at, last_accessed_at FROM public_share_links WHERE token_hash = $1 AND is_active
`

func (q *Queries) GetActivePublicShareByTokenHash(ctx context.Context, tokenHash string) (PublicShareLink, error) {
	row := q.db.QueryRow(ctx, getActivePublicShareByTokenHash, tokenHash)
	var i PublicShareLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const getNotificationSchedule = `-- name: GetNotificationSchedule :one
SELECT id, name, enabled, frequency, day_of_week, send_time, timezone, role_filter, recipients, cc_recipients, last_sent_at, created_by, created_at, updated_at, target_period, email_format FROM work_shift_notification_schedules WHERE id = $1
`

func (q *Queries) GetNotificationSchedule(ctx context.Context, id uuid.UUID) (WorkShiftNotificationSchedule, error) {
	row := q.db.QueryRow(ctx, getNotificationSchedule, id)
	var i WorkShiftNotificationSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Frequency,
		&i.DayOfWeek,
		&i.SendTime,
		&i.Timezone,
		&i.RoleFilter,
		&i.Recipients,
		&i.CcRecipients,
		&i.LastSentAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetPeriod,
		&i.EmailFormat,
	)
	return i, err
}

const getPublicShareBySlug = `-- name: GetPublicShareBySlug :one

SELECT id, slug, token_hash, is_active, created_by, created_at, last_accessed_at FROM public_share_links WHERE slug = $1
`

// ===== Enlace público TV (slug fijo 'telework', sin UNIQUE en slug: se
// resuelve la fila existente en el handler antes de decidir INSERT/UPDATE) =====
func (q *Queries) GetPublicShareBySlug(ctx context.Context, slug string) (PublicShareLink, error) {
	row := q.db.QueryRow(ctx, getPublicShareBySlug, slug)
	var i PublicShareLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const listAssignmentsForRange = `-- name: ListAssignmentsForRange :many

SELECT id, user_id, assigned_date, condition, notes, created_at FROM work_shift_assignments
WHERE assigned_date BETWEEN $1::date AND $2::date
ORDER BY user_id, assigned_date
`

type ListAssignmentsForRangeParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

// Fase 8 del roadmap: matriz semanal de dotación/teletrabajo
// (work_shift_assignments), enlace público de solo lectura para TV
// (public_share_links) y notificación periódica a RRHH
// (work_shift_notification_schedules). Ver spec/04-contratos-api.md sección
// "Dotación, Teletrabajo y Pantallas de Sala (TV)".
func (q *Queries) ListAssignmentsForRange(ctx context.Context, arg ListAssignmentsForRangeParams) ([]WorkShiftAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsForRange, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkShiftAssignment
	for rows.Next() {
		var i WorkShiftAssignment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AssignedDate,
			&i.Condition,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardSlotsForRange = `-- name: ListGuardSlotsForRange :many
SELECT s.week_start_date, s.week_end_date, t.name AS team_name, c.start_time_utc, c.timezone,
  COALESCE(NULLIF(u.full_name, ''), ct.name, 'Pendiente')::text AS person_name,
  COALESCE(u.cargo_label, '')::text AS cargo_label,
  tm.user_id
FROM rotation_slots s
JOIN rotation_cycles c ON c.id = s.cycle_id
JOIN teams t ON t.id = c.team_id
JOIN team_members tm ON tm.id = s.team_member_id
LEFT JOIN users u ON u.id = tm.user_id
LEFT JOIN contacts ct ON ct.id = tm.contact_id
WHERE t.kind = 'oncall' AND NOT s.is_paused
  AND s.week_start_date <= $1::date AND s.week_end_date >= $2::date
ORDER BY s.week_start_date, t.name
`

type ListGuardSlotsForRangeParams struct {
	ToDate   pgtype.Date `json:"to_date"`
	FromDate pgtype.Date `json:"from_date"`
}

type ListGuardSlotsForRangeRow struct {
	WeekStartDate pgtype.Date `json:"week_start_date"`
	WeekEndDate   pgtype.Date `json:"week_end_date"`
	TeamName      string      `json:"team_name"`
	StartTimeUtc  pgtype.Time `json:"start_time_utc"`
	Timezone      string      `json:"timezone"`
	PersonName    string      `json:"person_name"`
	CargoLabel    string      `json:"cargo_label"`
	UserID        pgtype.UUID `json:"user_id"`
}

// Guardias semanales (equipos "oncall": Guardia N2, Guardia TI…) que tocan
// el periodo, para el correo de dotación en formato lista
// (sendEscalationScheduleInternal del legacy).
func (q *Queries) ListGuardSlotsForRange(ctx context.Context, arg ListGuardSlotsForRangeParams) ([]ListGuardSlotsForRangeRow, error) {
	rows, err := q.db.Query(ctx, listGuardSlotsForRange, arg.ToDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuardSlotsForRangeRow
	for rows.Next() {
		var i ListGuardSlotsForRangeRow
		if err := rows.Scan(
			&i.WeekStartDate,
			&i.WeekEndDate,
			&i.TeamName,
			&i.StartTimeUtc,
			&i.Timezone,
			&i.PersonName,
			&i.CargoLabel,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationSchedules = `-- name: ListNotificationSchedules :many

SELECT id, name, enabled, frequency, day_of_week, send_time, timezone, role_filter, recipients, cc_recipients, last_sent_at, created_by, created_at, updated_at, target_period, email_format FROM work_shift_notification_schedules ORDER BY name
`

// ===== Notificación periódica de dotación (HU-5b) =====
func (q *Queries) ListNotificationSchedules(ctx context.Context) ([]WorkShiftNotificationSchedule, error) {
	rows, err := q.db.Query(ctx, listNotificationSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkShiftNotificationSchedule
	for rows.Next() {
		var i WorkShiftNotificationSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Frequency,
			&i.DayOfWeek,
			&i.SendTime,
			&i.Timezone,
			&i.RoleFilter,
			&i.Recipients,
			&i.CcRecipients,
			&i.LastSentAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TargetPeriod,
			&i.EmailFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationScheduleSent = `-- name: MarkNotificationScheduleSent :exec
UPDATE work_shift_notification_schedules SET last_sent_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkNotificationScheduleSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationScheduleSent, id)
	return err
}

const patchNotificationSchedule = `-- name: PatchNotificationSchedule :one
UPDATE work_shift_notification_schedules SET
  enabled = COALESCE($2, enabled),
  name = COALESCE($3, name),
  frequency = COALESCE($4, frequency),
  day_of_week = COALESCE($5, day_of_week),
  send_time = COALESCE($6, send_time),
  role_filter = COALESCE($7::text[], role_filter),
  recipients = COALESCE($8::text[], recipients),
  cc_recipients = COALESCE($9::text[], cc_recipients),
  target_period = COALESCE($10, target_period),
  email_format = COALESCE($11, email_format),
  updated_at = now()
WHERE id = $1
RETURNING id, name, enabled, frequency, day_of_week, send_time, timezone, role_filter, recipients, cc_recipients, last_sent_at, created_by, created_at, updated_at, target_period, email_format
`

type PatchNotificationScheduleParams struct {
	ID           uuid.UUID                         `json:"id"`
	Enabled      pgtype.Bool                       `json:"enabled"`
	Name         pgtype.Text                       `json:"name"`
	Frequency    NullNotificationScheduleFrequency `json:"frequency"`
	DayOfWeek    pgtype.Int4                       `json:"day_of_week"`
	SendTime     pgtype.Time                       `json:"send_time"`
	RoleFilter   []string                          `json:"role_filter"`
	Recipients   []string                          `json:"recipients"`
	CcRecipients []string                          `json:"cc_recipients"`
	TargetPeriod pgtype.Text                       `json:"target_period"`
	EmailFormat  pgtype.Text                       `json:"email_format"`
}

func (q *Queries) PatchNotificationSchedule(ctx context.Context, arg PatchNotificationScheduleParams) (WorkShiftNotificationSchedule, error) {
	row := q.db.QueryRow(ctx, patchNotificationSchedule,
		arg.ID,
		arg.Enabled,
		arg.Name,
		arg.Frequency,
		arg.DayOfWeek,
		arg.SendTime,
		arg.RoleFilter,
		arg.Recipients,
		arg.CcRecipients,
		arg.TargetPeriod,
		arg.EmailFormat,
	)
	var i WorkShiftNotificationSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Frequency,
		&i.DayOfWeek,
		&i.SendTime,
		&i.Timezone,
		&i.RoleFilter,
		&i.Recipients,
		&i.CcRecipients,
		&i.LastSentAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetPeriod,
		&i.EmailFormat,
	)
	return i, err
}

const rotatePublicShareLink = `-- name: RotatePublicShareLink :one
UPDATE public_share_links SET token_hash = $2, is_active = true, created_by = $3, created_at = now()
WHERE id = $1 RETURNING id, slug, token_hash, is_active, created_by, created_at, last_accessed_at
`

type RotatePublicShareLinkParams struct {
	ID        uuid.UUID `json:"id"`
	TokenHash string    `json:"token_hash"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) RotatePublicShareLink(ctx context.Context, arg RotatePublicShareLinkParams) (PublicShareLink, error) {
	row := q.db.QueryRow(ctx, rotatePublicShareLink, arg.ID, arg.TokenHash, arg.CreatedBy)
	var i PublicShareLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const setPublicShareLinkActive = `-- name: SetPublicShareLinkActive :one
UPDATE public_share_links SET is_active = $2 WHERE id = $1 RETURNING id, slug, token_hash, is_active, created_by, created_at, last_accessed_at
`

type SetPublicShareLinkActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetPublicShareLinkActive(ctx context.Context, arg SetPublicShareLinkActiveParams) (PublicShareLink, error) {
	row := q.db.QueryRow(ctx, setPublicShareLinkActive, arg.ID, arg.IsActive)
	var i PublicShareLink
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}

const touchPublicShareAccess = `-- name: TouchPublicShareAccess :exec
UPDATE public_share_links SET last_accessed_at = now() WHERE id = $1
`

func (q *Queries) TouchPublicShareAccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchPublicShareAccess, id)
	return err
}

const upsertAssignment = `-- name: UpsertAssignment :one
INSERT INTO work_shift_assignments (user_id, assigned_date, condition, notes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, assigned_date) DO UPDATE SET condition = EXCLUDED.condition, notes = EXCLUDED.notes
RETURNING id, user_id, assigned_date, condition, notes, created_at
`

type UpsertAssignmentParams struct {
	UserID       uuid.UUID         `json:"user_id"`
	AssignedDate pgtype.Date       `json:"assigned_date"`
	Condition    TeleworkCondition `json:"condition"`
	Notes        pgtype.Text       `json:"notes"`
}

// Un POST sobre el mismo (userId, assignedDate) corrige la condición en vez
// de fallar con 409 — mismo criterio "upsert" que UpsertTeamCoverage
// (teams.sql) de la Fase 6, más amigable para el admin que corrige un día.
func (q *Queries) UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) (WorkShiftAssignment, error) {
	row := q.db.QueryRow(ctx, upsertAssignment,
		arg.UserID,
		arg.AssignedDate,
		arg.Condition,
		arg.Notes,
	)
	var i WorkShiftAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AssignedDate,
		&i.Condition,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
