// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDraft = `-- name: DeleteDraft :execrows
DELETE FROM entry_drafts WHERE id = $1 AND user_id = $2
`

type DeleteDraftParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDraft(ctx context.Context, arg DeleteDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraft, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDrafts = `-- name: ListDrafts :many
SELECT id, user_id, form_type, draft_key, content, created_at, updated_at, expires_at FROM entry_drafts
WHERE user_id = $1
  AND ($2::text IS NULL OR form_type = $2)
ORDER BY updated_at DESC
`

type ListDraftsParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	FormType pgtype.Text `json:"form_type"`
}

func (q *Queries) ListDrafts(ctx context.Context, arg ListDraftsParams) ([]EntryDraft, error) {
	rows, err := q.db.Query(ctx, listDrafts, arg.UserID, arg.FormType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryDraft
	for rows.Next() {
		var i EntryDraft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FormType,
			&i.DraftKey,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDraft = `-- name: UpsertDraft :one

INSERT INTO entry_drafts (user_id, form_type, draft_key, content)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, form_type, draft_key)
DO UPDATE SET content = EXCLUDED.content, updated_at = now(), expires_at = now() + INTERVAL '7 days'
RETURNING id, user_id, form_type, draft_key, content, created_at, updated_at, expires_at
`

type UpsertDraftParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FormType string    `json:"form_type"`
	DraftKey string    `json:"draft_key"`
	Content  []byte    `json:"content"`
}

// Borradores (Autosave, HU-7d): generaliza personal_notes a cualquier
// formulario largo. draft_key es libre (no FK): el recurso final puede no
// existir todavía en el momento del autosave.
func (q *Queries) UpsertDraft(ctx context.Context, arg UpsertDraftParams) (EntryDraft, error) {
	row := q.db.QueryRow(ctx, upsertDraft,
		arg.UserID,
		arg.FormType,
		arg.DraftKey,
		arg.Content,
	)
	var i EntryDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FormType,
		&i.DraftKey,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
