// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry_comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEntryComment = `-- name: CreateEntryComment :one
INSERT INTO entry_comments (entry_id, user_id, comment, is_system_generated)
VALUES ($1, $2, $3, $4) RETURNING id, entry_id, user_id, comment, is_system_generated, created_at, updated_at
`

type CreateEntryCommentParams struct {
	EntryID           uuid.UUID `json:"entry_id"`
	UserID            uuid.UUID `json:"user_id"`
	Comment           string    `json:"comment"`
	IsSystemGenerated bool      `json:"is_system_generated"`
}

func (q *Queries) CreateEntryComment(ctx context.Context, arg CreateEntryCommentParams) (EntryComment, error) {
	row := q.db.QueryRow(ctx, createEntryComment,
		arg.EntryID,
		arg.UserID,
		arg.Comment,
		arg.IsSystemGenerated,
	)
	var i EntryComment
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.UserID,
		&i.Comment,
		&i.IsSystemGenerated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntryComments = `-- name: ListEntryComments :many
SELECT c.id, c.entry_id, c.user_id, c.comment, c.is_system_generated, c.created_at, c.updated_at, u.username AS author_username
FROM entry_comments c JOIN users u ON u.id = c.user_id
WHERE c.entry_id = $1
ORDER BY c.created_at ASC
`

type ListEntryCommentsRow struct {
	ID                uuid.UUID          `json:"id"`
	EntryID           uuid.UUID          `json:"entry_id"`
	UserID            uuid.UUID          `json:"user_id"`
	Comment           string             `json:"comment"`
	IsSystemGenerated bool               `json:"is_system_generated"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername    string             `json:"author_username"`
}

func (q *Queries) ListEntryComments(ctx context.Context, entryID uuid.UUID) ([]ListEntryCommentsRow, error) {
	rows, err := q.db.Query(ctx, listEntryComments, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntryCommentsRow
	for rows.Next() {
		var i ListEntryCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.UserID,
			&i.Comment,
			&i.IsSystemGenerated,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
