// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkPatchEntries = `-- name: BulkPatchEntries :execrows
UPDATE entries SET
  scope = COALESCE($1, scope),
  tags = COALESCE($2::text[], tags),
  updated_at = now()
WHERE id = ANY($3::uuid[])
`

type BulkPatchEntriesParams struct {
	Scope NullEntryScope `json:"scope"`
	Tags  []string       `json:"tags"`
	Ids   []uuid.UUID    `json:"ids"`
}

// PATCH /api/entries/bulk (admin, HU-7g) — reclasificación masiva.
func (q *Queries) BulkPatchEntries(ctx context.Context, arg BulkPatchEntriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkPatchEntries, arg.Scope, arg.Tags, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countEntries = `-- name: CountEntries :one
SELECT count(*) FROM entries e
WHERE ($1::entry_scope IS NULL OR e.scope = $1)
  AND ($2::entry_type IS NULL OR e.entry_type = $2)
  AND ($3::text IS NULL OR $3 = ANY(e.tags))
  AND ($4::timestamptz IS NULL OR e.created_at >= $4)
  AND ($5::timestamptz IS NULL OR e.created_at < $5)
  AND ($6::text IS NULL OR to_tsvector('spanish', e.content) @@ websearch_to_tsquery('spanish', $6))
`

type CountEntriesParams struct {
	Scope     NullEntryScope     `json:"scope"`
	EntryType NullEntryType      `json:"entry_type"`
	Tag       pgtype.Text        `json:"tag"`
	FromDate  pgtype.Timestamptz `json:"from_date"`
	ToDate    pgtype.Timestamptz `json:"to_date"`
	Q         pgtype.Text        `json:"q"`
}

func (q *Queries) CountEntries(ctx context.Context, arg CountEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntries,
		arg.Scope,
		arg.EntryType,
		arg.Tag,
		arg.FromDate,
		arg.ToDate,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntry = `-- name: CreateEntry :one

INSERT INTO entries (user_id, entry_type, scope, content, tags, service_id, asset_id, image_url, image_hash, image_size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, user_id, entry_type, scope, content, tags, service_id, asset_id, work_shift_id, glpi_ticket_id, glpi_linked_at, ticket_id, image_url, image_hash, image_size_bytes, created_at, updated_at
`

type CreateEntryParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	EntryType      EntryType   `json:"entry_type"`
	Scope          EntryScope  `json:"scope"`
	Content        string      `json:"content"`
	Tags           []string    `json:"tags"`
	ServiceID      pgtype.UUID `json:"service_id"`
	AssetID        pgtype.UUID `json:"asset_id"`
	ImageUrl       pgtype.Text `json:"image_url"`
	ImageHash      pgtype.Text `json:"image_hash"`
	ImageSizeBytes pgtype.Int4 `json:"image_size_bytes"`
}

// Fase 9 del roadmap (spec/02-alcance-y-roadmap.md): bitácora — registro
// operativo central. HU-7: búsqueda de texto completo con
// websearch_to_tsquery, NUNCA to_tsquery directo (rompe con '&'/'!' sueltos),
// contra el índice funcional idx_entries_fulltext ya creado en la Fase 2
// (to_tsvector('spanish', content)) — la expresión del WHERE debe calzar
// exactamente con la del índice para poder usarlo.
func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.UserID,
		arg.EntryType,
		arg.Scope,
		arg.Content,
		arg.Tags,
		arg.ServiceID,
		arg.AssetID,
		arg.ImageUrl,
		arg.ImageHash,
		arg.ImageSizeBytes,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryType,
		&i.Scope,
		&i.Content,
		&i.Tags,
		&i.ServiceID,
		&i.AssetID,
		&i.WorkShiftID,
		&i.GlpiTicketID,
		&i.GlpiLinkedAt,
		&i.TicketID,
		&i.ImageUrl,
		&i.ImageHash,
		&i.ImageSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :one
DELETE FROM entries WHERE id = $1 RETURNING id, user_id, entry_type, scope, content, tags, service_id, asset_id, work_shift_id, glpi_ticket_id, glpi_linked_at, ticket_id, image_url, image_hash, image_size_bytes, created_at, updated_at
`

// Borrado real (no soft-delete, HU-7g) — RETURNING para el snapshot de auditoría.
func (q *Queries) DeleteEntry(ctx context.Context, id uuid.UUID) (Entry, error) {
	row := q.db.QueryRow(ctx, deleteEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryType,
		&i.Scope,
		&i.Content,
		&i.Tags,
		&i.ServiceID,
		&i.AssetID,
		&i.WorkShiftID,
		&i.GlpiTicketID,
		&i.GlpiLinkedAt,
		&i.TicketID,
		&i.ImageUrl,
		&i.ImageHash,
		&i.ImageSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT e.id, e.user_id, e.entry_type, e.scope, e.content, e.tags, e.service_id, e.asset_id, e.work_shift_id, e.glpi_ticket_id, e.glpi_linked_at, e.ticket_id, e.image_url, e.image_hash, e.image_size_bytes, e.created_at, e.updated_at, u.username AS author_username
FROM entries e JOIN users u ON u.id = e.user_id
WHERE e.id = $1
`

type GetEntryRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	EntryType      EntryType          `json:"entry_type"`
	Scope          EntryScope         `json:"scope"`
	Content        string             `json:"content"`
	Tags           []string           `json:"tags"`
	ServiceID      pgtype.UUID        `json:"service_id"`
	AssetID        pgtype.UUID        `json:"asset_id"`
	WorkShiftID    pgtype.UUID        `json:"work_shift_id"`
	GlpiTicketID   pgtype.Text        `json:"glpi_ticket_id"`
	GlpiLinkedAt   pgtype.Timestamptz `json:"glpi_linked_at"`
	TicketID       pgtype.UUID        `json:"ticket_id"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	ImageHash      pgtype.Text        `json:"image_hash"`
	ImageSizeBytes pgtype.Int4        `json:"image_size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
}

func (q *Queries) GetEntry(ctx context.Context, id uuid.UUID) (GetEntryRow, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i GetEntryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryType,
		&i.Scope,
		&i.Content,
		&i.Tags,
		&i.ServiceID,
		&i.AssetID,
		&i.WorkShiftID,
		&i.GlpiTicketID,
		&i.GlpiLinkedAt,
		&i.TicketID,
		&i.ImageUrl,
		&i.ImageHash,
		&i.ImageSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT e.id, e.user_id, e.entry_type, e.scope, e.content, e.tags, e.service_id, e.asset_id, e.work_shift_id, e.glpi_ticket_id, e.glpi_linked_at, e.ticket_id, e.image_url, e.image_hash, e.image_size_bytes, e.created_at, e.updated_at, u.username AS author_username
FROM entries e JOIN users u ON u.id = e.user_id
WHERE ($1::entry_scope IS NULL OR e.scope = $1)
  AND ($2::entry_type IS NULL OR e.entry_type = $2)
  AND ($3::text IS NULL OR $3 = ANY(e.tags))
  AND ($4::timestamptz IS NULL OR e.created_at >= $4)
  AND ($5::timestamptz IS NULL OR e.created_at < $5)
  AND ($6::text IS NULL OR to_tsvector('spanish', e.content) @@ websearch_to_tsquery('spanish', $6))
ORDER BY e.created_at DESC
LIMIT $8 OFFSET $7
`

type ListEntriesParams struct {
	Scope      NullEntryScope     `json:"scope"`
	EntryType  NullEntryType      `json:"entry_type"`
	Tag        pgtype.Text        `json:"tag"`
	FromDate   pgtype.Timestamptz `json:"from_date"`
	ToDate     pgtype.Timestamptz `json:"to_date"`
	Q          pgtype.Text        `json:"q"`
	PageOffset int32              `json:"page_offset"`
	PageSize   int32              `json:"page_size"`
}

type ListEntriesRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	EntryType      EntryType          `json:"entry_type"`
	Scope          EntryScope         `json:"scope"`
	Content        string             `json:"content"`
	Tags           []string           `json:"tags"`
	ServiceID      pgtype.UUID        `json:"service_id"`
	AssetID        pgtype.UUID        `json:"asset_id"`
	WorkShiftID    pgtype.UUID        `json:"work_shift_id"`
	GlpiTicketID   pgtype.Text        `json:"glpi_ticket_id"`
	GlpiLinkedAt   pgtype.Timestamptz `json:"glpi_linked_at"`
	TicketID       pgtype.UUID        `json:"ticket_id"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	ImageHash      pgtype.Text        `json:"image_hash"`
	ImageSizeBytes pgtype.Int4        `json:"image_size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.Scope,
		arg.EntryType,
		arg.Tag,
		arg.FromDate,
		arg.ToDate,
		arg.Q,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryType,
			&i.Scope,
			&i.Content,
			&i.Tags,
			&i.ServiceID,
			&i.AssetID,
			&i.WorkShiftID,
			&i.GlpiTicketID,
			&i.GlpiLinkedAt,
			&i.TicketID,
			&i.ImageUrl,
			&i.ImageHash,
			&i.ImageSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesForExport = `-- name: ListEntriesForExport :many
SELECT e.id, e.user_id, e.entry_type, e.scope, e.content, e.tags, e.service_id, e.asset_id, e.work_shift_id, e.glpi_ticket_id, e.glpi_linked_at, e.ticket_id, e.image_url, e.image_hash, e.image_size_bytes, e.created_at, e.updated_at, u.username AS author_username
FROM entries e JOIN users u ON u.id = e.user_id
WHERE ($1::entry_scope IS NULL OR e.scope = $1)
  AND ($2::entry_type IS NULL OR e.entry_type = $2)
  AND ($3::text IS NULL OR $3 = ANY(e.tags))
  AND ($4::timestamptz IS NULL OR e.created_at >= $4)
  AND ($5::timestamptz IS NULL OR e.created_at < $5)
  AND ($6::text IS NULL OR to_tsvector('spanish', e.content) @@ websearch_to_tsquery('spanish', $6))
ORDER BY e.created_at DESC
`

type ListEntriesForExportParams struct {
	Scope     NullEntryScope     `json:"scope"`
	EntryType NullEntryType      `json:"entry_type"`
	Tag       pgtype.Text        `json:"tag"`
	FromDate  pgtype.Timestamptz `json:"from_date"`
	ToDate    pgtype.Timestamptz `json:"to_date"`
	Q         pgtype.Text        `json:"q"`
}

type ListEntriesForExportRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	EntryType      EntryType          `json:"entry_type"`
	Scope          EntryScope         `json:"scope"`
	Content        string             `json:"content"`
	Tags           []string           `json:"tags"`
	ServiceID      pgtype.UUID        `json:"service_id"`
	AssetID        pgtype.UUID        `json:"asset_id"`
	WorkShiftID    pgtype.UUID        `json:"work_shift_id"`
	GlpiTicketID   pgtype.Text        `json:"glpi_ticket_id"`
	GlpiLinkedAt   pgtype.Timestamptz `json:"glpi_linked_at"`
	TicketID       pgtype.UUID        `json:"ticket_id"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	ImageHash      pgtype.Text        `json:"image_hash"`
	ImageSizeBytes pgtype.Int4        `json:"image_size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
}

// GET /api/entries/export — mismos filtros que ListEntries, sin paginar.
func (q *Queries) ListEntriesForExport(ctx context.Context, arg ListEntriesForExportParams) ([]ListEntriesForExportRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForExport,
		arg.Scope,
		arg.EntryType,
		arg.Tag,
		arg.FromDate,
		arg.ToDate,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesForExportRow
	for rows.Next() {
		var i ListEntriesForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryType,
			&i.Scope,
			&i.Content,
			&i.Tags,
			&i.ServiceID,
			&i.AssetID,
			&i.WorkShiftID,
			&i.GlpiTicketID,
			&i.GlpiLinkedAt,
			&i.TicketID,
			&i.ImageUrl,
			&i.ImageHash,
			&i.ImageSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchEntry = `-- name: PatchEntry :one
UPDATE entries SET
  scope = COALESCE($2, scope),
  content = COALESCE($3, content),
  tags = COALESCE($4::text[], tags),
  service_id = COALESCE($5, service_id),
  asset_id = COALESCE($6, asset_id),
  updated_at = now()
WHERE id = $1
RETURNING id, user_id, entry_type, scope, content, tags, service_id, asset_id, work_shift_id, glpi_ticket_id, glpi_linked_at, ticket_id, image_url, image_hash, image_size_bytes, created_at, updated_at
`

type PatchEntryParams struct {
	ID        uuid.UUID      `json:"id"`
	Scope     NullEntryScope `json:"scope"`
	Content   pgtype.Text    `json:"content"`
	Tags      []string       `json:"tags"`
	ServiceID pgtype.UUID    `json:"service_id"`
	AssetID   pgtype.UUID    `json:"asset_id"`
}

func (q *Queries) PatchEntry(ctx context.Context, arg PatchEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, patchEntry,
		arg.ID,
		arg.Scope,
		arg.Content,
		arg.Tags,
		arg.ServiceID,
		arg.AssetID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryType,
		&i.Scope,
		&i.Content,
		&i.Tags,
		&i.ServiceID,
		&i.AssetID,
		&i.WorkShiftID,
		&i.GlpiTicketID,
		&i.GlpiLinkedAt,
		&i.TicketID,
		&i.ImageUrl,
		&i.ImageHash,
		&i.ImageSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
