// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry_attachments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimAttachment = `-- name: ClaimAttachment :execrows
UPDATE entry_attachments SET entry_id = $2 WHERE id = $1 AND entry_id IS NULL
`

type ClaimAttachmentParams struct {
	ID      uuid.UUID   `json:"id"`
	EntryID pgtype.UUID `json:"entry_id"`
}

// Solo reclama un adjunto todavía huérfano — evita que dos entradas
// terminen apuntando a la misma imagen si el cliente reenvía el mismo
// imageUrl dos veces.
func (q *Queries) ClaimAttachment(ctx context.Context, arg ClaimAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimAttachment, arg.ID, arg.EntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOrphanAttachment = `-- name: CreateOrphanAttachment :one

INSERT INTO entry_attachments (file_name, mime_type, size_bytes, file_data, hash_sha256)
VALUES ($1, $2, $3, $4, $5) RETURNING id, entry_id, file_name, mime_type, size_bytes, file_data, hash_sha256, created_at
`

type CreateOrphanAttachmentParams struct {
	FileName   string `json:"file_name"`
	MimeType   string `json:"mime_type"`
	SizeBytes  int32  `json:"size_bytes"`
	FileData   []byte `json:"file_data"`
	HashSha256 string `json:"hash_sha256"`
}

// Fase 9: imagen simple de una entrada (ver migración 000005 — entry_id
// nullable a propósito). CreateOrphanAttachment inserta sin entrada todavía
// (POST /api/entries/upload-image); ClaimAttachment la asocia al crear la
// entrada real. Sin conversión a WebP ni limpieza EXIF (decisión de esta
// fase, ver spec/00-mapa-mental.md) — se guarda tal cual se subió.
func (q *Queries) CreateOrphanAttachment(ctx context.Context, arg CreateOrphanAttachmentParams) (EntryAttachment, error) {
	row := q.db.QueryRow(ctx, createOrphanAttachment,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.FileData,
		arg.HashSha256,
	)
	var i EntryAttachment
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.FileData,
		&i.HashSha256,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, entry_id, file_name, mime_type, size_bytes, file_data, hash_sha256, created_at FROM entry_attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (EntryAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i EntryAttachment
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.FileData,
		&i.HashSha256,
		&i.CreatedAt,
	)
	return i, err
}
