// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

// Prueba mínima de conectividad real a Postgres para /api/health/ready
// (más que un simple pgxpool.Ping(): confirma que el pool puede ejecutar SQL
// de verdad contra la base, no solo abrir el socket TCP).
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
