// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_rate_limits.sql

package db

import (
	"context"
)

const getLoginRateLimit = `-- name: GetLoginRateLimit :one
SELECT ip_address, attempt_count, window_started_at FROM login_rate_limits WHERE ip_address = $1
`

func (q *Queries) GetLoginRateLimit(ctx context.Context, ipAddress string) (LoginRateLimit, error) {
	row := q.db.QueryRow(ctx, getLoginRateLimit, ipAddress)
	var i LoginRateLimit
	err := row.Scan(&i.IpAddress, &i.AttemptCount, &i.WindowStartedAt)
	return i, err
}

const resetAllLoginRateLimits = `-- name: ResetAllLoginRateLimits :exec
DELETE FROM login_rate_limits
`

func (q *Queries) ResetAllLoginRateLimits(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetAllLoginRateLimits)
	return err
}

const resetLoginRateLimit = `-- name: ResetLoginRateLimit :exec
DELETE FROM login_rate_limits WHERE ip_address = $1
`

// Nueva ventana de 15min, o la válvula de emergencia
// (POST /api/system/rate-limit-reset).
func (q *Queries) ResetLoginRateLimit(ctx context.Context, ipAddress string) error {
	_, err := q.db.Exec(ctx, resetLoginRateLimit, ipAddress)
	return err
}

const upsertLoginAttempt = `-- name: UpsertLoginAttempt :one
INSERT INTO login_rate_limits (ip_address, attempt_count, window_started_at)
VALUES ($1, 1, now())
ON CONFLICT (ip_address) DO UPDATE SET attempt_count = login_rate_limits.attempt_count + 1
RETURNING ip_address, attempt_count, window_started_at
`

// Primer intento desde una IP: crea la fila en 1. Intentos siguientes:
// incrementa. El servicio decide si la ventana de 15min ya venció y hay que
// resetear en vez de incrementar (ver internal/service/ratelimit).
func (q *Queries) UpsertLoginAttempt(ctx context.Context, ipAddress string) (LoginRateLimit, error) {
	row := q.db.QueryRow(ctx, upsertLoginAttempt, ipAddress)
	var i LoginRateLimit
	err := row.Scan(&i.IpAddress, &i.AttemptCount, &i.WindowStartedAt)
	return i, err
}
