// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminNotes = `-- name: GetAdminNotes :one

SELECT n.id, n.content, n.last_edited_by, n.updated_at, u.username AS last_edited_by_username
FROM admin_notes n LEFT JOIN users u ON u.id = n.last_edited_by
WHERE n.id = true
`

type GetAdminNotesRow struct {
	ID                   bool               `json:"id"`
	Content              string             `json:"content"`
	LastEditedBy         pgtype.UUID        `json:"last_edited_by"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	LastEditedByUsername pgtype.Text        `json:"last_edited_by_username"`
}

// Notas Operativas (Fase 9): pizarrón admin (fila singleton id=true) y
// libreta personal (1:1 por usuario). Ambas con autosave/debounce desde el
// frontend, ver spec/04-contratos-api.md sección "Notas Operativas".
func (q *Queries) GetAdminNotes(ctx context.Context) (GetAdminNotesRow, error) {
	row := q.db.QueryRow(ctx, getAdminNotes)
	var i GetAdminNotesRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.LastEditedBy,
		&i.UpdatedAt,
		&i.LastEditedByUsername,
	)
	return i, err
}

const getPersonalNotes = `-- name: GetPersonalNotes :one
SELECT id, user_id, content, updated_at FROM personal_notes WHERE user_id = $1
`

func (q *Queries) GetPersonalNotes(ctx context.Context, userID uuid.UUID) (PersonalNote, error) {
	row := q.db.QueryRow(ctx, getPersonalNotes, userID)
	var i PersonalNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdminNotes = `-- name: UpsertAdminNotes :one
INSERT INTO admin_notes (id, content, last_edited_by, updated_at)
VALUES (true, $1, $2, now())
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, last_edited_by = EXCLUDED.last_edited_by, updated_at = now()
RETURNING id, content, last_edited_by, updated_at
`

type UpsertAdminNotesParams struct {
	Content      string      `json:"content"`
	LastEditedBy pgtype.UUID `json:"last_edited_by"`
}

func (q *Queries) UpsertAdminNotes(ctx context.Context, arg UpsertAdminNotesParams) (AdminNote, error) {
	row := q.db.QueryRow(ctx, upsertAdminNotes, arg.Content, arg.LastEditedBy)
	var i AdminNote
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.LastEditedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPersonalNotes = `-- name: UpsertPersonalNotes :one
INSERT INTO personal_notes (user_id, content, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (user_id) DO UPDATE SET content = EXCLUDED.content, updated_at = now()
RETURNING id, user_id, content, updated_at
`

type UpsertPersonalNotesParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Content string    `json:"content"`
}

func (q *Queries) UpsertPersonalNotes(ctx context.Context, arg UpsertPersonalNotesParams) (PersonalNote, error) {
	row := q.db.QueryRow(ctx, upsertPersonalNotes, arg.UserID, arg.Content)
	var i PersonalNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}
