// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, code, type) VALUES ($1, $2, $3) RETURNING id, name, code, type, active, created_at
`

type CreateOrganizationParams struct {
	Name string           `json:"name"`
	Code string           `json:"code"`
	Type OrganizationType `json:"type"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Code, arg.Type)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const findOrganizationByNameOrCode = `-- name: FindOrganizationByNameOrCode :one
SELECT id, name, code, type, active, created_at FROM organizations
WHERE active AND (lower(name) = lower($1::text) OR lower(code) = lower($1::text))
ORDER BY (lower(code) = lower($1::text)) DESC
LIMIT 1
`

// Import CSV: la columna "Empresa" trae lo que el analista escribió; se acepta
// tanto el nombre como el código, sin distinguir mayúsculas.
func (q *Queries) FindOrganizationByNameOrCode(ctx context.Context, ref string) (Organization, error) {
	row := q.db.QueryRow(ctx, findOrganizationByNameOrCode, ref)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, code, type, active, created_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, code, type, active, created_at FROM organizations
WHERE ($1::organization_type IS NULL OR type = $1)
  AND ($2::boolean IS NULL OR active = $2)
ORDER BY name
`

type ListOrganizationsParams struct {
	Type   NullOrganizationType `json:"type"`
	Active pgtype.Bool          `json:"active"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Type, arg.Active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations SET
  name = COALESCE($2, name),
  code = COALESCE($3, code),
  type = COALESCE($4, type),
  active = COALESCE($5, active)
WHERE id = $1
RETURNING id, name, code, type, active, created_at
`

type UpdateOrganizationParams struct {
	ID     uuid.UUID            `json:"id"`
	Name   pgtype.Text          `json:"name"`
	Code   pgtype.Text          `json:"code"`
	Type   NullOrganizationType `json:"type"`
	Active pgtype.Bool          `json:"active"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Type,
		arg.Active,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
