// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_policy.sql

package db

import (
	"context"
)

const getPasswordMinLength = `-- name: GetPasswordMinLength :one
SELECT password_min_length FROM app_config WHERE id = true
`

func (q *Queries) GetPasswordMinLength(ctx context.Context) (int16, error) {
	row := q.db.QueryRow(ctx, getPasswordMinLength)
	var password_min_length int16
	err := row.Scan(&password_min_length)
	return password_min_length, err
}

const setPasswordMinLength = `-- name: SetPasswordMinLength :one
UPDATE app_config SET password_min_length = $1, updated_at = now() WHERE id = true
RETURNING password_min_length
`

func (q *Queries) SetPasswordMinLength(ctx context.Context, passwordMinLength int16) (int16, error) {
	row := q.db.QueryRow(ctx, setPasswordMinLength, passwordMinLength)
	var password_min_length int16
	err := row.Scan(&password_min_length)
	return password_min_length, err
}
