// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission_groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserPermissionGroup = `-- name: AddUserPermissionGroup :exec
INSERT INTO user_permission_groups (user_id, permission_group_id, assigned_by)
VALUES ($1, $2, $3)
`

type AddUserPermissionGroupParams struct {
	UserID            uuid.UUID   `json:"user_id"`
	PermissionGroupID uuid.UUID   `json:"permission_group_id"`
	AssignedBy        pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) AddUserPermissionGroup(ctx context.Context, arg AddUserPermissionGroupParams) error {
	_, err := q.db.Exec(ctx, addUserPermissionGroup, arg.UserID, arg.PermissionGroupID, arg.AssignedBy)
	return err
}

const createPermissionGroup = `-- name: CreatePermissionGroup :one
INSERT INTO permission_groups (code, name, module_scope, capabilities)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, module_scope, capabilities, active, created_at
`

type CreatePermissionGroupParams struct {
	Code         string                     `json:"code"`
	Name         string                     `json:"name"`
	ModuleScope  PermissionGroupModuleScope `json:"module_scope"`
	Capabilities []string                   `json:"capabilities"`
}

func (q *Queries) CreatePermissionGroup(ctx context.Context, arg CreatePermissionGroupParams) (PermissionGroup, error) {
	row := q.db.QueryRow(ctx, createPermissionGroup,
		arg.Code,
		arg.Name,
		arg.ModuleScope,
		arg.Capabilities,
	)
	var i PermissionGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ModuleScope,
		&i.Capabilities,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionGroup = `-- name: GetPermissionGroup :one
SELECT id, code, name, module_scope, capabilities, active, created_at FROM permission_groups WHERE id = $1
`

func (q *Queries) GetPermissionGroup(ctx context.Context, id uuid.UUID) (PermissionGroup, error) {
	row := q.db.QueryRow(ctx, getPermissionGroup, id)
	var i PermissionGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ModuleScope,
		&i.Capabilities,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissionGroups = `-- name: ListPermissionGroups :many
SELECT id, code, name, module_scope, capabilities, active, created_at FROM permission_groups
WHERE ($1::boolean IS NULL OR active = $1)
ORDER BY name
`

func (q *Queries) ListPermissionGroups(ctx context.Context, active pgtype.Bool) ([]PermissionGroup, error) {
	rows, err := q.db.Query(ctx, listPermissionGroups, active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionGroup
	for rows.Next() {
		var i PermissionGroup
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ModuleScope,
			&i.Capabilities,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionGroups = `-- name: ListUserPermissionGroups :many
SELECT pg.id, pg.code, pg.name, pg.module_scope, pg.capabilities, pg.active, pg.created_at FROM permission_groups pg
JOIN user_permission_groups upg ON upg.permission_group_id = pg.id
WHERE upg.user_id = $1 AND pg.active = true
ORDER BY pg.name
`

func (q *Queries) ListUserPermissionGroups(ctx context.Context, userID uuid.UUID) ([]PermissionGroup, error) {
	rows, err := q.db.Query(ctx, listUserPermissionGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionGroup
	for rows.Next() {
		var i PermissionGroup
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ModuleScope,
			&i.Capabilities,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceUserPermissionGroups = `-- name: ReplaceUserPermissionGroups :exec
DELETE FROM user_permission_groups WHERE user_id = $1
`

func (q *Queries) ReplaceUserPermissionGroups(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceUserPermissionGroups, userID)
	return err
}

const updatePermissionGroup = `-- name: UpdatePermissionGroup :one
UPDATE permission_groups SET
  name = COALESCE($2, name),
  module_scope = COALESCE($3, module_scope),
  capabilities = COALESCE($4, capabilities),
  active = COALESCE($5, active)
WHERE id = $1
RETURNING id, code, name, module_scope, capabilities, active, created_at
`

type UpdatePermissionGroupParams struct {
	ID           uuid.UUID                      `json:"id"`
	Name         pgtype.Text                    `json:"name"`
	ModuleScope  NullPermissionGroupModuleScope `json:"module_scope"`
	Capabilities []string                       `json:"capabilities"`
	Active       pgtype.Bool                    `json:"active"`
}

func (q *Queries) UpdatePermissionGroup(ctx context.Context, arg UpdatePermissionGroupParams) (PermissionGroup, error) {
	row := q.db.QueryRow(ctx, updatePermissionGroup,
		arg.ID,
		arg.Name,
		arg.ModuleScope,
		arg.Capabilities,
		arg.Active,
	)
	var i PermissionGroup
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ModuleScope,
		&i.Capabilities,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
