// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPolicyStep(ctx context.Context, arg AddPolicyStepParams) (EscalationStep, error)
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error)
	AddUserPermissionGroup(ctx context.Context, arg AddUserPermissionGroupParams) error
	// 409 de spec/04-contratos-api.md: la IP de un activo es su identidad operativa.
	AssetIPTaken(ctx context.Context, arg AssetIPTakenParams) (bool, error)
	// PATCH /api/entries/bulk (admin, HU-7g) — reclasificación masiva.
	BulkPatchEntries(ctx context.Context, arg BulkPatchEntriesParams) (int64, error)
	// Solo reclama un adjunto todavía huérfano — evita que dos entradas
	// terminen apuntando a la misma imagen si el cliente reenvía el mismo
	// imageUrl dos veces.
	ClaimAttachment(ctx context.Context, arg ClaimAttachmentParams) (int64, error)
	ClearPasswordResetToken(ctx context.Context, id uuid.UUID) error
	// A lo sumo un canal preferido por dueño (índice único parcial del esquema):
	// marcar uno nuevo desmarca el anterior.
	ClearPreferredContactChannel(ctx context.Context, contactID pgtype.UUID) error
	ClearPreferredUserChannel(ctx context.Context, userID pgtype.UUID) error
	CompleteSetup(ctx context.Context, arg CompleteSetupParams) (AppConfig, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountDirectory(ctx context.Context, arg CountDirectoryParams) (int64, error)
	CountEntries(ctx context.Context, arg CountEntriesParams) (int64, error)
	CountTerritorialUnits(ctx context.Context, arg CountTerritorialUnitsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (uuid.UUID, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (uuid.UUID, error)
	CreateContactChannel(ctx context.Context, arg CreateContactChannelParams) (ContactChannel, error)
	// Fase 9 del roadmap (spec/02-alcance-y-roadmap.md): bitácora — registro
	// operativo central. HU-7: búsqueda de texto completo con
	// websearch_to_tsquery, NUNCA to_tsquery directo (rompe con '&'/'!' sueltos),
	// contra el índice funcional idx_entries_fulltext ya creado en la Fase 2
	// (to_tsvector('spanish', content)) — la expresión del WHERE debe calzar
	// exactamente con la del índice para poder usarlo.
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateEntryComment(ctx context.Context, arg CreateEntryCommentParams) (EntryComment, error)
	CreateLogSource(ctx context.Context, arg CreateLogSourceParams) (CatalogLogSource, error)
	CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (MaintenanceWindow, error)
	CreateNotificationSchedule(ctx context.Context, arg CreateNotificationScheduleParams) (WorkShiftNotificationSchedule, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// Fase 9: imagen simple de una entrada (ver migración 000005 — entry_id
	// nullable a propósito). CreateOrphanAttachment inserta sin entrada todavía
	// (POST /api/entries/upload-image); ClaimAttachment la asocia al crear la
	// entrada real. Sin conversión a WebP ni limpieza EXIF (decisión de esta
	// fase, ver spec/00-mapa-mental.md) — se guarda tal cual se subió.
	CreateOrphanAttachment(ctx context.Context, arg CreateOrphanAttachmentParams) (EntryAttachment, error)
	CreatePermissionGroup(ctx context.Context, arg CreatePermissionGroupParams) (PermissionGroup, error)
	CreatePolicy(ctx context.Context, arg CreatePolicyParams) (EscalationPolicy, error)
	CreatePublicShareLink(ctx context.Context, arg CreatePublicShareLinkParams) (PublicShareLink, error)
	CreateRaciAssignment(ctx context.Context, arg CreateRaciAssignmentParams) (RaciAssignment, error)
	CreateRotationCycle(ctx context.Context, arg CreateRotationCycleParams) (RotationCycle, error)
	CreateRotationOverride(ctx context.Context, arg CreateRotationOverrideParams) (RotationOverride, error)
	CreateRotationSlot(ctx context.Context, arg CreateRotationSlotParams) (RotationSlot, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamGroup(ctx context.Context, arg CreateTeamGroupParams) (TeamGroup, error)
	CreateTerritorialUnit(ctx context.Context, arg CreateTerritorialUnitParams) (TerritorialUnit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserChannel(ctx context.Context, arg CreateUserChannelParams) (ContactChannel, error)
	CreateWorkShift(ctx context.Context, arg CreateWorkShiftParams) (WorkShift, error)
	DeactivateLeftoverMemberships(ctx context.Context, duplicateID pgtype.UUID) error
	DeactivateMaintenanceWindow(ctx context.Context, id uuid.UUID) (int64, error)
	// DELETE /api/users/:id se implementa como soft-delete (active=false), no
	// DELETE real: audit_log.actor_user_id referencia a users(id) sin ON DELETE
	// CASCADE (a propósito, es append-only e inmutable) — borrar de verdad a un
	// usuario que alguna vez hizo algo auditado rompería esa FK. Mismo patrón
	// `active` que ya usa el resto del esquema (organizations, teams, etc.).
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	DeleteContactChannel(ctx context.Context, arg DeleteContactChannelParams) (int64, error)
	DeleteDraft(ctx context.Context, arg DeleteDraftParams) (int64, error)
	// Borrado real (no soft-delete, HU-7g) — RETURNING para el snapshot de auditoría.
	DeleteEntry(ctx context.Context, id uuid.UUID) (Entry, error)
	DeletePolicy(ctx context.Context, id uuid.UUID) (int64, error)
	DeletePolicyStep(ctx context.Context, arg DeletePolicyStepParams) (int64, error)
	DeleteUserChannel(ctx context.Context, arg DeleteUserChannelParams) (int64, error)
	// POST /api/auth/logout — revoca un JTI puntual sin afectar otras sesiones
	// del mismo usuario.
	DenylistToken(ctx context.Context, arg DenylistTokenParams) error
	DisableMFA(ctx context.Context, id uuid.UUID) error
	EnableMFA(ctx context.Context, id uuid.UUID) error
	// app_config es singleton pero no viene precargado por la migración inicial
	// (03-esquema-db.sql no tiene un INSERT semilla) — GET /api/setup/status
	// necesita una fila para leer, así que se asegura antes de leer si todavía
	// no existe, con los defaults de la propia tabla.
	EnsureAppConfigRow(ctx context.Context) error
	// Completa los huecos del principal con los datos del duplicado, sin pisar nada.
	FillContactFromDuplicate(ctx context.Context, arg FillContactFromDuplicateParams) error
	FindContactByEmailHash(ctx context.Context, emailHash pgtype.Text) (FindContactByEmailHashRow, error)
	FindContactByNameAndOrg(ctx context.Context, arg FindContactByNameAndOrgParams) (FindContactByNameAndOrgRow, error)
	// Import CSV: la columna "Empresa" trae lo que el analista escribió; se acepta
	// tanto el nombre como el código, sin distinguir mayúsculas.
	FindOrganizationByNameOrCode(ctx context.Context, ref string) (Organization, error)
	FindPolicyByAsset(ctx context.Context, assetID pgtype.UUID) (uuid.UUID, error)
	// ===== Resolución =====
	FindPolicyByService(ctx context.Context, serviceID pgtype.UUID) (uuid.UUID, error)
	// POST /api/users/force-reset-all — usuarios internos = no invitados
	// (is_guest=false), activos. Devuelve los afectados para poder notificarlos
	// por correo sin una segunda consulta.
	ForceResetAllActivePasswords(ctx context.Context) ([]User, error)
	GetActivePublicShareByTokenHash(ctx context.Context, tokenHash string) (PublicShareLink, error)
	// Notas Operativas (Fase 9): pizarrón admin (fila singleton id=true) y
	// libreta personal (1:1 por usuario). Ambas con autosave/debounce desde el
	// frontend, ver spec/04-contratos-api.md sección "Notas Operativas".
	GetAdminNotes(ctx context.Context) (GetAdminNotesRow, error)
	GetAppConfig(ctx context.Context) (AppConfig, error)
	GetAsset(ctx context.Context, id uuid.UUID) (GetAssetRow, error)
	GetAssetForResolve(ctx context.Context, id uuid.UUID) (GetAssetForResolveRow, error)
	GetAttachment(ctx context.Context, id uuid.UUID) (EntryAttachment, error)
	// El slot regular cuya semana cubre `now` (independiente de is_paused: el
	// handler decide qué hacer con eso vía internal/rotation.Resolve).
	GetCurrentRotationSlot(ctx context.Context, arg GetCurrentRotationSlotParams) (GetCurrentRotationSlotRow, error)
	GetDirectoryContact(ctx context.Context, id uuid.UUID) (GetDirectoryContactRow, error)
	GetEntry(ctx context.Context, id uuid.UUID) (GetEntryRow, error)
	GetLoginRateLimit(ctx context.Context, ipAddress string) (LoginRateLimit, error)
	GetNotificationSchedule(ctx context.Context, id uuid.UUID) (WorkShiftNotificationSchedule, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetPermissionGroup(ctx context.Context, id uuid.UUID) (PermissionGroup, error)
	GetPersonalNotes(ctx context.Context, userID uuid.UUID) (PersonalNote, error)
	GetPolicy(ctx context.Context, id uuid.UUID) (EscalationPolicy, error)
	// ===== Enlace público TV (slug fijo 'telework', sin UNIQUE en slug: se
	// resuelve la fila existente en el handler antes de decidir INSERT/UPDATE) =====
	GetPublicShareBySlug(ctx context.Context, slug string) (PublicShareLink, error)
	GetRotationCycle(ctx context.Context, id uuid.UUID) (RotationCycle, error)
	// smtp_config es singleton (id BOOLEAN PRIMARY KEY DEFAULT true), siempre hay
	// a lo sumo una fila. sqlc.narg permite pgx.ErrNoRows cuando aún no se
	// configuró SMTP (setup inicial no completado).
	GetSMTPConfig(ctx context.Context) (GetSMTPConfigRow, error)
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamMemberDisplay(ctx context.Context, id uuid.UUID) (GetTeamMemberDisplayRow, error)
	GetTerritorialUnit(ctx context.Context, id uuid.UUID) (TerritorialUnit, error)
	// Lock de la fila antes del upsert del import: si el code ya existía con
	// otro path (el dataset lo movió de padre), hay que reubicar sus
	// descendientes con el path viejo — ver RebaseTerritorialSubtree.
	GetTerritorialUnitPathByCodeForUpdate(ctx context.Context, code string) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// El servicio valida la expiración (reset_password_expires_at > now()) en
	// Go, no acá, para poder distinguir "token no existe" de "token vencido" en
	// los tests sin depender del reloj de Postgres.
	GetUserByResetTokenHash(ctx context.Context, resetPasswordTokenHash pgtype.Text) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// ===== Intentos (inmutables, ver migración 000004) =====
	InsertActionLog(ctx context.Context, arg InsertActionLogParams) (EscalationActionLog, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// Hub SSE genérico (Fase 2 del roadmap) — toda publicación pasa por acá para
	// que GET /api/stream/events pueda reponer eventos perdidos vía Last-Event-ID
	// (ver spec/09-alta-disponibilidad-2-nodos.md sección 3.2/9.3).
	InsertSystemEvent(ctx context.Context, arg InsertSystemEventParams) (SystemEvent, error)
	IsTokenDenylisted(ctx context.Context, jti uuid.UUID) (bool, error)
	ListActionLogs(ctx context.Context, arg ListActionLogsParams) ([]ListActionLogsRow, error)
	ListActiveOverridesForCycle(ctx context.Context, arg ListActiveOverridesForCycleParams) ([]RotationOverride, error)
	// ip_address es INET: se lee y escribe como texto (::text / ::inet) para que
	// el tipo Go sea string y Postgres valide el formato (IPv4/IPv6) al insertar.
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error)
	// Fase 8 del roadmap: matriz semanal de dotación/teletrabajo
	// (work_shift_assignments), enlace público de solo lectura para TV
	// (public_share_links) y notificación periódica a RRHH
	// (work_shift_notification_schedules). Ver spec/04-contratos-api.md sección
	// "Dotación, Teletrabajo y Pantallas de Sala (TV)".
	ListAssignmentsForRange(ctx context.Context, arg ListAssignmentsForRangeParams) ([]WorkShiftAssignment, error)
	// GET /api/audit-logs — paginado simple, más reciente primero.
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	// ===== Canales =====
	ListChannelsForContacts(ctx context.Context, contactIds []uuid.UUID) ([]ContactChannel, error)
	ListChannelsForUser(ctx context.Context, userID pgtype.UUID) ([]ContactChannel, error)
	ListChannelsForUsers(ctx context.Context, userIds []uuid.UUID) ([]ContactChannel, error)
	// ===== Consolidación de duplicados (POST /api/directory/merge-duplicates) =====
	// Orden por antigüedad: el más antiguo de cada grupo queda como principal,
	// salvo que otro esté más completo (ver handler).
	ListContactsForDedupe(ctx context.Context) ([]ListContactsForDedupeRow, error)
	ListCoverageForUnits(ctx context.Context, unitIds []uuid.UUID) ([]TeamCoverage, error)
	// Directorio Global de Contactos (spec/04-contratos-api.md, HU-DIR-1/2).
	// email/phone están cifrados (AES-256-GCM): la búsqueda por esos campos es por
	// igualdad exacta contra su índice ciego (email_hash/phone_hash, HMAC), igual
	// que el legacy buscaba por sha256. Nombre/cargo/especialidad/organización sí
	// admiten búsqueda parcial (ILIKE).
	ListDirectory(ctx context.Context, arg ListDirectoryParams) ([]ListDirectoryRow, error)
	ListDrafts(ctx context.Context, arg ListDraftsParams) ([]EntryDraft, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error)
	// GET /api/entries/export — mismos filtros que ListEntries, sin paginar.
	ListEntriesForExport(ctx context.Context, arg ListEntriesForExportParams) ([]ListEntriesForExportRow, error)
	ListEntryComments(ctx context.Context, entryID uuid.UUID) ([]ListEntryCommentsRow, error)
	ListLogSources(ctx context.Context, arg ListLogSourcesParams) ([]CatalogLogSource, error)
	// ===== Ventanas de mantenimiento =====
	ListMaintenanceWindows(ctx context.Context, arg ListMaintenanceWindowsParams) ([]MaintenanceWindow, error)
	// Miembros activos de los equipos a resolver, con lo que la tarjeta necesita
	// mostrar: nombre, especialidad (solo contactos), rol y prioridad.
	ListMembersForTeams(ctx context.Context, teamIds []uuid.UUID) ([]ListMembersForTeamsRow, error)
	// ===== Notificación periódica de dotación (HU-5b) =====
	ListNotificationSchedules(ctx context.Context) ([]WorkShiftNotificationSchedule, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListPermissionGroups(ctx context.Context, active pgtype.Bool) ([]PermissionGroup, error)
	// ===== Políticas y pasos =====
	ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]EscalationPolicy, error)
	ListPoliciesForUnits(ctx context.Context, unitIds []uuid.UUID) ([]ListPoliciesForUnitsRow, error)
	ListPolicySteps(ctx context.Context, policyIds []uuid.UUID) ([]ListPolicyStepsRow, error)
	// ===== RACI (solo dato en esta fase, sin UI) =====
	ListRaciAssignments(ctx context.Context, arg ListRaciAssignmentsParams) ([]ListRaciAssignmentsRow, error)
	// Fase 8 del roadmap (spec/02-alcance-y-roadmap.md): motor de rotación
	// unificado (rotation_cycles/rotation_slots/rotation_overrides) y work_shifts.
	// GET /api/rotation-slots, POST /api/rotation-slots y PATCH
	// /api/rotation-slots/:id no estaban en el contrato original (faltaba forma
	// de armar/pausar el rol semanal, ver 04-contratos-api.md) — agregados acá,
	// mismo patrón de gap real que las Fases 5-7.
	ListRotationCyclesByTeam(ctx context.Context, teamID pgtype.UUID) ([]RotationCycle, error)
	ListRotationSlotsByCycle(ctx context.Context, cycleID uuid.UUID) ([]ListRotationSlotsByCycleRow, error)
	// ===== Servicios (módulo SOC) =====
	ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error)
	// Reposición tras reconexión: todo lo publicado después de Last-Event-ID.
	ListSystemEventsSince(ctx context.Context, arg ListSystemEventsSinceParams) ([]SystemEvent, error)
	ListSystemFeatures(ctx context.Context) ([]SystemFeature, error)
	ListTeamCoverage(ctx context.Context, teamID uuid.UUID) ([]ListTeamCoverageRow, error)
	ListTeamGroups(ctx context.Context, arg ListTeamGroupsParams) ([]TeamGroup, error)
	// Un miembro es un usuario interno O un contacto del directorio (CHECK
	// exactamente uno): se devuelve el nombre de cualquiera de los dos.
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error)
	ListTeamsForResolve(ctx context.Context, teamIds []uuid.UUID) ([]ListTeamsForResolveRow, error)
	// GET /api/territorial-units — ?parentId= devuelve un nivel (hijos directos);
	// sin parentId devuelve el árbol completo aplanado, ordenado por path (el
	// frontend lo indenta por nlevel sin reconstruir nada). child_count deja al
	// frontend saber si un nodo es expandible sin pedir otro nivel a ciegas.
	ListTerritorialUnits(ctx context.Context, arg ListTerritorialUnitsParams) ([]ListTerritorialUnitsRow, error)
	// Quiénes ya se intentaron en este paso durante el incidente en curso (desde
	// "since"), para que el modo sequential llame al siguiente y no repita.
	ListTriedContactsForStep(ctx context.Context, arg ListTriedContactsForStepParams) ([]pgtype.UUID, error)
	// Camino desde la unidad hacia la raíz (ltree @>), de la más específica a la
	// menos: es el orden en que se busca política o cobertura (HU-1).
	ListUnitAncestors(ctx context.Context, id uuid.UUID) ([]ListUnitAncestorsRow, error)
	ListUserPermissionGroups(ctx context.Context, userID uuid.UUID) ([]PermissionGroup, error)
	// ?role=&active= son opcionales (04-contratos-api.md) — sqlc.narg + el
	// patrón "columna = $n OR $n IS NULL" evita escribir dos queries a mano.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Candidatas para notify: ventanas activas del servicio, del activo, o de
	// cualquier unidad del camino territorial (un mantenimiento sobre toda la
	// zona Calama también cubre a sus routers).
	ListWindowsForScope(ctx context.Context, arg ListWindowsForScopeParams) ([]MaintenanceWindow, error)
	ListWorkShifts(ctx context.Context, active pgtype.Bool) ([]WorkShift, error)
	LockUser(ctx context.Context, arg LockUserParams) error
	// PATCH /api/config/territorial-labels — merge parcial (jsonb ||): solo pisa
	// los niveles que vienen en el request, el resto queda como estaba.
	MergeTerritorialLabels(ctx context.Context, labels []byte) ([]byte, error)
	// Pierden la marca de preferido: el principal ya puede tener el suyo (a lo
	// sumo uno por dueño, uq_contact_channels_preferred_contact).
	MoveContactChannels(ctx context.Context, arg MoveContactChannelsParams) error
	// Reapunta la membresía al principal, salvo que ya esté en ese equipo.
	MoveTeamMemberships(ctx context.Context, arg MoveTeamMembershipsParams) error
	PatchEntry(ctx context.Context, arg PatchEntryParams) (Entry, error)
	PatchNotificationSchedule(ctx context.Context, arg PatchNotificationScheduleParams) (WorkShiftNotificationSchedule, error)
	// HU-5: pausar sin borrar la fila (conserva el historial del rol).
	PatchRotationSlotPause(ctx context.Context, arg PatchRotationSlotPauseParams) (RotationSlot, error)
	// Prueba mínima de conectividad real a Postgres para /api/health/ready
	// (más que un simple pgxpool.Ping(): confirma que el pool puede ejecutar SQL
	// de verdad contra la base, no solo abrir el socket TCP).
	Ping(ctx context.Context) (int32, error)
	// Housekeeping: una vez que un JTI expiró de verdad, ya no hace falta
	// consultarlo (el JWT tampoco pasaría Verify() por expiración propia).
	PurgeExpiredDenylistedTokens(ctx context.Context) error
	// Reubica los descendientes de un nodo cuyo path cambió (reimport que lo
	// movió de padre) — incluidos los sitios agregados a mano que el dataset
	// no conoce y por lo tanto no vuelve a upsertear.
	RebaseTerritorialSubtree(ctx context.Context, arg RebaseTerritorialSubtreeParams) error
	RegisterFailedLogin(ctx context.Context, id uuid.UUID) (int32, error)
	// Re-hash oportunista en login (spec/07-backend-arquitectura-go.md sección
	// 6.5) — a diferencia de UpdateUserPassword, NO toca must_change_password:
	// esto es transparente para el usuario, no un cambio de contraseña real.
	RehashPassword(ctx context.Context, arg RehashPasswordParams) error
	RemoveTeamCoverage(ctx context.Context, arg RemoveTeamCoverageParams) (int64, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error)
	ReplaceUserPermissionGroups(ctx context.Context, userID uuid.UUID) error
	ResetAllLoginRateLimits(ctx context.Context) error
	ResetFailedLoginAttempts(ctx context.Context, id uuid.UUID) error
	// Nueva ventana de 15min, o la válvula de emergencia
	// (POST /api/system/rate-limit-reset).
	ResetLoginRateLimit(ctx context.Context, ipAddress string) error
	RotatePublicShareLink(ctx context.Context, arg RotatePublicShareLinkParams) (PublicShareLink, error)
	// email/phone de contacts son la copia denormalizada del canal preferido de
	// cada tipo (la fuente de verdad son contact_channels), cifrada + indexada
	// para listar y buscar sin recorrer los canales.
	SetContactPrimaryChannels(ctx context.Context, arg SetContactPrimaryChannelsParams) error
	SetMFASecret(ctx context.Context, arg SetMFASecretParams) error
	SetModuleFlags(ctx context.Context, arg SetModuleFlagsParams) (AppConfig, error)
	SetMustChangePassword(ctx context.Context, arg SetMustChangePasswordParams) error
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error
	SetPublicShareLinkActive(ctx context.Context, arg SetPublicShareLinkActiveParams) (PublicShareLink, error)
	// Borrado lógico: el contacto puede estar referenciado por team_members (FK
	// sin cascada) y por el historial de escalación de fases siguientes.
	SoftDeleteContact(ctx context.Context, id uuid.UUID) (int64, error)
	TouchPublicShareAccess(ctx context.Context, id uuid.UUID) error
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (int64, error)
	UpdateChannelValue(ctx context.Context, arg UpdateChannelValueParams) error
	UpdateContact(ctx context.Context, arg UpdateContactParams) (int64, error)
	UpdateLogSource(ctx context.Context, arg UpdateLogSourceParams) (CatalogLogSource, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdatePermissionGroup(ctx context.Context, arg UpdatePermissionGroupParams) (PermissionGroup, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateSystemFeature(ctx context.Context, arg UpdateSystemFeatureParams) (SystemFeature, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	// PATCH /api/territorial-units/:id — correcciones manuales (HU-TERR-3). No
	// permite cambiar code/kind/parent: eso reescribiría el árbol y es
	// administración fina fuera del alcance de la Fase 5.
	UpdateTerritorialUnit(ctx context.Context, arg UpdateTerritorialUnitParams) (TerritorialUnit, error)
	// PATCH /api/users/:id — campos parciales: NULL en un parámetro conserva el
	// valor actual (COALESCE), no lo borra.
	UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (User, error)
	// Limpia must_change_password al completar el cambio (04-contratos-api.md:
	// "Limpia el flag al completar").
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertAdminNotes(ctx context.Context, arg UpsertAdminNotesParams) (AdminNote, error)
	// Un POST sobre el mismo (userId, assignedDate) corrige la condición en vez
	// de fallar con 409 — mismo criterio "upsert" que UpsertTeamCoverage
	// (teams.sql) de la Fase 6, más amigable para el admin que corrige un día.
	UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) (WorkShiftAssignment, error)
	// Borradores (Autosave, HU-7d): generaliza personal_notes a cualquier
	// formulario largo. draft_key es libre (no FK): el recurso final puede no
	// existir todavía en el momento del autosave.
	UpsertDraft(ctx context.Context, arg UpsertDraftParams) (EntryDraft, error)
	// Primer intento desde una IP: crea la fila en 1. Intentos siguientes:
	// incrementa. El servicio decide si la ventana de 15min ya venció y hay que
	// resetear en vez de incrementar (ver internal/service/ratelimit).
	UpsertLoginAttempt(ctx context.Context, ipAddress string) (LoginRateLimit, error)
	UpsertPersonalNotes(ctx context.Context, arg UpsertPersonalNotesParams) (PersonalNote, error)
	UpsertSMTPConfig(ctx context.Context, arg UpsertSMTPConfigParams) error
	UpsertTeamCoverage(ctx context.Context, arg UpsertTeamCoverageParams) (TeamCoverage, error)
	// POST /api/territorial-units/import — upsert por code (idempotente). No
	// toca `active` ni `address`: si el admin desactivó o completó a mano una
	// fila importada, reimportar el dataset no se lo pisa (HU-TERR-3). Las
	// coordenadas solo se actualizan si el import trae un valor, nunca se
	// borran por venir vacías. `xmax = 0` distingue insert de update.
	UpsertTerritorialUnit(ctx context.Context, arg UpsertTerritorialUnitParams) (UpsertTerritorialUnitRow, error)
}

var _ Querier = (*Queries)(nil)
