// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// smtp_config es singleton (id BOOLEAN PRIMARY KEY DEFAULT true), siempre hay
	// a lo sumo una fila. sqlc.narg permite pgx.ErrNoRows cuando aún no se
	// configuró SMTP (setup inicial no completado).
	GetSMTPConfig(ctx context.Context) (GetSMTPConfigRow, error)
	// Hub SSE genérico (Fase 2 del roadmap) — toda publicación pasa por acá para
	// que GET /api/stream/events pueda reponer eventos perdidos vía Last-Event-ID
	// (ver spec/09-alta-disponibilidad-2-nodos.md sección 3.2/9.3).
	InsertSystemEvent(ctx context.Context, arg InsertSystemEventParams) (SystemEvent, error)
	// Reposición tras reconexión: todo lo publicado después de Last-Event-ID.
	ListSystemEventsSince(ctx context.Context, arg ListSystemEventsSinceParams) ([]SystemEvent, error)
	// Prueba mínima de conectividad real a Postgres para /api/health/ready
	// (más que un simple pgxpool.Ping(): confirma que el pool puede ejecutar SQL
	// de verdad contra la base, no solo abrir el socket TCP).
	Ping(ctx context.Context) (int32, error)
	UpsertSMTPConfig(ctx context.Context, arg UpsertSMTPConfigParams) error
}

var _ Querier = (*Queries)(nil)
