// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ackClientAlert = `-- name: AckClientAlert :exec
INSERT INTO client_alert_acks (rule_id, user_id, occurrence_key, context) VALUES ($1, $2, $3, $4)
ON CONFLICT (rule_id, user_id, occurrence_key, context) DO NOTHING
`

type AckClientAlertParams struct {
	RuleID        uuid.UUID `json:"rule_id"`
	UserID        uuid.UUID `json:"user_id"`
	OccurrenceKey string    `json:"occurrence_key"`
	Context       string    `json:"context"`
}

func (q *Queries) AckClientAlert(ctx context.Context, arg AckClientAlertParams) error {
	_, err := q.db.Exec(ctx, ackClientAlert,
		arg.RuleID,
		arg.UserID,
		arg.OccurrenceKey,
		arg.Context,
	)
	return err
}

const countReportHistory = `-- name: CountReportHistory :one
SELECT count(*) FROM report_history WHERE ($1::text IS NULL OR kind = $1)
`

func (q *Queries) CountReportHistory(ctx context.Context, kind pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countReportHistory, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClientAlertRule = `-- name: CreateClientAlertRule :one
INSERT INTO client_alert_rules (organization_id, name, enabled, contexts, timezone, priority, valid_from, valid_to, holiday_dates, time_windows, channels, message, requires_ack, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13, $14)
RETURNING id, organization_id, name, enabled, contexts, timezone, priority, valid_from, valid_to, holiday_dates, time_windows, channels, message, requires_ack, updated_by, created_at, updated_at
`

type CreateClientAlertRuleParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Enabled        bool               `json:"enabled"`
	Contexts       []string           `json:"contexts"`
	Timezone       string             `json:"timezone"`
	Priority       int32              `json:"priority"`
	ValidFrom      pgtype.Timestamptz `json:"valid_from"`
	ValidTo        pgtype.Timestamptz `json:"valid_to"`
	HolidayDates   []pgtype.Date      `json:"holiday_dates"`
	TimeWindows    []byte             `json:"time_windows"`
	Channels       []string           `json:"channels"`
	Message        string             `json:"message"`
	RequiresAck    bool               `json:"requires_ack"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) CreateClientAlertRule(ctx context.Context, arg CreateClientAlertRuleParams) (ClientAlertRule, error) {
	row := q.db.QueryRow(ctx, createClientAlertRule,
		arg.OrganizationID,
		arg.Name,
		arg.Enabled,
		arg.Contexts,
		arg.Timezone,
		arg.Priority,
		arg.ValidFrom,
		arg.ValidTo,
		arg.HolidayDates,
		arg.TimeWindows,
		arg.Channels,
		arg.Message,
		arg.RequiresAck,
		arg.UpdatedBy,
	)
	var i ClientAlertRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Enabled,
		&i.Contexts,
		&i.Timezone,
		&i.Priority,
		&i.ValidFrom,
		&i.ValidTo,
		&i.HolidayDates,
		&i.TimeWindows,
		&i.Channels,
		&i.Message,
		&i.RequiresAck,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReportOperationType = `-- name: CreateReportOperationType :one
INSERT INTO report_operation_types (name, info_default, enabled) VALUES ($1, $2, $3) RETURNING id, name, info_default, enabled, created_at, updated_at
`

type CreateReportOperationTypeParams struct {
	Name        string `json:"name"`
	InfoDefault string `json:"info_default"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) CreateReportOperationType(ctx context.Context, arg CreateReportOperationTypeParams) (ReportOperationType, error) {
	row := q.db.QueryRow(ctx, createReportOperationType, arg.Name, arg.InfoDefault, arg.Enabled)
	var i ReportOperationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InfoDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClientAlertRule = `-- name: DeleteClientAlertRule :execrows
DELETE FROM client_alert_rules WHERE id = $1
`

func (q *Queries) DeleteClientAlertRule(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClientAlertRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReportHistory = `-- name: DeleteReportHistory :execrows
DELETE FROM report_history WHERE id = $1
`

func (q *Queries) DeleteReportHistory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReportHistory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReportOperationType = `-- name: DeleteReportOperationType :execrows
DELETE FROM report_operation_types WHERE id = $1
`

func (q *Queries) DeleteReportOperationType(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReportOperationType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClientAlertRule = `-- name: GetClientAlertRule :one
SELECT id, organization_id, name, enabled, contexts, timezone, priority, valid_from, valid_to, holiday_dates, time_windows, channels, message, requires_ack, updated_by, created_at, updated_at FROM client_alert_rules WHERE id = $1
`

func (q *Queries) GetClientAlertRule(ctx context.Context, id uuid.UUID) (ClientAlertRule, error) {
	row := q.db.QueryRow(ctx, getClientAlertRule, id)
	var i ClientAlertRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Enabled,
		&i.Contexts,
		&i.Timezone,
		&i.Priority,
		&i.ValidFrom,
		&i.ValidTo,
		&i.HolidayDates,
		&i.TimeWindows,
		&i.Channels,
		&i.Message,
		&i.RequiresAck,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportHistory = `-- name: GetReportHistory :one
SELECT h.id, h.kind, h.title, h.subject, h.organization_id, h.service_id, h.recipients, h.cc_recipients, h.html, h.payload, h.status, h.error, h.sent_by, h.sent_by_username, h.created_at, o.name AS organization_name FROM report_history h LEFT JOIN organizations o ON o.id = h.organization_id WHERE h.id = $1
`

type GetReportHistoryRow struct {
	ID               uuid.UUID          `json:"id"`
	Kind             string             `json:"kind"`
	Title            string             `json:"title"`
	Subject          string             `json:"subject"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	ServiceID        pgtype.UUID        `json:"service_id"`
	Recipients       []string           `json:"recipients"`
	CcRecipients     []string           `json:"cc_recipients"`
	Html             string             `json:"html"`
	Payload          []byte             `json:"payload"`
	Status           string             `json:"status"`
	Error            pgtype.Text        `json:"error"`
	SentBy           pgtype.UUID        `json:"sent_by"`
	SentByUsername   string             `json:"sent_by_username"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OrganizationName pgtype.Text        `json:"organization_name"`
}

func (q *Queries) GetReportHistory(ctx context.Context, id uuid.UUID) (GetReportHistoryRow, error) {
	row := q.db.QueryRow(ctx, getReportHistory, id)
	var i GetReportHistoryRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Subject,
		&i.OrganizationID,
		&i.ServiceID,
		&i.Recipients,
		&i.CcRecipients,
		&i.Html,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.SentBy,
		&i.SentByUsername,
		&i.CreatedAt,
		&i.OrganizationName,
	)
	return i, err
}

const hasClientAlertAck = `-- name: HasClientAlertAck :one
SELECT EXISTS (SELECT 1 FROM client_alert_acks WHERE rule_id = $1 AND user_id = $2 AND occurrence_key = $3 AND context = $4)
`

type HasClientAlertAckParams struct {
	RuleID        uuid.UUID `json:"rule_id"`
	UserID        uuid.UUID `json:"user_id"`
	OccurrenceKey string    `json:"occurrence_key"`
	Context       string    `json:"context"`
}

func (q *Queries) HasClientAlertAck(ctx context.Context, arg HasClientAlertAckParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasClientAlertAck,
		arg.RuleID,
		arg.UserID,
		arg.OccurrenceKey,
		arg.Context,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertReportHistory = `-- name: InsertReportHistory :one

INSERT INTO report_history (kind, title, subject, organization_id, service_id, recipients, cc_recipients, html, payload, status, error, sent_by, sent_by_username)
VALUES ($1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13)
RETURNING id, created_at
`

type InsertReportHistoryParams struct {
	Kind           string      `json:"kind"`
	Title          string      `json:"title"`
	Subject        string      `json:"subject"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ServiceID      pgtype.UUID `json:"service_id"`
	Recipients     []string    `json:"recipients"`
	CcRecipients   []string    `json:"cc_recipients"`
	Html           string      `json:"html"`
	Payload        []byte      `json:"payload"`
	Status         string      `json:"status"`
	Error          pgtype.Text `json:"error"`
	SentBy         pgtype.UUID `json:"sent_by"`
	SentByUsername string      `json:"sent_by_username"`
}

type InsertReportHistoryRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ===== Reportes (comentario del dueño #10) =====
func (q *Queries) InsertReportHistory(ctx context.Context, arg InsertReportHistoryParams) (InsertReportHistoryRow, error) {
	row := q.db.QueryRow(ctx, insertReportHistory,
		arg.Kind,
		arg.Title,
		arg.Subject,
		arg.OrganizationID,
		arg.ServiceID,
		arg.Recipients,
		arg.CcRecipients,
		arg.Html,
		arg.Payload,
		arg.Status,
		arg.Error,
		arg.SentBy,
		arg.SentByUsername,
	)
	var i InsertReportHistoryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listActiveClientAlertRules = `-- name: ListActiveClientAlertRules :many
SELECT r.id, r.organization_id, r.name, r.enabled, r.contexts, r.timezone, r.priority, r.valid_from, r.valid_to, r.holiday_dates, r.time_windows, r.channels, r.message, r.requires_ack, r.updated_by, r.created_at, r.updated_at, o.name AS organization_name FROM client_alert_rules r JOIN organizations o ON o.id = r.organization_id
WHERE r.enabled AND r.organization_id = $1 ORDER BY r.priority, r.name
`

type ListActiveClientAlertRulesRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Name             string             `json:"name"`
	Enabled          bool               `json:"enabled"`
	Contexts         []string           `json:"contexts"`
	Timezone         string             `json:"timezone"`
	Priority         int32              `json:"priority"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ValidTo          pgtype.Timestamptz `json:"valid_to"`
	HolidayDates     []pgtype.Date      `json:"holiday_dates"`
	TimeWindows      []byte             `json:"time_windows"`
	Channels         []string           `json:"channels"`
	Message          string             `json:"message"`
	RequiresAck      bool               `json:"requires_ack"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrganizationName string             `json:"organization_name"`
}

func (q *Queries) ListActiveClientAlertRules(ctx context.Context, organizationID uuid.UUID) ([]ListActiveClientAlertRulesRow, error) {
	rows, err := q.db.Query(ctx, listActiveClientAlertRules, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveClientAlertRulesRow
	for rows.Next() {
		var i ListActiveClientAlertRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Enabled,
			&i.Contexts,
			&i.Timezone,
			&i.Priority,
			&i.ValidFrom,
			&i.ValidTo,
			&i.HolidayDates,
			&i.TimeWindows,
			&i.Channels,
			&i.Message,
			&i.RequiresAck,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientAlertRules = `-- name: ListClientAlertRules :many

SELECT r.id, r.organization_id, r.name, r.enabled, r.contexts, r.timezone, r.priority, r.valid_from, r.valid_to, r.holiday_dates, r.time_windows, r.channels, r.message, r.requires_ack, r.updated_by, r.created_at, r.updated_at, o.name AS organization_name FROM client_alert_rules r JOIN organizations o ON o.id = r.organization_id
WHERE ($1::uuid IS NULL OR r.organization_id = $1)
ORDER BY o.name, r.priority, r.name
`

type ListClientAlertRulesRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Name             string             `json:"name"`
	Enabled          bool               `json:"enabled"`
	Contexts         []string           `json:"contexts"`
	Timezone         string             `json:"timezone"`
	Priority         int32              `json:"priority"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ValidTo          pgtype.Timestamptz `json:"valid_to"`
	HolidayDates     []pgtype.Date      `json:"holiday_dates"`
	TimeWindows      []byte             `json:"time_windows"`
	Channels         []string           `json:"channels"`
	Message          string             `json:"message"`
	RequiresAck      bool               `json:"requires_ack"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrganizationName string             `json:"organization_name"`
}

// ===== Avisos por cliente =====
func (q *Queries) ListClientAlertRules(ctx context.Context, organizationID pgtype.UUID) ([]ListClientAlertRulesRow, error) {
	rows, err := q.db.Query(ctx, listClientAlertRules, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientAlertRulesRow
	for rows.Next() {
		var i ListClientAlertRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Enabled,
			&i.Contexts,
			&i.Timezone,
			&i.Priority,
			&i.ValidFrom,
			&i.ValidTo,
			&i.HolidayDates,
			&i.TimeWindows,
			&i.Channels,
			&i.Message,
			&i.RequiresAck,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailDomainSources = `-- name: ListEmailDomainSources :many
SELECT email::text AS value, false AS encrypted FROM users WHERE email IS NOT NULL AND email <> ''
UNION ALL
SELECT cc.value_encrypted AS value, true AS encrypted FROM contact_channels cc WHERE cc.channel_type = 'email'
`

type ListEmailDomainSourcesRow struct {
	Value     string `json:"value"`
	Encrypted bool   `json:"encrypted"`
}

// Correos conocidos para los dominios permitidos (getValidSOCDomains del
// legacy): usuarios en claro; los de contactos van cifrados y se descifran
// en Go.
func (q *Queries) ListEmailDomainSources(ctx context.Context) ([]ListEmailDomainSourcesRow, error) {
	rows, err := q.db.Query(ctx, listEmailDomainSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailDomainSourcesRow
	for rows.Next() {
		var i ListEmailDomainSourcesRow
		if err := rows.Scan(&i.Value, &i.Encrypted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscalationEmailsForOrganization = `-- name: ListEscalationEmailsForOrganization :many
SELECT DISTINCT tm.recipient_type::text AS recipient_type, cc.value_encrypted
FROM services s
JOIN escalation_policies p ON p.service_id = s.id AND p.active
JOIN escalation_steps st ON st.policy_id = p.id AND st.step_order = (SELECT min(x.step_order) FROM escalation_steps x WHERE x.policy_id = p.id)
JOIN team_members tm ON tm.team_id = st.team_id AND tm.active
JOIN contact_channels cc ON cc.contact_id = tm.contact_id AND cc.channel_type = 'email'
WHERE s.organization_id = $1 AND ($2::uuid IS NULL OR s.id = $2)
`

type ListEscalationEmailsForOrganizationParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ServiceID      pgtype.UUID `json:"service_id"`
}

type ListEscalationEmailsForOrganizationRow struct {
	RecipientType  string `json:"recipient_type"`
	ValueEncrypted string `json:"value_encrypted"`
}

// Para/CC propuestos: los correos de los integrantes del primer paso del
// escalamiento de cada servicio del cliente (como el legacy proponía los
// PARA/CC del cliente).
func (q *Queries) ListEscalationEmailsForOrganization(ctx context.Context, arg ListEscalationEmailsForOrganizationParams) ([]ListEscalationEmailsForOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listEscalationEmailsForOrganization, arg.OrganizationID, arg.ServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEscalationEmailsForOrganizationRow
	for rows.Next() {
		var i ListEscalationEmailsForOrganizationRow
		if err := rows.Scan(&i.RecipientType, &i.ValueEncrypted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportHistory = `-- name: ListReportHistory :many
SELECT h.id, h.kind, h.title, h.subject, h.organization_id, o.name AS organization_name, h.recipients, h.cc_recipients,
  h.status, h.error, h.sent_by_username, h.created_at, (h.payload IS NOT NULL)::boolean AS reusable
FROM report_history h LEFT JOIN organizations o ON o.id = h.organization_id
WHERE ($1::text IS NULL OR h.kind = $1)
ORDER BY h.created_at DESC
LIMIT $3 OFFSET $2
`

type ListReportHistoryParams struct {
	Kind     pgtype.Text `json:"kind"`
	SkipRows int32       `json:"skip_rows"`
	MaxRows  int32       `json:"max_rows"`
}

type ListReportHistoryRow struct {
	ID               uuid.UUID          `json:"id"`
	Kind             string             `json:"kind"`
	Title            string             `json:"title"`
	Subject          string             `json:"subject"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	OrganizationName pgtype.Text        `json:"organization_name"`
	Recipients       []string           `json:"recipients"`
	CcRecipients     []string           `json:"cc_recipients"`
	Status           string             `json:"status"`
	Error            pgtype.Text        `json:"error"`
	SentByUsername   string             `json:"sent_by_username"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Reusable         bool               `json:"reusable"`
}

// Sin el html (pesa): la lista del historial.
func (q *Queries) ListReportHistory(ctx context.Context, arg ListReportHistoryParams) ([]ListReportHistoryRow, error) {
	rows, err := q.db.Query(ctx, listReportHistory, arg.Kind, arg.SkipRows, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportHistoryRow
	for rows.Next() {
		var i ListReportHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.Subject,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Recipients,
			&i.CcRecipients,
			&i.Status,
			&i.Error,
			&i.SentByUsername,
			&i.CreatedAt,
			&i.Reusable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportOperationTypes = `-- name: ListReportOperationTypes :many

SELECT id, name, info_default, enabled, created_at, updated_at FROM report_operation_types ORDER BY name
`

// ===== Tipos de operación del informe de incidente =====
func (q *Queries) ListReportOperationTypes(ctx context.Context) ([]ReportOperationType, error) {
	rows, err := q.db.Query(ctx, listReportOperationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportOperationType
	for rows.Next() {
		var i ReportOperationType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InfoDefault,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientAlertRule = `-- name: UpdateClientAlertRule :one
UPDATE client_alert_rules SET organization_id = $1, name = $2, enabled = $3, contexts = $4,
  timezone = $5, priority = $6, valid_from = $7, valid_to = $8,
  holiday_dates = $9, time_windows = $10, channels = $11, message = $12,
  requires_ack = $13, updated_by = $14, updated_at = now()
WHERE id = $15 RETURNING id, organization_id, name, enabled, contexts, timezone, priority, valid_from, valid_to, holiday_dates, time_windows, channels, message, requires_ack, updated_by, created_at, updated_at
`

type UpdateClientAlertRuleParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Enabled        bool               `json:"enabled"`
	Contexts       []string           `json:"contexts"`
	Timezone       string             `json:"timezone"`
	Priority       int32              `json:"priority"`
	ValidFrom      pgtype.Timestamptz `json:"valid_from"`
	ValidTo        pgtype.Timestamptz `json:"valid_to"`
	HolidayDates   []pgtype.Date      `json:"holiday_dates"`
	TimeWindows    []byte             `json:"time_windows"`
	Channels       []string           `json:"channels"`
	Message        string             `json:"message"`
	RequiresAck    bool               `json:"requires_ack"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateClientAlertRule(ctx context.Context, arg UpdateClientAlertRuleParams) (ClientAlertRule, error) {
	row := q.db.QueryRow(ctx, updateClientAlertRule,
		arg.OrganizationID,
		arg.Name,
		arg.Enabled,
		arg.Contexts,
		arg.Timezone,
		arg.Priority,
		arg.ValidFrom,
		arg.ValidTo,
		arg.HolidayDates,
		arg.TimeWindows,
		arg.Channels,
		arg.Message,
		arg.RequiresAck,
		arg.UpdatedBy,
		arg.ID,
	)
	var i ClientAlertRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Enabled,
		&i.Contexts,
		&i.Timezone,
		&i.Priority,
		&i.ValidFrom,
		&i.ValidTo,
		&i.HolidayDates,
		&i.TimeWindows,
		&i.Channels,
		&i.Message,
		&i.RequiresAck,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReportOperationType = `-- name: UpdateReportOperationType :one
UPDATE report_operation_types SET name = $2, info_default = $3, enabled = $4, updated_at = now() WHERE id = $1 RETURNING id, name, info_default, enabled, created_at, updated_at
`

type UpdateReportOperationTypeParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	InfoDefault string    `json:"info_default"`
	Enabled     bool      `json:"enabled"`
}

func (q *Queries) UpdateReportOperationType(ctx context.Context, arg UpdateReportOperationTypeParams) (ReportOperationType, error) {
	row := q.db.QueryRow(ctx, updateReportOperationType,
		arg.ID,
		arg.Name,
		arg.InfoDefault,
		arg.Enabled,
	)
	var i ReportOperationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InfoDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
