// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rotation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRotationCycle = `-- name: CreateRotationCycle :one
INSERT INTO rotation_cycles (team_id, start_day_of_week, start_time_utc, duration_days, timezone)
VALUES ($1, $2, $3, $4, $5) RETURNING id, team_id, start_day_of_week, start_time_utc, duration_days, timezone, active
`

type CreateRotationCycleParams struct {
	TeamID         uuid.UUID   `json:"team_id"`
	StartDayOfWeek int32       `json:"start_day_of_week"`
	StartTimeUtc   pgtype.Time `json:"start_time_utc"`
	DurationDays   int32       `json:"duration_days"`
	Timezone       string      `json:"timezone"`
}

func (q *Queries) CreateRotationCycle(ctx context.Context, arg CreateRotationCycleParams) (RotationCycle, error) {
	row := q.db.QueryRow(ctx, createRotationCycle,
		arg.TeamID,
		arg.StartDayOfWeek,
		arg.StartTimeUtc,
		arg.DurationDays,
		arg.Timezone,
	)
	var i RotationCycle
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.StartDayOfWeek,
		&i.StartTimeUtc,
		&i.DurationDays,
		&i.Timezone,
		&i.Active,
	)
	return i, err
}

const createRotationOverride = `-- name: CreateRotationOverride :one
INSERT INTO rotation_overrides (cycle_id, original_team_member_id, replacement_team_member_id, start_date, end_date, reason, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, cycle_id, original_team_member_id, replacement_team_member_id, start_date, end_date, reason, created_by, created_at
`

type CreateRotationOverrideParams struct {
	CycleID                 uuid.UUID          `json:"cycle_id"`
	OriginalTeamMemberID    pgtype.UUID        `json:"original_team_member_id"`
	ReplacementTeamMemberID uuid.UUID          `json:"replacement_team_member_id"`
	StartDate               pgtype.Timestamptz `json:"start_date"`
	EndDate                 pgtype.Timestamptz `json:"end_date"`
	Reason                  string             `json:"reason"`
	CreatedBy               uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreateRotationOverride(ctx context.Context, arg CreateRotationOverrideParams) (RotationOverride, error) {
	row := q.db.QueryRow(ctx, createRotationOverride,
		arg.CycleID,
		arg.OriginalTeamMemberID,
		arg.ReplacementTeamMemberID,
		arg.StartDate,
		arg.EndDate,
		arg.Reason,
		arg.CreatedBy,
	)
	var i RotationOverride
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.OriginalTeamMemberID,
		&i.ReplacementTeamMemberID,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createRotationSlot = `-- name: CreateRotationSlot :one
INSERT INTO rotation_slots (cycle_id, team_member_id, week_start_date, week_end_date)
VALUES ($1, $2, $3, $4) RETURNING id, cycle_id, team_member_id, week_start_date, week_end_date, is_paused, paused_reason
`

type CreateRotationSlotParams struct {
	CycleID       uuid.UUID   `json:"cycle_id"`
	TeamMemberID  uuid.UUID   `json:"team_member_id"`
	WeekStartDate pgtype.Date `json:"week_start_date"`
	WeekEndDate   pgtype.Date `json:"week_end_date"`
}

func (q *Queries) CreateRotationSlot(ctx context.Context, arg CreateRotationSlotParams) (RotationSlot, error) {
	row := q.db.QueryRow(ctx, createRotationSlot,
		arg.CycleID,
		arg.TeamMemberID,
		arg.WeekStartDate,
		arg.WeekEndDate,
	)
	var i RotationSlot
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.TeamMemberID,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.IsPaused,
		&i.PausedReason,
	)
	return i, err
}

const createWorkShift = `-- name: CreateWorkShift :one
INSERT INTO work_shifts (
  rotation_cycle_id, name, start_time, end_time, timezone, shift_type,
  checklist_template_start_id, checklist_template_end_id, email_recipients
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, rotation_cycle_id, name, start_time, end_time, timezone, shift_type, checklist_template_start_id, checklist_template_end_id, email_recipients, active
`

type CreateWorkShiftParams struct {
	RotationCycleID          pgtype.UUID `json:"rotation_cycle_id"`
	Name                     string      `json:"name"`
	StartTime                pgtype.Time `json:"start_time"`
	EndTime                  pgtype.Time `json:"end_time"`
	Timezone                 string      `json:"timezone"`
	ShiftType                string      `json:"shift_type"`
	ChecklistTemplateStartID pgtype.UUID `json:"checklist_template_start_id"`
	ChecklistTemplateEndID   pgtype.UUID `json:"checklist_template_end_id"`
	EmailRecipients          []string    `json:"email_recipients"`
}

func (q *Queries) CreateWorkShift(ctx context.Context, arg CreateWorkShiftParams) (WorkShift, error) {
	row := q.db.QueryRow(ctx, createWorkShift,
		arg.RotationCycleID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
		arg.ShiftType,
		arg.ChecklistTemplateStartID,
		arg.ChecklistTemplateEndID,
		arg.EmailRecipients,
	)
	var i WorkShift
	err := row.Scan(
		&i.ID,
		&i.RotationCycleID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.ShiftType,
		&i.ChecklistTemplateStartID,
		&i.ChecklistTemplateEndID,
		&i.EmailRecipients,
		&i.Active,
	)
	return i, err
}

const getCurrentRotationSlot = `-- name: GetCurrentRotationSlot :one
SELECT s.id, s.cycle_id, s.team_member_id, s.week_start_date, s.week_end_date, s.is_paused, s.paused_reason, COALESCE(u.username, c.name, '')::text AS display_name
FROM rotation_slots s
JOIN team_members m ON m.id = s.team_member_id
LEFT JOIN users u ON u.id = m.user_id
LEFT JOIN contacts c ON c.id = m.contact_id
WHERE s.cycle_id = $1
  AND s.week_start_date <= $2::date
  AND s.week_end_date >= $2::date
ORDER BY s.week_start_date DESC
LIMIT 1
`

type GetCurrentRotationSlotParams struct {
	CycleID uuid.UUID   `json:"cycle_id"`
	Today   pgtype.Date `json:"today"`
}

type GetCurrentRotationSlotRow struct {
	ID            uuid.UUID   `json:"id"`
	CycleID       uuid.UUID   `json:"cycle_id"`
	TeamMemberID  uuid.UUID   `json:"team_member_id"`
	WeekStartDate pgtype.Date `json:"week_start_date"`
	WeekEndDate   pgtype.Date `json:"week_end_date"`
	IsPaused      bool        `json:"is_paused"`
	PausedReason  pgtype.Text `json:"paused_reason"`
	DisplayName   string      `json:"display_name"`
}

// El slot regular cuya semana cubre `now` (independiente de is_paused: el
// handler decide qué hacer con eso vía internal/rotation.Resolve).
func (q *Queries) GetCurrentRotationSlot(ctx context.Context, arg GetCurrentRotationSlotParams) (GetCurrentRotationSlotRow, error) {
	row := q.db.QueryRow(ctx, getCurrentRotationSlot, arg.CycleID, arg.Today)
	var i GetCurrentRotationSlotRow
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.TeamMemberID,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.IsPaused,
		&i.PausedReason,
		&i.DisplayName,
	)
	return i, err
}

const getRotationCycle = `-- name: GetRotationCycle :one
SELECT id, team_id, start_day_of_week, start_time_utc, duration_days, timezone, active FROM rotation_cycles WHERE id = $1
`

func (q *Queries) GetRotationCycle(ctx context.Context, id uuid.UUID) (RotationCycle, error) {
	row := q.db.QueryRow(ctx, getRotationCycle, id)
	var i RotationCycle
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.StartDayOfWeek,
		&i.StartTimeUtc,
		&i.DurationDays,
		&i.Timezone,
		&i.Active,
	)
	return i, err
}

const getTeamMemberDisplay = `-- name: GetTeamMemberDisplay :one
SELECT m.id, m.team_id, m.user_id, m.contact_id, COALESCE(u.username, c.name, '')::text AS display_name
FROM team_members m
LEFT JOIN users u ON u.id = m.user_id
LEFT JOIN contacts c ON c.id = m.contact_id
WHERE m.id = $1
`

type GetTeamMemberDisplayRow struct {
	ID          uuid.UUID   `json:"id"`
	TeamID      uuid.UUID   `json:"team_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ContactID   pgtype.UUID `json:"contact_id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) GetTeamMemberDisplay(ctx context.Context, id uuid.UUID) (GetTeamMemberDisplayRow, error) {
	row := q.db.QueryRow(ctx, getTeamMemberDisplay, id)
	var i GetTeamMemberDisplayRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.ContactID,
		&i.DisplayName,
	)
	return i, err
}

const listActiveOverridesForCycle = `-- name: ListActiveOverridesForCycle :many
SELECT id, cycle_id, original_team_member_id, replacement_team_member_id, start_date, end_date, reason, created_by, created_at FROM rotation_overrides
WHERE cycle_id = $1
  AND start_date <= $2::timestamptz
  AND end_date > $2::timestamptz
ORDER BY start_date DESC
`

type ListActiveOverridesForCycleParams struct {
	CycleID uuid.UUID          `json:"cycle_id"`
	Now     pgtype.Timestamptz `json:"now"`
}

func (q *Queries) ListActiveOverridesForCycle(ctx context.Context, arg ListActiveOverridesForCycleParams) ([]RotationOverride, error) {
	rows, err := q.db.Query(ctx, listActiveOverridesForCycle, arg.CycleID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RotationOverride
	for rows.Next() {
		var i RotationOverride
		if err := rows.Scan(
			&i.ID,
			&i.CycleID,
			&i.OriginalTeamMemberID,
			&i.ReplacementTeamMemberID,
			&i.StartDate,
			&i.EndDate,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRotationCyclesByTeam = `-- name: ListRotationCyclesByTeam :many

SELECT id, team_id, start_day_of_week, start_time_utc, duration_days, timezone, active FROM rotation_cycles
WHERE ($1::uuid IS NULL OR team_id = $1)
ORDER BY team_id
`

// Fase 8 del roadmap (spec/02-alcance-y-roadmap.md): motor de rotación
// unificado (rotation_cycles/rotation_slots/rotation_overrides) y work_shifts.
// GET /api/rotation-slots, POST /api/rotation-slots y PATCH
// /api/rotation-slots/:id no estaban en el contrato original (faltaba forma
// de armar/pausar el rol semanal, ver 04-contratos-api.md) — agregados acá,
// mismo patrón de gap real que las Fases 5-7.
func (q *Queries) ListRotationCyclesByTeam(ctx context.Context, teamID pgtype.UUID) ([]RotationCycle, error) {
	rows, err := q.db.Query(ctx, listRotationCyclesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RotationCycle
	for rows.Next() {
		var i RotationCycle
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.StartDayOfWeek,
			&i.StartTimeUtc,
			&i.DurationDays,
			&i.Timezone,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRotationSlotsByCycle = `-- name: ListRotationSlotsByCycle :many
SELECT s.id, s.cycle_id, s.team_member_id, s.week_start_date, s.week_end_date, s.is_paused, s.paused_reason, COALESCE(u.username, c.name, '')::text AS display_name
FROM rotation_slots s
JOIN team_members m ON m.id = s.team_member_id
LEFT JOIN users u ON u.id = m.user_id
LEFT JOIN contacts c ON c.id = m.contact_id
WHERE s.cycle_id = $1
ORDER BY s.week_start_date DESC
`

type ListRotationSlotsByCycleRow struct {
	ID            uuid.UUID   `json:"id"`
	CycleID       uuid.UUID   `json:"cycle_id"`
	TeamMemberID  uuid.UUID   `json:"team_member_id"`
	WeekStartDate pgtype.Date `json:"week_start_date"`
	WeekEndDate   pgtype.Date `json:"week_end_date"`
	IsPaused      bool        `json:"is_paused"`
	PausedReason  pgtype.Text `json:"paused_reason"`
	DisplayName   string      `json:"display_name"`
}

func (q *Queries) ListRotationSlotsByCycle(ctx context.Context, cycleID uuid.UUID) ([]ListRotationSlotsByCycleRow, error) {
	rows, err := q.db.Query(ctx, listRotationSlotsByCycle, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRotationSlotsByCycleRow
	for rows.Next() {
		var i ListRotationSlotsByCycleRow
		if err := rows.Scan(
			&i.ID,
			&i.CycleID,
			&i.TeamMemberID,
			&i.WeekStartDate,
			&i.WeekEndDate,
			&i.IsPaused,
			&i.PausedReason,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkShifts = `-- name: ListWorkShifts :many
SELECT id, rotation_cycle_id, name, start_time, end_time, timezone, shift_type, checklist_template_start_id, checklist_template_end_id, email_recipients, active FROM work_shifts
WHERE ($1::boolean IS NULL OR active = $1)
ORDER BY name
`

func (q *Queries) ListWorkShifts(ctx context.Context, active pgtype.Bool) ([]WorkShift, error) {
	rows, err := q.db.Query(ctx, listWorkShifts, active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkShift
	for rows.Next() {
		var i WorkShift
		if err := rows.Scan(
			&i.ID,
			&i.RotationCycleID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.ShiftType,
			&i.ChecklistTemplateStartID,
			&i.ChecklistTemplateEndID,
			&i.EmailRecipients,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchRotationSlotPause = `-- name: PatchRotationSlotPause :one
UPDATE rotation_slots SET is_paused = $2, paused_reason = $3 WHERE id = $1 RETURNING id, cycle_id, team_member_id, week_start_date, week_end_date, is_paused, paused_reason
`

type PatchRotationSlotPauseParams struct {
	ID           uuid.UUID   `json:"id"`
	IsPaused     bool        `json:"is_paused"`
	PausedReason pgtype.Text `json:"paused_reason"`
}

// HU-5: pausar sin borrar la fila (conserva el historial del rol).
func (q *Queries) PatchRotationSlotPause(ctx context.Context, arg PatchRotationSlotPauseParams) (RotationSlot, error) {
	row := q.db.QueryRow(ctx, patchRotationSlotPause, arg.ID, arg.IsPaused, arg.PausedReason)
	var i RotationSlot
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.TeamMemberID,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.IsPaused,
		&i.PausedReason,
	)
	return i, err
}
