// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shift_reminders.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimShiftReminderSend = `-- name: ClaimShiftReminderSend :execrows
INSERT INTO shift_reminder_sends (reminder_id, work_shift_id, trigger_key, recipients_count, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (reminder_id, work_shift_id, trigger_key) DO NOTHING
`

type ClaimShiftReminderSendParams struct {
	ReminderID      uuid.UUID `json:"reminder_id"`
	WorkShiftID     uuid.UUID `json:"work_shift_id"`
	TriggerKey      string    `json:"trigger_key"`
	RecipientsCount int32     `json:"recipients_count"`
	Status          string    `json:"status"`
}

// Reserva el envío de un bloque u hora: 0 filas = otro nodo (u otra vuelta
// del planificador) ya lo tomó, y no se envía de nuevo.
func (q *Queries) ClaimShiftReminderSend(ctx context.Context, arg ClaimShiftReminderSendParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimShiftReminderSend,
		arg.ReminderID,
		arg.WorkShiftID,
		arg.TriggerKey,
		arg.RecipientsCount,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createShiftReminder = `-- name: CreateShiftReminder :one
INSERT INTO shift_reminders (label, reminder_text, frequency_type, interval_hours, fixed_times, target_shift_ids, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, label, reminder_text, frequency_type, interval_hours, fixed_times, target_shift_ids, enabled, created_by, created_at, updated_at
`

type CreateShiftReminderParams struct {
	Label          string      `json:"label"`
	ReminderText   string      `json:"reminder_text"`
	FrequencyType  string      `json:"frequency_type"`
	IntervalHours  int32       `json:"interval_hours"`
	FixedTimes     []string    `json:"fixed_times"`
	TargetShiftIds []uuid.UUID `json:"target_shift_ids"`
	Enabled        bool        `json:"enabled"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateShiftReminder(ctx context.Context, arg CreateShiftReminderParams) (ShiftReminder, error) {
	row := q.db.QueryRow(ctx, createShiftReminder,
		arg.Label,
		arg.ReminderText,
		arg.FrequencyType,
		arg.IntervalHours,
		arg.FixedTimes,
		arg.TargetShiftIds,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i ShiftReminder
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.ReminderText,
		&i.FrequencyType,
		&i.IntervalHours,
		&i.FixedTimes,
		&i.TargetShiftIds,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShiftReminder = `-- name: DeleteShiftReminder :execrows
DELETE FROM shift_reminders WHERE id = $1
`

func (q *Queries) DeleteShiftReminder(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShiftReminder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShiftReminder = `-- name: GetShiftReminder :one
SELECT id, label, reminder_text, frequency_type, interval_hours, fixed_times, target_shift_ids, enabled, created_by, created_at, updated_at FROM shift_reminders WHERE id = $1
`

func (q *Queries) GetShiftReminder(ctx context.Context, id uuid.UUID) (ShiftReminder, error) {
	row := q.db.QueryRow(ctx, getShiftReminder, id)
	var i ShiftReminder
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.ReminderText,
		&i.FrequencyType,
		&i.IntervalHours,
		&i.FixedTimes,
		&i.TargetShiftIds,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledShiftReminders = `-- name: ListEnabledShiftReminders :many
SELECT id, label, reminder_text, frequency_type, interval_hours, fixed_times, target_shift_ids, enabled, created_by, created_at, updated_at FROM shift_reminders WHERE enabled ORDER BY created_at
`

func (q *Queries) ListEnabledShiftReminders(ctx context.Context) ([]ShiftReminder, error) {
	rows, err := q.db.Query(ctx, listEnabledShiftReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftReminder
	for rows.Next() {
		var i ShiftReminder
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.ReminderText,
			&i.FrequencyType,
			&i.IntervalHours,
			&i.FixedTimes,
			&i.TargetShiftIds,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftReminders = `-- name: ListShiftReminders :many

SELECT r.id, r.label, r.reminder_text, r.frequency_type, r.interval_hours, r.fixed_times, r.target_shift_ids, r.enabled, r.created_by, r.created_at, r.updated_at,
  last.sent_at AS last_sent_at,
  COALESCE(last.recipients_count, 0)::int AS last_recipients_count,
  COALESCE(last.status, '')::text AS last_status
FROM shift_reminders r
LEFT JOIN LATERAL (
  SELECT s.sent_at, s.recipients_count, s.status
  FROM shift_reminder_sends s
  WHERE s.reminder_id = r.id
  ORDER BY s.sent_at DESC
  LIMIT 1
) last ON true
ORDER BY r.created_at
`

type ListShiftRemindersRow struct {
	ID                  uuid.UUID          `json:"id"`
	Label               string             `json:"label"`
	ReminderText        string             `json:"reminder_text"`
	FrequencyType       string             `json:"frequency_type"`
	IntervalHours       int32              `json:"interval_hours"`
	FixedTimes          []string           `json:"fixed_times"`
	TargetShiftIds      []uuid.UUID        `json:"target_shift_ids"`
	Enabled             bool               `json:"enabled"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastSentAt          pgtype.Timestamptz `json:"last_sent_at"`
	LastRecipientsCount int32              `json:"last_recipients_count"`
	LastStatus          string             `json:"last_status"`
}

// Recordatorios de turno por correo (spec/12-pendientes.md §2.3b).
// Con el último envío de cada uno, para la tabla de Administración → Turnos.
func (q *Queries) ListShiftReminders(ctx context.Context) ([]ListShiftRemindersRow, error) {
	rows, err := q.db.Query(ctx, listShiftReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShiftRemindersRow
	for rows.Next() {
		var i ListShiftRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.ReminderText,
			&i.FrequencyType,
			&i.IntervalHours,
			&i.FixedTimes,
			&i.TargetShiftIds,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSentAt,
			&i.LastRecipientsCount,
			&i.LastStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShiftReminderSendFailed = `-- name: MarkShiftReminderSendFailed :exec
UPDATE shift_reminder_sends SET status = 'failed', error = $4
WHERE reminder_id = $1 AND work_shift_id = $2 AND trigger_key = $3
`

type MarkShiftReminderSendFailedParams struct {
	ReminderID  uuid.UUID   `json:"reminder_id"`
	WorkShiftID uuid.UUID   `json:"work_shift_id"`
	TriggerKey  string      `json:"trigger_key"`
	Error       pgtype.Text `json:"error"`
}

func (q *Queries) MarkShiftReminderSendFailed(ctx context.Context, arg MarkShiftReminderSendFailedParams) error {
	_, err := q.db.Exec(ctx, markShiftReminderSendFailed,
		arg.ReminderID,
		arg.WorkShiftID,
		arg.TriggerKey,
		arg.Error,
	)
	return err
}

const updateShiftReminder = `-- name: UpdateShiftReminder :one
UPDATE shift_reminders SET
  label = $2, reminder_text = $3, frequency_type = $4, interval_hours = $5,
  fixed_times = $6, target_shift_ids = $7, enabled = $8, updated_at = now()
WHERE id = $1
RETURNING id, label, reminder_text, frequency_type, interval_hours, fixed_times, target_shift_ids, enabled, created_by, created_at, updated_at
`

type UpdateShiftReminderParams struct {
	ID             uuid.UUID   `json:"id"`
	Label          string      `json:"label"`
	ReminderText   string      `json:"reminder_text"`
	FrequencyType  string      `json:"frequency_type"`
	IntervalHours  int32       `json:"interval_hours"`
	FixedTimes     []string    `json:"fixed_times"`
	TargetShiftIds []uuid.UUID `json:"target_shift_ids"`
	Enabled        bool        `json:"enabled"`
}

func (q *Queries) UpdateShiftReminder(ctx context.Context, arg UpdateShiftReminderParams) (ShiftReminder, error) {
	row := q.db.QueryRow(ctx, updateShiftReminder,
		arg.ID,
		arg.Label,
		arg.ReminderText,
		arg.FrequencyType,
		arg.IntervalHours,
		arg.FixedTimes,
		arg.TargetShiftIds,
		arg.Enabled,
	)
	var i ShiftReminder
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.ReminderText,
		&i.FrequencyType,
		&i.IntervalHours,
		&i.FixedTimes,
		&i.TargetShiftIds,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
