// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: smtp_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSMTPConfig = `-- name: GetSMTPConfig :one
SELECT host, port, username, password_encrypted, from_address, require_tls
FROM smtp_config
WHERE id = true
`

type GetSMTPConfigRow struct {
	Host              string      `json:"host"`
	Port              int32       `json:"port"`
	Username          pgtype.Text `json:"username"`
	PasswordEncrypted pgtype.Text `json:"password_encrypted"`
	FromAddress       string      `json:"from_address"`
	RequireTls        bool        `json:"require_tls"`
}

// smtp_config es singleton (id BOOLEAN PRIMARY KEY DEFAULT true), siempre hay
// a lo sumo una fila. sqlc.narg permite pgx.ErrNoRows cuando aún no se
// configuró SMTP (setup inicial no completado).
func (q *Queries) GetSMTPConfig(ctx context.Context) (GetSMTPConfigRow, error) {
	row := q.db.QueryRow(ctx, getSMTPConfig)
	var i GetSMTPConfigRow
	err := row.Scan(
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.FromAddress,
		&i.RequireTls,
	)
	return i, err
}

const upsertSMTPConfig = `-- name: UpsertSMTPConfig :exec
INSERT INTO smtp_config (id, host, port, username, password_encrypted, from_address, require_tls)
VALUES (true, $1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
  host = EXCLUDED.host,
  port = EXCLUDED.port,
  username = EXCLUDED.username,
  password_encrypted = EXCLUDED.password_encrypted,
  from_address = EXCLUDED.from_address,
  require_tls = EXCLUDED.require_tls
`

type UpsertSMTPConfigParams struct {
	Host              string      `json:"host"`
	Port              int32       `json:"port"`
	Username          pgtype.Text `json:"username"`
	PasswordEncrypted pgtype.Text `json:"password_encrypted"`
	FromAddress       string      `json:"from_address"`
	RequireTls        bool        `json:"require_tls"`
}

func (q *Queries) UpsertSMTPConfig(ctx context.Context, arg UpsertSMTPConfigParams) error {
	_, err := q.db.Exec(ctx, upsertSMTPConfig,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEncrypted,
		arg.FromAddress,
		arg.RequireTls,
	)
	return err
}
