// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_features.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSystemFeature = `-- name: GetSystemFeature :one
SELECT code, name, description, is_enabled, config_payload, updated_by, updated_at FROM system_features WHERE code = $1
`

func (q *Queries) GetSystemFeature(ctx context.Context, code string) (SystemFeature, error) {
	row := q.db.QueryRow(ctx, getSystemFeature, code)
	var i SystemFeature
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsEnabled,
		&i.ConfigPayload,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemFeatures = `-- name: ListSystemFeatures :many
SELECT code, name, description, is_enabled, config_payload, updated_by, updated_at FROM system_features ORDER BY code
`

func (q *Queries) ListSystemFeatures(ctx context.Context) ([]SystemFeature, error) {
	rows, err := q.db.Query(ctx, listSystemFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemFeature
	for rows.Next() {
		var i SystemFeature
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsEnabled,
			&i.ConfigPayload,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSystemFeature = `-- name: UpdateSystemFeature :one
UPDATE system_features SET
  is_enabled = $2,
  config_payload = COALESCE($4, config_payload),
  updated_by = $3,
  updated_at = now()
WHERE code = $1
RETURNING code, name, description, is_enabled, config_payload, updated_by, updated_at
`

type UpdateSystemFeatureParams struct {
	Code          string      `json:"code"`
	IsEnabled     bool        `json:"is_enabled"`
	UpdatedBy     pgtype.UUID `json:"updated_by"`
	ConfigPayload []byte      `json:"config_payload"`
}

func (q *Queries) UpdateSystemFeature(ctx context.Context, arg UpdateSystemFeatureParams) (SystemFeature, error) {
	row := q.db.QueryRow(ctx, updateSystemFeature,
		arg.Code,
		arg.IsEnabled,
		arg.UpdatedBy,
		arg.ConfigPayload,
	)
	var i SystemFeature
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsEnabled,
		&i.ConfigPayload,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
