// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, contact_id, recipient_type, role_in_team, priority, pool_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, team_id, user_id, contact_id, recipient_type, role_in_team, priority, active, pool_id
`

type AddTeamMemberParams struct {
	TeamID        uuid.UUID     `json:"team_id"`
	UserID        pgtype.UUID   `json:"user_id"`
	ContactID     pgtype.UUID   `json:"contact_id"`
	RecipientType RecipientType `json:"recipient_type"`
	RoleInTeam    TeamRole      `json:"role_in_team"`
	Priority      int32         `json:"priority"`
	PoolID        pgtype.UUID   `json:"pool_id"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember,
		arg.TeamID,
		arg.UserID,
		arg.ContactID,
		arg.RecipientType,
		arg.RoleInTeam,
		arg.Priority,
		arg.PoolID,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.ContactID,
		&i.RecipientType,
		&i.RoleInTeam,
		&i.Priority,
		&i.Active,
		&i.PoolID,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, slug, kind, organization_id, team_group_id, audience)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, organization_id, team_group_id, name, slug, kind, audience, active, deactivated_by_org
`

type CreateTeamParams struct {
	Name           string       `json:"name"`
	Slug           string       `json:"slug"`
	Kind           string       `json:"kind"`
	OrganizationID pgtype.UUID  `json:"organization_id"`
	TeamGroupID    pgtype.UUID  `json:"team_group_id"`
	Audience       TeamAudience `json:"audience"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Slug,
		arg.Kind,
		arg.OrganizationID,
		arg.TeamGroupID,
		arg.Audience,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamGroupID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.Audience,
		&i.Active,
		&i.DeactivatedByOrg,
	)
	return i, err
}

const createTeamGroup = `-- name: CreateTeamGroup :one
INSERT INTO team_groups (name, slug, client_id) VALUES ($1, $2, $3) RETURNING id, name, slug, client_id, active
`

type CreateTeamGroupParams struct {
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) CreateTeamGroup(ctx context.Context, arg CreateTeamGroupParams) (TeamGroup, error) {
	row := q.db.QueryRow(ctx, createTeamGroup, arg.Name, arg.Slug, arg.ClientID)
	var i TeamGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ClientID,
		&i.Active,
	)
	return i, err
}

const deactivateOrganizationTeams = `-- name: DeactivateOrganizationTeams :execrows
UPDATE teams SET active = false, deactivated_by_org = true
WHERE organization_id = $1 AND active AND kind <> 'step'
`

func (q *Queries) DeactivateOrganizationTeams(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateOrganizationTeams, organizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRaciOfTeams = `-- name: DeleteRaciOfTeams :execrows
DELETE FROM raci_assignments WHERE team_id = ANY($1::uuid[])
`

func (q *Queries) DeleteRaciOfTeams(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRaciOfTeams, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStepsOfTeams = `-- name: DeleteStepsOfTeams :many
DELETE FROM escalation_steps WHERE team_id = ANY($1::uuid[]) RETURNING policy_id
`

func (q *Queries) DeleteStepsOfTeams(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteStepsOfTeams, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var policy_id uuid.UUID
		if err := rows.Scan(&policy_id); err != nil {
			return nil, err
		}
		items = append(items, policy_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTeamCycles = `-- name: DeleteTeamCycles :exec
DELETE FROM rotation_cycles WHERE team_id = ANY($1::uuid[])
`

func (q *Queries) DeleteTeamCycles(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeamCycles, ids)
	return err
}

const deleteTeamGuards = `-- name: DeleteTeamGuards :exec
WITH cycles AS (SELECT id FROM rotation_cycles WHERE team_id = ANY($1::uuid[])),
members AS (SELECT id FROM team_members WHERE team_id = ANY($1::uuid[])),
unlink AS (UPDATE work_shifts SET rotation_cycle_id = NULL WHERE rotation_cycle_id IN (SELECT id FROM cycles)),
overrides AS (DELETE FROM rotation_overrides WHERE cycle_id IN (SELECT id FROM cycles)
  OR original_team_member_id IN (SELECT id FROM members) OR replacement_team_member_id IN (SELECT id FROM members)),
slots AS (DELETE FROM rotation_slots WHERE cycle_id IN (SELECT id FROM cycles) OR team_member_id IN (SELECT id FROM members))
SELECT 1
`

// Guardias de esos equipos: reemplazos, turnos y ciclos (los turnos de
// trabajo enlazados quedan sin ciclo).
func (q *Queries) DeleteTeamGuards(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeamGuards, ids)
	return err
}

const deleteTeams = `-- name: DeleteTeams :execrows
DELETE FROM teams WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteTeams(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeams, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTeam = `-- name: GetTeam :one
SELECT id, organization_id, team_group_id, name, slug, kind, audience, active, deactivated_by_org FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamGroupID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.Audience,
		&i.Active,
		&i.DeactivatedByOrg,
	)
	return i, err
}

const listTeamCoverage = `-- name: ListTeamCoverage :many
SELECT tc.team_id, tc.territorial_unit_id, tc.priority, tu.name, tu.code, tu.kind
FROM team_coverage tc JOIN territorial_units tu ON tu.id = tc.territorial_unit_id
WHERE tc.team_id = $1
ORDER BY tc.priority, tu.path
`

type ListTeamCoverageRow struct {
	TeamID            uuid.UUID       `json:"team_id"`
	TerritorialUnitID uuid.UUID       `json:"territorial_unit_id"`
	Priority          int32           `json:"priority"`
	Name              string          `json:"name"`
	Code              string          `json:"code"`
	Kind              TerritorialKind `json:"kind"`
}

func (q *Queries) ListTeamCoverage(ctx context.Context, teamID uuid.UUID) ([]ListTeamCoverageRow, error) {
	rows, err := q.db.Query(ctx, listTeamCoverage, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamCoverageRow
	for rows.Next() {
		var i ListTeamCoverageRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TerritorialUnitID,
			&i.Priority,
			&i.Name,
			&i.Code,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamGroups = `-- name: ListTeamGroups :many
SELECT id, name, slug, client_id, active FROM team_groups
WHERE ($1::uuid IS NULL OR client_id = $1)
  AND ($2::boolean IS NULL OR active = $2)
ORDER BY name
`

type ListTeamGroupsParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Active   pgtype.Bool `json:"active"`
}

func (q *Queries) ListTeamGroups(ctx context.Context, arg ListTeamGroupsParams) ([]TeamGroup, error) {
	rows, err := q.db.Query(ctx, listTeamGroups, arg.ClientID, arg.Active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamGroup
	for rows.Next() {
		var i TeamGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ClientID,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT m.id, m.team_id, m.user_id, m.contact_id, m.recipient_type, m.role_in_team, m.priority, m.active, m.pool_id, COALESCE(u.username, c.name, 'Pool ' || p.name, '')::text AS display_name
FROM team_members m
LEFT JOIN users u ON u.id = m.user_id
LEFT JOIN contacts c ON c.id = m.contact_id
LEFT JOIN escalation_pools p ON p.id = m.pool_id
WHERE m.team_id = $1 AND m.active
ORDER BY m.priority, display_name
`

type ListTeamMembersRow struct {
	ID            uuid.UUID     `json:"id"`
	TeamID        uuid.UUID     `json:"team_id"`
	UserID        pgtype.UUID   `json:"user_id"`
	ContactID     pgtype.UUID   `json:"contact_id"`
	RecipientType RecipientType `json:"recipient_type"`
	RoleInTeam    TeamRole      `json:"role_in_team"`
	Priority      int32         `json:"priority"`
	Active        bool          `json:"active"`
	PoolID        pgtype.UUID   `json:"pool_id"`
	DisplayName   string        `json:"display_name"`
}

// Un miembro es un usuario interno O un contacto del directorio (CHECK
// exactamente uno): se devuelve el nombre de cualquiera de los dos.
func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.ContactID,
			&i.RecipientType,
			&i.RoleInTeam,
			&i.Priority,
			&i.Active,
			&i.PoolID,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.organization_id, t.team_group_id, t.name, t.slug, t.kind, t.audience, t.active, t.deactivated_by_org, o.name AS organization_name, COALESCE(o.active, true) AS organization_active,
  (SELECT count(*) FROM team_members m WHERE m.team_id = t.id AND m.active)::int AS member_count,
  COALESCE((SELECT string_agg(COALESCE(sv.name || ' · ' || so.name, sv.name, a.name, u.name, 'política') || ' #' || st.step_order, ', ' ORDER BY st.step_order)
    FROM escalation_steps st JOIN escalation_policies p ON p.id = st.policy_id
    LEFT JOIN services sv ON sv.id = p.service_id LEFT JOIN organizations so ON so.id = sv.organization_id
    LEFT JOIN assets a ON a.id = p.asset_id LEFT JOIN territorial_units u ON u.id = p.territorial_unit_id
    WHERE st.team_id = t.id), '')::text AS used_in_steps,
  (SELECT count(*) FROM raci_assignments ra WHERE ra.team_id = t.id)::int AS raci_count,
  (SELECT count(*) FROM rotation_slots rs JOIN rotation_cycles rc ON rc.id = rs.cycle_id WHERE rc.team_id = t.id)::int AS guard_count,
  (SELECT count(*) FROM tickets tk WHERE tk.assigned_team_id = t.id)::int AS ticket_count
FROM teams t LEFT JOIN organizations o ON o.id = t.organization_id
WHERE ($1::text IS NULL OR t.kind = $1)
  AND (t.kind <> 'step' OR $1::text = 'step')
  AND ($2::uuid IS NULL OR t.organization_id = $2)
  AND ($3::uuid IS NULL OR t.team_group_id = $3)
  AND ($4::team_audience IS NULL OR t.audience = $4)
  AND ($5::boolean IS NULL OR t.active = $5)
ORDER BY t.name
`

type ListTeamsParams struct {
	Kind           pgtype.Text      `json:"kind"`
	OrganizationID pgtype.UUID      `json:"organization_id"`
	TeamGroupID    pgtype.UUID      `json:"team_group_id"`
	Audience       NullTeamAudience `json:"audience"`
	Active         pgtype.Bool      `json:"active"`
}

type ListTeamsRow struct {
	ID                 uuid.UUID    `json:"id"`
	OrganizationID     pgtype.UUID  `json:"organization_id"`
	TeamGroupID        pgtype.UUID  `json:"team_group_id"`
	Name               string       `json:"name"`
	Slug               string       `json:"slug"`
	Kind               string       `json:"kind"`
	Audience           TeamAudience `json:"audience"`
	Active             bool         `json:"active"`
	DeactivatedByOrg   bool         `json:"deactivated_by_org"`
	OrganizationName   pgtype.Text  `json:"organization_name"`
	OrganizationActive bool         `json:"organization_active"`
	MemberCount        int32        `json:"member_count"`
	UsedInSteps        string       `json:"used_in_steps"`
	RaciCount          int32        `json:"raci_count"`
	GuardCount         int32        `json:"guard_count"`
	TicketCount        int32        `json:"ticket_count"`
}

// Los grupos de un paso de escalamiento (kind 'step', 000030) son parte de
// su política: no se listan salvo que se pidan con kind=step. Cada equipo
// trae qué lo usa, para avisar antes de borrar.
func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams,
		arg.Kind,
		arg.OrganizationID,
		arg.TeamGroupID,
		arg.Audience,
		arg.Active,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsRow
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamGroupID,
			&i.Name,
			&i.Slug,
			&i.Kind,
			&i.Audience,
			&i.Active,
			&i.DeactivatedByOrg,
			&i.OrganizationName,
			&i.OrganizationActive,
			&i.MemberCount,
			&i.UsedInSteps,
			&i.RaciCount,
			&i.GuardCount,
			&i.TicketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateOrganizationTeams = `-- name: ReactivateOrganizationTeams :execrows
UPDATE teams SET active = true, deactivated_by_org = false
WHERE organization_id = $1 AND deactivated_by_org
`

func (q *Queries) ReactivateOrganizationTeams(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, reactivateOrganizationTeams, organizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeTeamCoverage = `-- name: RemoveTeamCoverage :execrows
DELETE FROM team_coverage WHERE team_id = $1 AND territorial_unit_id = $2
`

type RemoveTeamCoverageParams struct {
	TeamID            uuid.UUID `json:"team_id"`
	TerritorialUnitID uuid.UUID `json:"territorial_unit_id"`
}

func (q *Queries) RemoveTeamCoverage(ctx context.Context, arg RemoveTeamCoverageParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamCoverage, arg.TeamID, arg.TerritorialUnitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeTeamMember = `-- name: RemoveTeamMember :execrows
DELETE FROM team_members WHERE id = $1 AND team_id = $2
`

type RemoveTeamMemberParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamMember, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTeamsActive = `-- name: SetTeamsActive :execrows
UPDATE teams SET active = $1, deactivated_by_org = false
WHERE id = ANY($2::uuid[]) AND kind <> 'step'
`

type SetTeamsActiveParams struct {
	Active bool        `json:"active"`
	Ids    []uuid.UUID `json:"ids"`
}

// Activar o desactivar a mano anula lo que hizo la organización.
func (q *Queries) SetTeamsActive(ctx context.Context, arg SetTeamsActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTeamsActive, arg.Active, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unassignTeamTickets = `-- name: UnassignTeamTickets :execrows

UPDATE tickets SET assigned_team_id = NULL, updated_at = now() WHERE assigned_team_id = ANY($1::uuid[])
`

// Borrado en cascada (decisión del dueño 2026-10-07): todo lo que cuelga del
// equipo se va, menos los contactos del Directorio; los tickets quedan sin
// equipo asignado. Se ejecutan en este orden dentro de una transacción.
func (q *Queries) UnassignTeamTickets(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, unassignTeamTickets, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET
  name = COALESCE($2, name),
  kind = COALESCE($3, kind),
  organization_id = COALESCE($4, organization_id),
  team_group_id = COALESCE($5, team_group_id),
  audience = COALESCE($6, audience),
  active = COALESCE($7, active)
WHERE id = $1
RETURNING id, organization_id, team_group_id, name, slug, kind, audience, active, deactivated_by_org
`

type UpdateTeamParams struct {
	ID             uuid.UUID        `json:"id"`
	Name           pgtype.Text      `json:"name"`
	Kind           pgtype.Text      `json:"kind"`
	OrganizationID pgtype.UUID      `json:"organization_id"`
	TeamGroupID    pgtype.UUID      `json:"team_group_id"`
	Audience       NullTeamAudience `json:"audience"`
	Active         pgtype.Bool      `json:"active"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.OrganizationID,
		arg.TeamGroupID,
		arg.Audience,
		arg.Active,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamGroupID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.Audience,
		&i.Active,
		&i.DeactivatedByOrg,
	)
	return i, err
}

const upsertTeamCoverage = `-- name: UpsertTeamCoverage :one
INSERT INTO team_coverage (team_id, territorial_unit_id, priority) VALUES ($1, $2, $3)
ON CONFLICT (team_id, territorial_unit_id) DO UPDATE SET priority = EXCLUDED.priority
RETURNING team_id, territorial_unit_id, priority
`

type UpsertTeamCoverageParams struct {
	TeamID            uuid.UUID `json:"team_id"`
	TerritorialUnitID uuid.UUID `json:"territorial_unit_id"`
	Priority          int32     `json:"priority"`
}

func (q *Queries) UpsertTeamCoverage(ctx context.Context, arg UpsertTeamCoverageParams) (TeamCoverage, error) {
	row := q.db.QueryRow(ctx, upsertTeamCoverage, arg.TeamID, arg.TerritorialUnitID, arg.Priority)
	var i TeamCoverage
	err := row.Scan(&i.TeamID, &i.TerritorialUnitID, &i.Priority)
	return i, err
}
