// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, contact_id, recipient_type, role_in_team, priority)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, team_id, user_id, contact_id, recipient_type, role_in_team, priority, active
`

type AddTeamMemberParams struct {
	TeamID        uuid.UUID     `json:"team_id"`
	UserID        pgtype.UUID   `json:"user_id"`
	ContactID     pgtype.UUID   `json:"contact_id"`
	RecipientType RecipientType `json:"recipient_type"`
	RoleInTeam    TeamRole      `json:"role_in_team"`
	Priority      int32         `json:"priority"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember,
		arg.TeamID,
		arg.UserID,
		arg.ContactID,
		arg.RecipientType,
		arg.RoleInTeam,
		arg.Priority,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.ContactID,
		&i.RecipientType,
		&i.RoleInTeam,
		&i.Priority,
		&i.Active,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, slug, kind, organization_id, team_group_id, audience)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, organization_id, team_group_id, name, slug, kind, audience, active
`

type CreateTeamParams struct {
	Name           string       `json:"name"`
	Slug           string       `json:"slug"`
	Kind           string       `json:"kind"`
	OrganizationID pgtype.UUID  `json:"organization_id"`
	TeamGroupID    pgtype.UUID  `json:"team_group_id"`
	Audience       TeamAudience `json:"audience"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Slug,
		arg.Kind,
		arg.OrganizationID,
		arg.TeamGroupID,
		arg.Audience,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamGroupID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.Audience,
		&i.Active,
	)
	return i, err
}

const createTeamGroup = `-- name: CreateTeamGroup :one
INSERT INTO team_groups (name, slug, client_id) VALUES ($1, $2, $3) RETURNING id, name, slug, client_id, active
`

type CreateTeamGroupParams struct {
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) CreateTeamGroup(ctx context.Context, arg CreateTeamGroupParams) (TeamGroup, error) {
	row := q.db.QueryRow(ctx, createTeamGroup, arg.Name, arg.Slug, arg.ClientID)
	var i TeamGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ClientID,
		&i.Active,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, organization_id, team_group_id, name, slug, kind, audience, active FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamGroupID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.Audience,
		&i.Active,
	)
	return i, err
}

const listTeamCoverage = `-- name: ListTeamCoverage :many
SELECT tc.team_id, tc.territorial_unit_id, tc.priority, tu.name, tu.code, tu.kind
FROM team_coverage tc JOIN territorial_units tu ON tu.id = tc.territorial_unit_id
WHERE tc.team_id = $1
ORDER BY tc.priority, tu.path
`

type ListTeamCoverageRow struct {
	TeamID            uuid.UUID       `json:"team_id"`
	TerritorialUnitID uuid.UUID       `json:"territorial_unit_id"`
	Priority          int32           `json:"priority"`
	Name              string          `json:"name"`
	Code              string          `json:"code"`
	Kind              TerritorialKind `json:"kind"`
}

func (q *Queries) ListTeamCoverage(ctx context.Context, teamID uuid.UUID) ([]ListTeamCoverageRow, error) {
	rows, err := q.db.Query(ctx, listTeamCoverage, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamCoverageRow
	for rows.Next() {
		var i ListTeamCoverageRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TerritorialUnitID,
			&i.Priority,
			&i.Name,
			&i.Code,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamGroups = `-- name: ListTeamGroups :many
SELECT id, name, slug, client_id, active FROM team_groups
WHERE ($1::uuid IS NULL OR client_id = $1)
  AND ($2::boolean IS NULL OR active = $2)
ORDER BY name
`

type ListTeamGroupsParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Active   pgtype.Bool `json:"active"`
}

func (q *Queries) ListTeamGroups(ctx context.Context, arg ListTeamGroupsParams) ([]TeamGroup, error) {
	rows, err := q.db.Query(ctx, listTeamGroups, arg.ClientID, arg.Active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamGroup
	for rows.Next() {
		var i TeamGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ClientID,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT m.id, m.team_id, m.user_id, m.contact_id, m.recipient_type, m.role_in_team, m.priority, m.active, COALESCE(u.username, c.name, '')::text AS display_name
FROM team_members m
LEFT JOIN users u ON u.id = m.user_id
LEFT JOIN contacts c ON c.id = m.contact_id
WHERE m.team_id = $1 AND m.active
ORDER BY m.priority, display_name
`

type ListTeamMembersRow struct {
	ID            uuid.UUID     `json:"id"`
	TeamID        uuid.UUID     `json:"team_id"`
	UserID        pgtype.UUID   `json:"user_id"`
	ContactID     pgtype.UUID   `json:"contact_id"`
	RecipientType RecipientType `json:"recipient_type"`
	RoleInTeam    TeamRole      `json:"role_in_team"`
	Priority      int32         `json:"priority"`
	Active        bool          `json:"active"`
	DisplayName   string        `json:"display_name"`
}

// Un miembro es un usuario interno O un contacto del directorio (CHECK
// exactamente uno): se devuelve el nombre de cualquiera de los dos.
func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.ContactID,
			&i.RecipientType,
			&i.RoleInTeam,
			&i.Priority,
			&i.Active,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.organization_id, t.team_group_id, t.name, t.slug, t.kind, t.audience, t.active, o.name AS organization_name,
  (SELECT count(*) FROM team_members m WHERE m.team_id = t.id AND m.active)::int AS member_count
FROM teams t LEFT JOIN organizations o ON o.id = t.organization_id
WHERE ($1::text IS NULL OR t.kind = $1)
  AND ($2::uuid IS NULL OR t.organization_id = $2)
  AND ($3::uuid IS NULL OR t.team_group_id = $3)
  AND ($4::team_audience IS NULL OR t.audience = $4)
  AND ($5::boolean IS NULL OR t.active = $5)
ORDER BY t.name
`

type ListTeamsParams struct {
	Kind           pgtype.Text      `json:"kind"`
	OrganizationID pgtype.UUID      `json:"organization_id"`
	TeamGroupID    pgtype.UUID      `json:"team_group_id"`
	Audience       NullTeamAudience `json:"audience"`
	Active         pgtype.Bool      `json:"active"`
}

type ListTeamsRow struct {
	ID               uuid.UUID    `json:"id"`
	OrganizationID   pgtype.UUID  `json:"organization_id"`
	TeamGroupID      pgtype.UUID  `json:"team_group_id"`
	Name             string       `json:"name"`
	Slug             string       `json:"slug"`
	Kind             string       `json:"kind"`
	Audience         TeamAudience `json:"audience"`
	Active           bool         `json:"active"`
	OrganizationName pgtype.Text  `json:"organization_name"`
	MemberCount      int32        `json:"member_count"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams,
		arg.Kind,
		arg.OrganizationID,
		arg.TeamGroupID,
		arg.Audience,
		arg.Active,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsRow
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamGroupID,
			&i.Name,
			&i.Slug,
			&i.Kind,
			&i.Audience,
			&i.Active,
			&i.OrganizationName,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamCoverage = `-- name: RemoveTeamCoverage :execrows
DELETE FROM team_coverage WHERE team_id = $1 AND territorial_unit_id = $2
`

type RemoveTeamCoverageParams struct {
	TeamID            uuid.UUID `json:"team_id"`
	TerritorialUnitID uuid.UUID `json:"territorial_unit_id"`
}

func (q *Queries) RemoveTeamCoverage(ctx context.Context, arg RemoveTeamCoverageParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamCoverage, arg.TeamID, arg.TerritorialUnitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeTeamMember = `-- name: RemoveTeamMember :execrows
DELETE FROM team_members WHERE id = $1 AND team_id = $2
`

type RemoveTeamMemberParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamMember, arg.ID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET
  name = COALESCE($2, name),
  kind = COALESCE($3, kind),
  organization_id = COALESCE($4, organization_id),
  team_group_id = COALESCE($5, team_group_id),
  audience = COALESCE($6, audience),
  active = COALESCE($7, active)
WHERE id = $1
RETURNING id, organization_id, team_group_id, name, slug, kind, audience, active
`

type UpdateTeamParams struct {
	ID             uuid.UUID        `json:"id"`
	Name           pgtype.Text      `json:"name"`
	Kind           pgtype.Text      `json:"kind"`
	OrganizationID pgtype.UUID      `json:"organization_id"`
	TeamGroupID    pgtype.UUID      `json:"team_group_id"`
	Audience       NullTeamAudience `json:"audience"`
	Active         pgtype.Bool      `json:"active"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.OrganizationID,
		arg.TeamGroupID,
		arg.Audience,
		arg.Active,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamGroupID,
		&i.Name,
		&i.Slug,
		&i.Kind,
		&i.Audience,
		&i.Active,
	)
	return i, err
}

const upsertTeamCoverage = `-- name: UpsertTeamCoverage :one
INSERT INTO team_coverage (team_id, territorial_unit_id, priority) VALUES ($1, $2, $3)
ON CONFLICT (team_id, territorial_unit_id) DO UPDATE SET priority = EXCLUDED.priority
RETURNING team_id, territorial_unit_id, priority
`

type UpsertTeamCoverageParams struct {
	TeamID            uuid.UUID `json:"team_id"`
	TerritorialUnitID uuid.UUID `json:"territorial_unit_id"`
	Priority          int32     `json:"priority"`
}

func (q *Queries) UpsertTeamCoverage(ctx context.Context, arg UpsertTeamCoverageParams) (TeamCoverage, error) {
	row := q.db.QueryRow(ctx, upsertTeamCoverage, arg.TeamID, arg.TerritorialUnitID, arg.Priority)
	var i TeamCoverage
	err := row.Scan(&i.TeamID, &i.TerritorialUnitID, &i.Priority)
	return i, err
}
