// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTickets = `-- name: CountTickets :one
SELECT count(*) FROM tickets t
WHERE ($1::ticket_type IS NULL OR t.ticket_type = $1::ticket_type)
  AND ($2::entry_scope IS NULL OR t.scope = $2::entry_scope)
  AND ($3::ticket_status IS NULL OR t.status = $3::ticket_status)
  AND ($4::uuid IS NULL OR t.assigned_team_id = $4::uuid)
  AND ($5::uuid IS NULL OR t.client_id = $5::uuid)
  AND ($6::text IS NULL OR t.ticket_number ILIKE '%' || $6::text || '%' OR t.title ILIKE '%' || $6::text || '%')
`

type CountTicketsParams struct {
	TicketType     NullTicketType   `json:"ticket_type"`
	Scope          NullEntryScope   `json:"scope"`
	Status         NullTicketStatus `json:"status"`
	AssignedTeamID pgtype.UUID      `json:"assigned_team_id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	Q              pgtype.Text      `json:"q"`
}

func (q *Queries) CountTickets(ctx context.Context, arg CountTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTickets,
		arg.TicketType,
		arg.Scope,
		arg.Status,
		arg.AssignedTeamID,
		arg.ClientID,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (ticket_number, ticket_type, scope, client_id, asset_id, service_id, assigned_team_id, assigned_user_id, status, impact, urgency, priority, title, description, sla_response_due_at, sla_resolution_due_at, public_tracking_token, created_by)
VALUES ($1, $2, $3, $4, $15, $16, $5, $17, 'new', $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, ticket_number, ticket_type, scope, client_id, asset_id, service_id, assigned_team_id, assigned_user_id, assigned_contact_id, status, impact, urgency, priority, title, description, sla_response_due_at, sla_resolution_due_at, sla_on_hold_since, sla_paused_seconds, first_responded_at, resolved_at, closed_at, reopened_count, reopened_at, public_tracking_token, public_tracking_enabled, public_tracking_pin, created_by, created_at, updated_at
`

type CreateTicketParams struct {
	TicketNumber        string             `json:"ticket_number"`
	TicketType          TicketType         `json:"ticket_type"`
	Scope               EntryScope         `json:"scope"`
	ClientID            uuid.UUID          `json:"client_id"`
	AssignedTeamID      pgtype.UUID        `json:"assigned_team_id"`
	Impact              ItilImpact         `json:"impact"`
	Urgency             ItilUrgency        `json:"urgency"`
	Priority            ItilPriority       `json:"priority"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	SlaResponseDueAt    pgtype.Timestamptz `json:"sla_response_due_at"`
	SlaResolutionDueAt  pgtype.Timestamptz `json:"sla_resolution_due_at"`
	PublicTrackingToken pgtype.Text        `json:"public_tracking_token"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	AssetID             pgtype.UUID        `json:"asset_id"`
	ServiceID           pgtype.UUID        `json:"service_id"`
	AssignedUserID      pgtype.UUID        `json:"assigned_user_id"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.TicketNumber,
		arg.TicketType,
		arg.Scope,
		arg.ClientID,
		arg.AssignedTeamID,
		arg.Impact,
		arg.Urgency,
		arg.Priority,
		arg.Title,
		arg.Description,
		arg.SlaResponseDueAt,
		arg.SlaResolutionDueAt,
		arg.PublicTrackingToken,
		arg.CreatedBy,
		arg.AssetID,
		arg.ServiceID,
		arg.AssignedUserID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketNumber,
		&i.TicketType,
		&i.Scope,
		&i.ClientID,
		&i.AssetID,
		&i.ServiceID,
		&i.AssignedTeamID,
		&i.AssignedUserID,
		&i.AssignedContactID,
		&i.Status,
		&i.Impact,
		&i.Urgency,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.SlaResponseDueAt,
		&i.SlaResolutionDueAt,
		&i.SlaOnHoldSince,
		&i.SlaPausedSeconds,
		&i.FirstRespondedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.ReopenedCount,
		&i.ReopenedAt,
		&i.PublicTrackingToken,
		&i.PublicTrackingEnabled,
		&i.PublicTrackingPin,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketComment = `-- name: CreateTicketComment :one
INSERT INTO ticket_comments (ticket_id, user_id, author_name, content, is_public)
VALUES ($1, $2, $3, $4, $5) RETURNING id, ticket_id, user_id, author_name, content, is_public, created_at
`

type CreateTicketCommentParams struct {
	TicketID   uuid.UUID   `json:"ticket_id"`
	UserID     pgtype.UUID `json:"user_id"`
	AuthorName string      `json:"author_name"`
	Content    string      `json:"content"`
	IsPublic   bool        `json:"is_public"`
}

func (q *Queries) CreateTicketComment(ctx context.Context, arg CreateTicketCommentParams) (TicketComment, error) {
	row := q.db.QueryRow(ctx, createTicketComment,
		arg.TicketID,
		arg.UserID,
		arg.AuthorName,
		arg.Content,
		arg.IsPublic,
	)
	var i TicketComment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.AuthorName,
		&i.Content,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const createTicketTask = `-- name: CreateTicketTask :one
INSERT INTO ticket_tasks (ticket_id, user_id, content, time_spent_seconds, is_public, performed_at)
VALUES ($1, $2, $3, $4, $5, COALESCE($6, now())) RETURNING id, ticket_id, user_id, content, time_spent_seconds, is_public, performed_at, created_at
`

type CreateTicketTaskParams struct {
	TicketID         uuid.UUID   `json:"ticket_id"`
	UserID           uuid.UUID   `json:"user_id"`
	Content          string      `json:"content"`
	TimeSpentSeconds int32       `json:"time_spent_seconds"`
	IsPublic         bool        `json:"is_public"`
	PerformedAt      interface{} `json:"performed_at"`
}

func (q *Queries) CreateTicketTask(ctx context.Context, arg CreateTicketTaskParams) (TicketTask, error) {
	row := q.db.QueryRow(ctx, createTicketTask,
		arg.TicketID,
		arg.UserID,
		arg.Content,
		arg.TimeSpentSeconds,
		arg.IsPublic,
		arg.PerformedAt,
	)
	var i TicketTask
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.Content,
		&i.TimeSpentSeconds,
		&i.IsPublic,
		&i.PerformedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicTicket = `-- name: GetPublicTicket :one
SELECT id, ticket_number, ticket_type, scope, client_id, asset_id, service_id, assigned_team_id, assigned_user_id, assigned_contact_id, status, impact, urgency, priority, title, description, sla_response_due_at, sla_resolution_due_at, sla_on_hold_since, sla_paused_seconds, first_responded_at, resolved_at, closed_at, reopened_count, reopened_at, public_tracking_token, public_tracking_enabled, public_tracking_pin, created_by, created_at, updated_at FROM tickets WHERE public_tracking_token = $1 AND public_tracking_enabled = true
`

func (q *Queries) GetPublicTicket(ctx context.Context, publicTrackingToken pgtype.Text) (Ticket, error) {
	row := q.db.QueryRow(ctx, getPublicTicket, publicTrackingToken)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketNumber,
		&i.TicketType,
		&i.Scope,
		&i.ClientID,
		&i.AssetID,
		&i.ServiceID,
		&i.AssignedTeamID,
		&i.AssignedUserID,
		&i.AssignedContactID,
		&i.Status,
		&i.Impact,
		&i.Urgency,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.SlaResponseDueAt,
		&i.SlaResolutionDueAt,
		&i.SlaOnHoldSince,
		&i.SlaPausedSeconds,
		&i.FirstRespondedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.ReopenedCount,
		&i.ReopenedAt,
		&i.PublicTrackingToken,
		&i.PublicTrackingEnabled,
		&i.PublicTrackingPin,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, ticket_number, ticket_type, scope, client_id, asset_id, service_id, assigned_team_id, assigned_user_id, assigned_contact_id, status, impact, urgency, priority, title, description, sla_response_due_at, sla_resolution_due_at, sla_on_hold_since, sla_paused_seconds, first_responded_at, resolved_at, closed_at, reopened_count, reopened_at, public_tracking_token, public_tracking_enabled, public_tracking_pin, created_by, created_at, updated_at FROM tickets WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketNumber,
		&i.TicketType,
		&i.Scope,
		&i.ClientID,
		&i.AssetID,
		&i.ServiceID,
		&i.AssignedTeamID,
		&i.AssignedUserID,
		&i.AssignedContactID,
		&i.Status,
		&i.Impact,
		&i.Urgency,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.SlaResponseDueAt,
		&i.SlaResolutionDueAt,
		&i.SlaOnHoldSince,
		&i.SlaPausedSeconds,
		&i.FirstRespondedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.ReopenedCount,
		&i.ReopenedAt,
		&i.PublicTrackingToken,
		&i.PublicTrackingEnabled,
		&i.PublicTrackingPin,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByNumber = `-- name: GetTicketByNumber :one
SELECT id, ticket_number, ticket_type, scope, client_id, asset_id, service_id, assigned_team_id, assigned_user_id, assigned_contact_id, status, impact, urgency, priority, title, description, sla_response_due_at, sla_resolution_due_at, sla_on_hold_since, sla_paused_seconds, first_responded_at, resolved_at, closed_at, reopened_count, reopened_at, public_tracking_token, public_tracking_enabled, public_tracking_pin, created_by, created_at, updated_at FROM tickets WHERE ticket_number = $1
`

func (q *Queries) GetTicketByNumber(ctx context.Context, ticketNumber string) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByNumber, ticketNumber)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketNumber,
		&i.TicketType,
		&i.Scope,
		&i.ClientID,
		&i.AssetID,
		&i.ServiceID,
		&i.AssignedTeamID,
		&i.AssignedUserID,
		&i.AssignedContactID,
		&i.Status,
		&i.Impact,
		&i.Urgency,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.SlaResponseDueAt,
		&i.SlaResolutionDueAt,
		&i.SlaOnHoldSince,
		&i.SlaPausedSeconds,
		&i.FirstRespondedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.ReopenedCount,
		&i.ReopenedAt,
		&i.PublicTrackingToken,
		&i.PublicTrackingEnabled,
		&i.PublicTrackingPin,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketTask = `-- name: GetTicketTask :one
SELECT id, ticket_id, user_id, content, time_spent_seconds, is_public, performed_at, created_at FROM ticket_tasks WHERE id = $1
`

func (q *Queries) GetTicketTask(ctx context.Context, id uuid.UUID) (TicketTask, error) {
	row := q.db.QueryRow(ctx, getTicketTask, id)
	var i TicketTask
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.Content,
		&i.TimeSpentSeconds,
		&i.IsPublic,
		&i.PerformedAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkEntryToTicket = `-- name: LinkEntryToTicket :one
UPDATE entries SET ticket_id = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, entry_type, scope, content, tags, service_id, asset_id, work_shift_id, glpi_ticket_id, glpi_linked_at, ticket_id, image_url, image_hash, image_size_bytes, created_at, updated_at
`

type LinkEntryToTicketParams struct {
	ID       uuid.UUID   `json:"id"`
	TicketID pgtype.UUID `json:"ticket_id"`
}

func (q *Queries) LinkEntryToTicket(ctx context.Context, arg LinkEntryToTicketParams) (Entry, error) {
	row := q.db.QueryRow(ctx, linkEntryToTicket, arg.ID, arg.TicketID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryType,
		&i.Scope,
		&i.Content,
		&i.Tags,
		&i.ServiceID,
		&i.AssetID,
		&i.WorkShiftID,
		&i.GlpiTicketID,
		&i.GlpiLinkedAt,
		&i.TicketID,
		&i.ImageUrl,
		&i.ImageHash,
		&i.ImageSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicTicketComments = `-- name: ListPublicTicketComments :many
SELECT id, ticket_id, user_id, author_name, content, is_public, created_at FROM ticket_comments WHERE ticket_id = $1 AND is_public = true ORDER BY created_at ASC
`

func (q *Queries) ListPublicTicketComments(ctx context.Context, ticketID uuid.UUID) ([]TicketComment, error) {
	rows, err := q.db.Query(ctx, listPublicTicketComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketComment
	for rows.Next() {
		var i TicketComment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.UserID,
			&i.AuthorName,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketComments = `-- name: ListTicketComments :many
SELECT id, ticket_id, user_id, author_name, content, is_public, created_at FROM ticket_comments WHERE ticket_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTicketComments(ctx context.Context, ticketID uuid.UUID) ([]TicketComment, error) {
	rows, err := q.db.Query(ctx, listTicketComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketComment
	for rows.Next() {
		var i TicketComment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.UserID,
			&i.AuthorName,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketEntries = `-- name: ListTicketEntries :many
SELECT id, user_id, entry_type, scope, content, tags, service_id, asset_id, work_shift_id, glpi_ticket_id, glpi_linked_at, ticket_id, image_url, image_hash, image_size_bytes, created_at, updated_at FROM entries WHERE ticket_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTicketEntries(ctx context.Context, ticketID pgtype.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listTicketEntries, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryType,
			&i.Scope,
			&i.Content,
			&i.Tags,
			&i.ServiceID,
			&i.AssetID,
			&i.WorkShiftID,
			&i.GlpiTicketID,
			&i.GlpiLinkedAt,
			&i.TicketID,
			&i.ImageUrl,
			&i.ImageHash,
			&i.ImageSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTasks = `-- name: ListTicketTasks :many
SELECT id, ticket_id, user_id, content, time_spent_seconds, is_public, performed_at, created_at FROM ticket_tasks WHERE ticket_id = $1 ORDER BY performed_at ASC
`

func (q *Queries) ListTicketTasks(ctx context.Context, ticketID uuid.UUID) ([]TicketTask, error) {
	rows, err := q.db.Query(ctx, listTicketTasks, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketTask
	for rows.Next() {
		var i TicketTask
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.UserID,
			&i.Content,
			&i.TimeSpentSeconds,
			&i.IsPublic,
			&i.PerformedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT t.id, t.ticket_number, t.ticket_type, t.scope, t.client_id, t.asset_id, t.service_id, t.assigned_team_id, t.assigned_user_id, t.assigned_contact_id, t.status, t.impact, t.urgency, t.priority, t.title, t.description, t.sla_response_due_at, t.sla_resolution_due_at, t.sla_on_hold_since, t.sla_paused_seconds, t.first_responded_at, t.resolved_at, t.closed_at, t.reopened_count, t.reopened_at, t.public_tracking_token, t.public_tracking_enabled, t.public_tracking_pin, t.created_by, t.created_at, t.updated_at
FROM tickets t
WHERE ($1::ticket_type IS NULL OR t.ticket_type = $1::ticket_type)
  AND ($2::entry_scope IS NULL OR t.scope = $2::entry_scope)
  AND ($3::ticket_status IS NULL OR t.status = $3::ticket_status)
  AND ($4::uuid IS NULL OR t.assigned_team_id = $4::uuid)
  AND ($5::uuid IS NULL OR t.client_id = $5::uuid)
  AND ($6::text IS NULL OR t.ticket_number ILIKE '%' || $6::text || '%' OR t.title ILIKE '%' || $6::text || '%')
ORDER BY t.updated_at DESC
LIMIT $8 OFFSET $7
`

type ListTicketsParams struct {
	TicketType     NullTicketType   `json:"ticket_type"`
	Scope          NullEntryScope   `json:"scope"`
	Status         NullTicketStatus `json:"status"`
	AssignedTeamID pgtype.UUID      `json:"assigned_team_id"`
	ClientID       pgtype.UUID      `json:"client_id"`
	Q              pgtype.Text      `json:"q"`
	PageOffset     int32            `json:"page_offset"`
	PageSize       int32            `json:"page_size"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets,
		arg.TicketType,
		arg.Scope,
		arg.Status,
		arg.AssignedTeamID,
		arg.ClientID,
		arg.Q,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TicketNumber,
			&i.TicketType,
			&i.Scope,
			&i.ClientID,
			&i.AssetID,
			&i.ServiceID,
			&i.AssignedTeamID,
			&i.AssignedUserID,
			&i.AssignedContactID,
			&i.Status,
			&i.Impact,
			&i.Urgency,
			&i.Priority,
			&i.Title,
			&i.Description,
			&i.SlaResponseDueAt,
			&i.SlaResolutionDueAt,
			&i.SlaOnHoldSince,
			&i.SlaPausedSeconds,
			&i.FirstRespondedAt,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.ReopenedCount,
			&i.ReopenedAt,
			&i.PublicTrackingToken,
			&i.PublicTrackingEnabled,
			&i.PublicTrackingPin,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTicketTaskTime = `-- name: SumTicketTaskTime :one
SELECT COALESCE(sum(time_spent_seconds), 0)::bigint FROM ticket_tasks WHERE ticket_id = $1
`

func (q *Queries) SumTicketTaskTime(ctx context.Context, ticketID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumTicketTaskTime, ticketID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets SET
  status = COALESCE($2, status),
  assigned_team_id = COALESCE($3, assigned_team_id),
  assigned_user_id = COALESCE($4, assigned_user_id),
  assigned_contact_id = COALESCE($5, assigned_contact_id),
  impact = COALESCE($6, impact),
  urgency = COALESCE($7, urgency),
  priority = COALESCE($8, priority),
  sla_on_hold_since = $9,
  sla_paused_seconds = COALESCE($10, sla_paused_seconds),
  first_responded_at = COALESCE($11, first_responded_at),
  resolved_at = $12,
  closed_at = $13,
  reopened_count = COALESCE($14, reopened_count),
  reopened_at = $15,
  updated_at = now()
WHERE id = $1
RETURNING id, ticket_number, ticket_type, scope, client_id, asset_id, service_id, assigned_team_id, assigned_user_id, assigned_contact_id, status, impact, urgency, priority, title, description, sla_response_due_at, sla_resolution_due_at, sla_on_hold_since, sla_paused_seconds, first_responded_at, resolved_at, closed_at, reopened_count, reopened_at, public_tracking_token, public_tracking_enabled, public_tracking_pin, created_by, created_at, updated_at
`

type UpdateTicketParams struct {
	ID                uuid.UUID          `json:"id"`
	Status            NullTicketStatus   `json:"status"`
	AssignedTeamID    pgtype.UUID        `json:"assigned_team_id"`
	AssignedUserID    pgtype.UUID        `json:"assigned_user_id"`
	AssignedContactID pgtype.UUID        `json:"assigned_contact_id"`
	Impact            NullItilImpact     `json:"impact"`
	Urgency           NullItilUrgency    `json:"urgency"`
	Priority          NullItilPriority   `json:"priority"`
	SlaOnHoldSince    pgtype.Timestamptz `json:"sla_on_hold_since"`
	SlaPausedSeconds  pgtype.Int4        `json:"sla_paused_seconds"`
	FirstRespondedAt  pgtype.Timestamptz `json:"first_responded_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	ReopenedCount     pgtype.Int4        `json:"reopened_count"`
	ReopenedAt        pgtype.Timestamptz `json:"reopened_at"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Status,
		arg.AssignedTeamID,
		arg.AssignedUserID,
		arg.AssignedContactID,
		arg.Impact,
		arg.Urgency,
		arg.Priority,
		arg.SlaOnHoldSince,
		arg.SlaPausedSeconds,
		arg.FirstRespondedAt,
		arg.ResolvedAt,
		arg.ClosedAt,
		arg.ReopenedCount,
		arg.ReopenedAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketNumber,
		&i.TicketType,
		&i.Scope,
		&i.ClientID,
		&i.AssetID,
		&i.ServiceID,
		&i.AssignedTeamID,
		&i.AssignedUserID,
		&i.AssignedContactID,
		&i.Status,
		&i.Impact,
		&i.Urgency,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.SlaResponseDueAt,
		&i.SlaResolutionDueAt,
		&i.SlaOnHoldSince,
		&i.SlaPausedSeconds,
		&i.FirstRespondedAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.ReopenedCount,
		&i.ReopenedAt,
		&i.PublicTrackingToken,
		&i.PublicTrackingEnabled,
		&i.PublicTrackingPin,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketTask = `-- name: UpdateTicketTask :one
UPDATE ticket_tasks SET content = COALESCE($3, content), time_spent_seconds = COALESCE($4, time_spent_seconds)
WHERE id = $1 AND ticket_id = $2 RETURNING id, ticket_id, user_id, content, time_spent_seconds, is_public, performed_at, created_at
`

type UpdateTicketTaskParams struct {
	ID               uuid.UUID   `json:"id"`
	TicketID         uuid.UUID   `json:"ticket_id"`
	Content          pgtype.Text `json:"content"`
	TimeSpentSeconds pgtype.Int4 `json:"time_spent_seconds"`
}

func (q *Queries) UpdateTicketTask(ctx context.Context, arg UpdateTicketTaskParams) (TicketTask, error) {
	row := q.db.QueryRow(ctx, updateTicketTask,
		arg.ID,
		arg.TicketID,
		arg.Content,
		arg.TimeSpentSeconds,
	)
	var i TicketTask
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.Content,
		&i.TimeSpentSeconds,
		&i.IsPublic,
		&i.PerformedAt,
		&i.CreatedAt,
	)
	return i, err
}
