// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_shift_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveWorkShiftMembers = `-- name: CountActiveWorkShiftMembers :one
SELECT count(*)::int FROM work_shift_members WHERE work_shift_id = $1 AND active
`

func (q *Queries) CountActiveWorkShiftMembers(ctx context.Context, workShiftID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveWorkShiftMembers, workShiftID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWorkShiftMember = `-- name: DeleteWorkShiftMember :execrows
DELETE FROM work_shift_members WHERE work_shift_id = $1 AND user_id = $2
`

type DeleteWorkShiftMemberParams struct {
	WorkShiftID uuid.UUID `json:"work_shift_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkShiftMember(ctx context.Context, arg DeleteWorkShiftMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkShiftMember, arg.WorkShiftID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listShiftReminderMemberEmails = `-- name: ListShiftReminderMemberEmails :many
SELECT DISTINCT lower(trim(u.email))::text AS email
FROM work_shift_members m JOIN users u ON u.id = m.user_id
WHERE m.work_shift_id = $1 AND m.active AND u.active
  AND $2::int = ANY(m.weekdays)
  AND (m.valid_from IS NULL OR m.valid_from <= $3::date)
  AND (m.valid_to IS NULL OR m.valid_to >= $3::date)
  AND u.email IS NOT NULL AND trim(u.email) <> ''
ORDER BY 1
`

type ListShiftReminderMemberEmailsParams struct {
	WorkShiftID uuid.UUID   `json:"work_shift_id"`
	Weekday     int32       `json:"weekday"`
	Day         pgtype.Date `json:"day"`
}

// Recordatorios: las personas activas del turno que trabajan ese día (y
// dentro de su vigencia), con correo — como shiftReminderScheduler del legacy.
func (q *Queries) ListShiftReminderMemberEmails(ctx context.Context, arg ListShiftReminderMemberEmailsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listShiftReminderMemberEmails, arg.WorkShiftID, arg.Weekday, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkShiftMembers = `-- name: ListWorkShiftMembers :many

SELECT m.id, m.work_shift_id, m.user_id, m.weekdays, m.active, m.valid_from, m.valid_to, m.created_at, u.username, COALESCE(NULLIF(trim(u.full_name), ''), u.username)::text AS display_name, u.active AS user_active
FROM work_shift_members m JOIN users u ON u.id = m.user_id
WHERE m.work_shift_id = $1
ORDER BY display_name
`

type ListWorkShiftMembersRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkShiftID uuid.UUID          `json:"work_shift_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Weekdays    []int32            `json:"weekdays"`
	Active      bool               `json:"active"`
	ValidFrom   pgtype.Date        `json:"valid_from"`
	ValidTo     pgtype.Date        `json:"valid_to"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	UserActive  bool               `json:"user_active"`
}

// ===== Personas del turno (WorkShiftAssignment del legacy) =====
func (q *Queries) ListWorkShiftMembers(ctx context.Context, workShiftID uuid.UUID) ([]ListWorkShiftMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkShiftMembers, workShiftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkShiftMembersRow
	for rows.Next() {
		var i ListWorkShiftMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkShiftID,
			&i.UserID,
			&i.Weekdays,
			&i.Active,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.UserActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkShiftMember = `-- name: UpsertWorkShiftMember :one
INSERT INTO work_shift_members (work_shift_id, user_id, weekdays, active)
VALUES ($1, $2, $3, true)
ON CONFLICT (work_shift_id, user_id) DO UPDATE SET weekdays = EXCLUDED.weekdays, active = true
RETURNING id, work_shift_id, user_id, weekdays, active, valid_from, valid_to, created_at
`

type UpsertWorkShiftMemberParams struct {
	WorkShiftID uuid.UUID `json:"work_shift_id"`
	UserID      uuid.UUID `json:"user_id"`
	Weekdays    []int32   `json:"weekdays"`
}

func (q *Queries) UpsertWorkShiftMember(ctx context.Context, arg UpsertWorkShiftMemberParams) (WorkShiftMember, error) {
	row := q.db.QueryRow(ctx, upsertWorkShiftMember, arg.WorkShiftID, arg.UserID, arg.Weekdays)
	var i WorkShiftMember
	err := row.Scan(
		&i.ID,
		&i.WorkShiftID,
		&i.UserID,
		&i.Weekdays,
		&i.Active,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}
