import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { DatePipe, DecimalPipe, SlicePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { problemDetail } from '../../core/http-error';
import { BackupRun, BackupsService } from '../../core/backups/backups.service';

@Component({ selector: 'app-admin-backups', standalone: true, imports: [FormsModule, DatePipe, DecimalPipe, SlicePipe], changeDetection: ChangeDetectionStrategy.OnPush, template: `
  <section class="panel backup-panel">
    <header><div><h2>Respaldos del sistema</h2><p>Snapshot completo cifrado y comprimido, con historial verificable.</p></div><span class="status">{{ backups().length }} respaldos</span></header>
      <div class="backup-actions"><form class="backup-create" (submit)="$event.preventDefault(); create()"><label>Passphrase<input type="password" name="passphrase" [(ngModel)]="passphrase" required /></label><button type="submit" [disabled]="busy()">{{ busy() ? 'Generando...' : 'Crear backup completo' }}</button></form><form class="backup-create" (submit)="$event.preventDefault(); exportDelta()"><label>Delta<input type="password" name="deltaPassphrase" [(ngModel)]="deltaPassphrase" placeholder="Passphrase" required /></label><select name="deltaWindow" [(ngModel)]="deltaWindow"><option value="6h">Últimas 6 horas</option><option value="24h">Últimas 24 horas</option><option value="3d">Últimos 3 días</option><option value="7d">Últimos 7 días</option></select><button type="submit" [disabled]="busy()">Exportar delta</button></form><label class="backup-import">Importar delta<input type="file" accept=".enc,.zst,.backup" (change)="onDeltaSelected($event)" /></label></div>
    @if (error()) { <p class="error">{{ error() }}</p> }
      <table><thead><tr><th>Tipo</th><th>Estado</th><th>Registros</th><th>Tamaño</th><th>Checksum</th><th>Fecha</th><th></th></tr></thead><tbody>@for (backup of backups(); track backup.id) { <tr><td>{{ backup.kind }}</td><td>{{ backup.status }}</td><td>{{ backup.records_count }}</td><td>{{ backup.file_size_bytes ? (backup.file_size_bytes / 1024 | number:'1.0-0') + ' KB' : '—' }}</td><td><code>{{ backup.checksum_sha256 ? (backup.checksum_sha256 | slice:0:12) + '…' : '—' }}</code></td><td>{{ backup.started_at | date:'dd/MM/yyyy HH:mm' }}</td><td><button type="button" (click)="validate(backup)">Validar</button><a [href]="api.downloadUrl(backup.id)">Descargar</a><button type="button" (click)="remove(backup)">Eliminar</button></td></tr> } @empty { <tr><td colspan="7">No hay respaldos registrados.</td></tr> }</tbody></table>
  </section>
`, styles: [`
  .backup-panel { display:grid; gap:18px; } header { display:flex; justify-content:space-between; gap:24px; align-items:start; border-bottom:1px solid var(--border-subtle); padding-bottom:16px; } h2 { margin:0; } p { color:var(--text-secondary); } .status { color:var(--accent-cyan); } .backup-actions { display:grid; grid-template-columns:1fr 1fr auto; gap:12px; align-items:end; } .backup-create { display:flex; align-items:end; gap:12px; } label { display:grid; gap:6px; flex:1; font-size:13px; } input,select { width:100%; box-sizing:border-box; border:1px solid var(--border-subtle); border-radius:var(--radius-sm); padding:9px; background:var(--bg-app); color:var(--text-primary); } button { border:0; border-radius:var(--radius-sm); padding:9px 12px; background:var(--accent-cyan); color:var(--bg-app); cursor:pointer; } button:disabled { opacity:.55; cursor:not-allowed; } .backup-import { min-height:38px; padding:0 12px; border:1px dashed var(--border-active); border-radius:var(--radius-sm); align-items:center; justify-content:center; color:var(--text-secondary); cursor:pointer; } .backup-import input { display:none; } table { width:100%; border-collapse:collapse; } th,td { border-bottom:1px solid var(--border-subtle); padding:10px; text-align:left; } td a { color:var(--accent-cyan); margin-right:12px; } td button { background:transparent; color:var(--text-secondary); } .error { color:var(--status-critical); } @media (max-width: 900px) { .backup-actions { grid-template-columns:1fr; } }
` ] })
export class AdminBackupsComponent implements OnInit {
  protected readonly api = inject(BackupsService); protected readonly backups = signal<BackupRun[]>([]); protected readonly error = signal<string | null>(null); protected readonly busy = signal(false); protected passphrase = '';
  protected deltaPassphrase = ''; protected deltaWindow: '6h' | '12h' | '24h' | '3d' | '7d' = '24h';
  async ngOnInit(): Promise<void> { await this.load(); }
  protected async load(): Promise<void> { try { this.backups.set((await this.api.history()).items); } catch (error) { this.error.set(problemDetail(error, 'No se pudo cargar el historial de backups.')); } }
  protected async create(): Promise<void> { this.busy.set(true); try { await this.api.create(this.passphrase); this.passphrase = ''; await this.load(); } catch (error) { this.error.set(problemDetail(error, 'No se pudo crear el backup.')); } finally { this.busy.set(false); } }
  protected async exportDelta(): Promise<void> { this.busy.set(true); try { await this.api.exportDelta(this.deltaWindow, this.deltaPassphrase); this.deltaPassphrase = ''; await this.load(); } catch (error) { this.error.set(problemDetail(error, 'No se pudo exportar el delta.')); } finally { this.busy.set(false); } }
  protected async onDeltaSelected(event: Event): Promise<void> { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const passphrase = window.prompt('Passphrase del delta'); if (!passphrase) return; this.busy.set(true); try { await this.api.importDelta(file, passphrase); await this.load(); } catch (error) { this.error.set(problemDetail(error, 'No se pudo importar el delta.')); } finally { this.busy.set(false); } }
  protected async validate(backup: BackupRun): Promise<void> { const passphrase = window.prompt('Passphrase del backup'); if (!passphrase) return; this.busy.set(true); try { const result = await this.api.validate(backup.id, passphrase); this.error.set(result.valid ? `Backup íntegro: checksum y descifrado correctos (${result.tables ?? 0} tablas).` : 'Backup inválido: revisá checksum o passphrase.'); } catch (error) { this.error.set(problemDetail(error, 'No se pudo validar el backup.')); } finally { this.busy.set(false); } }
  protected async remove(backup: BackupRun): Promise<void> { try { await this.api.remove(backup.id); this.backups.update(items => items.filter(item => item.id !== backup.id)); } catch (error) { this.error.set(problemDetail(error, 'No se pudo eliminar el backup.')); } }
}